IF OBJECT_ID('CR_Reports.iron_iron_grip_func') IS NOT NULL
    DROP FUNCTION [CR_Reports].[iron_iron_grip_func];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [CR_Reports].[iron_iron_grip_func] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(


with PLAYERTABLE AS (
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, CATEGORY, EXTRA
FROM [Player_Master].[PLAYERNAMES]
WHERE "FIRSTDAY" = @FIRSTDAY AND SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS IRONNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, "PKey"
FROM PLAYERTABLE
INNER JOIN
(
SELECT "Name" AS PLAYERNAME, "Iron Club Code" AS IRONCLUBCODE, DCLUBCODE,
"Iron Brand Code" AS IRONBRAND, DBRANDCODE, "Iron Model Code" AS IRONMODEL, DMODELCODE,
"PKey"
FROM Player_Master.[Iron Detail]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID
--GROUP BY "Name", "Shaft Club Code", ISNULL(a."Mfgr Abbrev", a."Mfgr Descr"), b."Model Descr", "PKey"
) AS I
ON PLAYERTABLE.PLAYERNAME = I.PLAYERNAME
),

IRONGRIPTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS IRONGRIPNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, IRONGRIPCLUBCODE, DCLUBCODE, IRONGRIPMFGR, DMFGRCODE, IRONGRIPBRAND, DBRANDCODE, IRONGRIPMODEL, DMODELCODE, IRONGRIPMATL, DMATERIAL
FROM PLAYERTABLE
INNER JOIN
( SELECT
"Name" AS PLAYERNAME, "Grip Club Code" AS IRONGRIPCLUBCODE, DCLUBCODE,
"Grip Mfgr Code" AS IRONGRIPMFGR, DMFGRCODE,
"Grip Brand Code" AS IRONGRIPBRAND, DBRANDCODE,
"Grip Model Code" AS IRONGRIPMODEL, DMODELCODE,
"Grip Mat'l Code" AS IRONGRIPMATL, DMATERIAL,
"PKey"
FROM Player_Master.[Grip Detail]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID AND "Grip Equip Type" = 'IRON'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONTABLE.PLAYERNAME, IRONGRIPTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, IRONGRIPTABLE.CATEGORY) AS CATEGORY,
COALESCE(IRONTABLE.EXTRA, IRONGRIPTABLE.EXTRA) AS EXTRA,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE,
IRONGRIPCLUBCODE, IRONGRIPTABLE.DCLUBCODE AS DIRONGRIPCLUBCODE, IRONGRIPMFGR, IRONGRIPTABLE.DMFGRCODE AS DIRONGRIPMFGRCODE, IRONGRIPBRAND, IRONGRIPTABLE.DBRANDCODE AS DIRONGRIPBRANDCODE, IRONGRIPMODEL, IRONGRIPTABLE.DMODELCODE AS DIRONGRIPMODELCODE, IRONGRIPMATL, IRONGRIPTABLE.DMATERIAL

FROM IRONTABLE
FULL OUTER JOIN
IRONGRIPTABLE ON IRONTABLE.PLAYERNAME = IRONGRIPTABLE.PLAYERNAME AND IRONNUMBER = IRONGRIPNUMBER


)
GO
