IF OBJECT_ID('CR_Reports.ball_driver_putter_glove_shoes_func') IS NOT NULL
    DROP FUNCTION [CR_Reports].[ball_driver_putter_glove_shoes_func];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [CR_Reports].[ball_driver_putter_glove_shoes_func] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(

with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL, GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND
FROM [Player_Master].[All] d
LEFT OUTER JOIN Player_Master.PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
WHERE "FIRST DAY" = @FIRSTDAY AND d.SID = @SID
),


DRIVERTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.PLAYERNAME ORDER BY "PKey" ASC) AS DRIVERNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.PLAYERNAME) AS PLAYERNAME, CATEGORY, EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND, SHOEBRAND, DSHOEBRAND, GLOVEBRAND, DGLOVEBRAND,
WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATERIAL, DMATERIAL, "PKey"
FROM BALLTABLE
INNER JOIN
(SELECT
row_number() OVER(PARTITION BY "Name" ORDER BY "PKey" ASC) AS SUBDRIVERNUMBER,
"Name" AS PLAYERNAME, "Wood Club Code" AS WOODCLUBCODE, DCLUBCODE, "Wood Brand Code" AS WOODBRAND, DBRANDCODE, "Wood Model Code" AS WOODMODEL, DMODELCODE,
"Wood Size Code" AS WOODSIZE, DSIZECODE, "Wood Mat'l Code" AS WOODMATERIAL, DMATERIAL, "PKey"
FROM Player_Master.[Wood Detail]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID and ISDRIVER = 1
GROUP BY "Name", "Wood Club Code", "Wood Brand Code", "Wood Model Code", "PKey", DCLUBCODE, DBRANDCODE, DMODELCODE, "Wood Size Code", "Wood Mat'l Code", DSIZECODE, DMATERIAL) AS I
ON BALLTABLE.PLAYERNAME = I.PLAYERNAME
and BALLTABLE.BALLNUMBER = SUBDRIVERNUMBER 
),

PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY "PKey") AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERCLUBCODE, DCLUBCODE, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE, PUTTERMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
"Name" AS PLAYERNAME, "Putter Sequence No" AS PUTTERCLUBCODE, DCLUBCODE,
"Putter Brand Code" AS PUTTERBRAND, DBRANDCODE,
"Putter Model Code" AS PUTTERMODEL, DMODELCODE, 
"Putter Size Code" AS PUTTERSIZE, DSIZECODE,
"Putter Mat'l Code" AS PUTTERMATL, DMATERIAL,
"PKey"
FROM Player_Master.[Putter Detail]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(DRIVERTABLE.PLAYERNAME, PUTTERTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(DRIVERTABLE.CATEGORY, PUTTERTABLE.CATEGORY) AS CATEGORY, COALESCE(DRIVERTABLE.EXTRA, PUTTERTABLE.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
WOODCLUBCODE, DRIVERTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, DRIVERTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, DRIVERTABLE.DMODELCODE AS DWOODMODELCODE, DRIVERTABLE.WOODSIZE AS WOODSIZECODE, DRIVERTABLE.DSIZECODE AS DWOODSIZECODE, DRIVERTABLE.WOODMATERIAL, DRIVERTABLE.DMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, DRIVERNUMBER, PUTTERNUMBER,
ROW_NUMBER () OVER(ORDER BY COALESCE(DRIVERTABLE.EXTRA, PUTTERTABLE.EXTRA, ''), Coalesce(DRIVERTABLE.PLAYERNAME, PUTTERTABLE.PLAYERNAME), Coalesce(DRIVERNUMBER, PUTTERNUMBER)) AS ROW_ORDER


FROM DRIVERTABLE
FULL OUTER JOIN
PUTTERTABLE ON DRIVERTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND DRIVERNUMBER = PUTTERNUMBER

)
GO
