DROP FUNCTION IF EXISTS [CR_Reports].[ball_iron_wood_driver_func];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [CR_Reports].[ball_iron_wood_driver_func] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(

with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL
FROM [Player_Master].[All] d
LEFT OUTER JOIN Player_Master.PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
WHERE "FIRST DAY" = @FIRSTDAY AND d.SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.PLAYERNAME ORDER BY "PKey" ASC) AS IRONNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.PLAYERNAME) AS PLAYERNAME, COALESCE(BALLTABLE.CATEGORY, I.CATEGORY) AS CATEGORY, COALESCE(BALLTABLE.EXTRA, I.EXTRA) AS EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, "PKey"
FROM BALLTABLE
RIGHT OUTER JOIN
(SELECT
row_number() OVER(PARTITION BY d."Name" ORDER BY d."PKey" ASC) AS SUBIRONNUMBER,
"Name" AS PLAYERNAME, CATEGORY, EXTRA, "Iron Club Code" AS IRONCLUBCODE, DCLUBCODE, "Iron Brand Code" AS IRONBRAND, DBRANDCODE, "Iron Model Code" AS IRONMODEL, DMODELCODE, d."PKey"
FROM Player_Master.[Iron Detail] d
LEFT OUTER JOIN Player_master.playernames c ON c.SID = d.[Survey ID] and c.PLAYERNAME = d.Name and c.FIRSTDAY = d.[First Day]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID 
GROUP BY "Name", CATEGORY, EXTRA, "Iron Club Code", "Iron Brand Code", "Iron Model Code", d."PKey", DCLUBCODE, DBRANDCODE, DMODELCODE) AS I
ON BALLTABLE.PLAYERNAME = I.PLAYERNAME
and BALLTABLE.BALLNUMBER = SUBIRONNUMBER 
),

WOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY "PKey") AS WOODNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
"Name" AS PLAYERNAME, "Wood Club Code" AS WOODCLUBCODE, DCLUBCODE,
"Wood Brand Code" AS WOODBRAND, DBRANDCODE,
"Wood Model Code" AS WOODMODEL, DMODELCODE, 
"Wood Size Code" AS WOODSIZE, DSIZECODE,
"Wood Mat'l Code" AS WOODMATL, DMATERIAL,
"PKey"
FROM Player_Master.[Wood Detail]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONTABLE.PLAYERNAME, WOODTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, WOODTABLE.CATEGORY) AS CATEGORY, COALESCE(IRONTABLE.EXTRA, WOODTABLE.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL,
ROW_NUMBER () OVER(Order By COALESCE(IRONTABLE.EXTRA, WOODTABLE.EXTRA, ''), Coalesce(IRONTABLE.PLAYERNAME, WOODTABLE.PLAYERNAME), Coalesce(IRONNUMBER, WOODNUMBER)) AS ROW_ORDER

FROM IRONTABLE
FULL OUTER JOIN
WOODTABLE ON IRONTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND IRONNUMBER = WOODNUMBER
--Order By COALESCE(IRONTABLE.EXTRA, WOODTABLE.EXTRA, ''), Coalesce(IRONTABLE.PLAYERNAME, WOODTABLE.PLAYERNAME), Coalesce(IRONNUMBER, WOODNUMBER);

)
GO
