IF OBJECT_ID('CR_Reports.utility_iron_hybrid_wood_func') IS NOT NULL
    DROP FUNCTION [CR_Reports].[utility_iron_hybrid_wood_func];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [CR_Reports].[utility_iron_hybrid_wood_func] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(

with PLAYERTABLE AS (
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, CATEGORY, EXTRA
FROM [Player_Master].[PLAYERNAMES]
WHERE "FIRSTDAY" = @FIRSTDAY AND SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS IRONNUMBER,
PLAYERTABLE.PLAYERNAME, PLAYERTABLE.CATEGORY, PLAYERTABLE.EXTRA,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, "PKey"
FROM PLAYERTABLE
INNER JOIN
(
SELECT "Name" AS PLAYERNAME, "Iron Club Code" AS IRONCLUBCODE, DCLUBCODE, "Iron Brand Code" AS IRONBRAND, DBRANDCODE, "Iron Model Code" AS IRONMODEL, DMODELCODE, "PKey"
FROM Player_Master.[Iron Detail]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID AND "Iron Club Code" LIKE '%^%'
GROUP BY "Name", "Iron Club Code", "Iron Brand Code", "Iron Model Code", "PKey", DCLUBCODE, DBRANDCODE, DMODELCODE) AS I
ON PLAYERTABLE.PLAYERNAME = I.PLAYERNAME
),

WOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS WOODNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM PLAYERTABLE
INNER JOIN
( SELECT
"Name" AS PLAYERNAME, "Wood Club Code" AS WOODCLUBCODE, DCLUBCODE,
"Wood Brand Code" AS WOODBRAND, DBRANDCODE,
"Wood Model Code" AS WOODMODEL, DMODELCODE,
"Wood Size Code" AS WOODSIZE, DSIZECODE,
"Wood Mat'l Code" AS WOODMATL, DMATERIAL,
"PKey"
FROM Player_Master.[Wood Detail]
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID AND "Wood Club Code" = 'HYB'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONTABLE.PLAYERNAME, WOODTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, WOODTABLE.CATEGORY) AS CATEGORY,
COALESCE(IRONTABLE.EXTRA, WOODTABLE.EXTRA) AS EXTRA,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE, WOODMATL, WOODTABLE.DMATERIAL

FROM IRONTABLE
FULL OUTER JOIN
WOODTABLE ON IRONTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND IRONNUMBER = WOODNUMBER

)
GO
