IF OBJECT_ID('CR_Reports.iron_wood_shaft_func') IS NOT NULL
    DROP FUNCTION [CR_Reports].[iron_wood_shaft_func];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [CR_Reports].[iron_wood_shaft_func] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(



with PLAYERTABLE AS (
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, CATEGORY, EXTRA
FROM [Player_Master].[PLAYERNAMES]
WHERE [FIRSTDAY] = @FIRSTDAY AND SID = @SID
),


IRONSHAFTTABLE as 
(SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY 
CASE WHEN [Shaft Equip Type] = 'WEDG'
THEN [PKey] END,
CASE WHEN [Shaft Equip Type] = 'IRON'
THEN [PKey] END

) AS IRONNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, 
IRONCLUBCODE, DCLUBCODE, IRONSHAFTMFGR, DMFGRCODE, IRONSHAFTBRAND, DBRANDCODE, IRONSHAFTMODEL, DMODELCODE, IRONSHAFTMATL, DMATERIAL, [PKey]
FROM PLAYERTABLE
INNER JOIN
(
SELECT [Name] AS PLAYERNAME, [Shaft Club Code] AS IRONCLUBCODE, DCLUBCODE, [Shaft Mfgr Code] AS IRONSHAFTMFGR, DMFGRCODE,
[Shaft Brand Code] AS IRONSHAFTBRAND, DBRANDCODE, [Shaft Model Code] AS IRONSHAFTMODEL, DMODELCODE,
[Shaft Mat'l Code] AS IRONSHAFTMATL, DMATERIAL, [PKey], [Shaft Equip Type]
FROM Player_Master.[Shaft Detail]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID AND ([Shaft Equip Type] = 'IRON' OR [Shaft Equip Type] = 'WEDG')
--GROUP BY [Name], [Shaft Club Code], ISNULL(a.[Mfgr Abbrev], a.[Mfgr Descr]), b.[Model Descr], [PKey]
) AS I
ON PLAYERTABLE.PLAYERNAME = I.PLAYERNAME
),

WOODSHAFTTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY [PKey]) AS WOODNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODSHAFTMFGR, DMFGRCODE, WOODSHAFTBRAND, DBRANDCODE, WOODSHAFTMODEL, DMODELCODE, WOODSHAFTMATL, DMATERIAL
FROM PLAYERTABLE
INNER JOIN
( SELECT
[Name] AS PLAYERNAME, [Shaft Club Code] AS WOODCLUBCODE, DCLUBCODE,
[Shaft Mfgr Code] AS WOODSHAFTMFGR, DMFGRCODE,
[Shaft Brand Code] AS WOODSHAFTBRAND, DBRANDCODE,
[Shaft Model Code] AS WOODSHAFTMODEL, DMODELCODE,
[Shaft Mat'l Code] AS WOODSHAFTMATL, DMATERIAL,
[PKey]
FROM Player_Master.[Shaft Detail]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID AND [Shaft Equip Type] = 'WOOD'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONSHAFTTABLE.PLAYERNAME, WOODSHAFTTABLE.PLAYERNAME) AS PLAYERNAME,
COALESCE(IRONSHAFTTABLE.CATEGORY, WOODSHAFTTABLE.CATEGORY) AS CATEGORY, COALESCE(IRONSHAFTTABLE.EXTRA, WOODSHAFTTABLE.EXTRA) AS EXTRA,
IRONCLUBCODE AS IRONSHAFTCLUBCODE, IRONSHAFTTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONSHAFTMFGR, IRONSHAFTTABLE.DMFGRCODE AS DIRONMFGRCODE, IRONSHAFTBRAND, IRONSHAFTTABLE.DBRANDCODE AS RIRONBRANDCODE, IRONSHAFTMODEL, IRONSHAFTTABLE.DMODELCODE AS DIRONMODELCODE, IRONSHAFTMATL, IRONSHAFTTABLE.DMATERIAL AS DIRONMATL,
WOODCLUBCODE AS WOODSHAFTCLUBCODE, WOODSHAFTTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODSHAFTMFGR, WOODSHAFTTABLE.DMFGRCODE AS DWOODMFGRCODE, WOODSHAFTBRAND, WOODSHAFTTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODSHAFTMODEL, WOODSHAFTTABLE.DMODELCODE AS DWOODMODELCODE, WOODSHAFTMATL, WOODSHAFTTABLE.DMATERIAL AS DWOODMATL

FROM IRONSHAFTTABLE
FULL OUTER JOIN
WOODSHAFTTABLE ON IRONSHAFTTABLE.PLAYERNAME = WOODSHAFTTABLE.PLAYERNAME AND IRONNUMBER = WOODNUMBER



)
GO
