DROP FUNCTION IF EXISTS [dbo].[base_report_old];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[base_report_old] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(


with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, HEADGEARBRAND AS HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND 
FROM [Player_Master].[All] d
LEFT OUTER JOIN [Player_master].PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
WHERE "FIRST DAY" = @FIRSTDAY AND d.SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.Name ORDER BY "PKey" ASC) AS IRONNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.Name) AS PLAYERNAME, COALESCE(BALLTABLE.CATEGORY, I.CATEGORY) AS CATEGORY, COALESCE(BALLTABLE.EXTRA, I.EXTRA) AS EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, "PKey"
FROM BALLTABLE
RIGHT OUTER JOIN
(SELECT
row_number() OVER(PARTITION BY Name ORDER BY "PKey" ASC) AS SUBIRONNUMBER, * FROM
--irons
( SELECT
Name, CATEGORY, EXTRA, [Iron Club Code] AS IRONCLUBCODE, DCLUBCODE, [Iron Brand Code] AS IRONBRAND, DBRANDCODE, [Iron Model Code] AS IRONMODEL, DMODELCODE, c."PKey"
FROM [Player_Master].[Iron Detail] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d ON c.[Survey ID] = d.SID and c.Name = d.PLAYERNAME and c.[First Day] = d.FIRSTDAY 
WHERE "First Day" = @FIRSTDAY AND [Survey ID] = @SID 
GROUP BY Name, CATEGORY, EXTRA, [Iron Club Code], [Iron Brand Code], [Iron Model Code], c."PKey", DCLUBCODE, DBRANDCODE, DMODELCODE)
subtable) AS I
ON BALLTABLE.PLAYERNAME = I.name
and BALLTABLE.BALLNUMBER = SUBIRONNUMBER 
),

WOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY "PKey") AS WOODNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
name, [Wood Club Code] AS WOODCLUBCODE, DCLUBCODE,
[Wood Brand Code] AS WOODBRAND, DBRANDCODE,
[Wood Model Code] AS WOODMODEL, DMODELCODE, 
[Wood Size Code] AS WOODSIZE, DSIZECODE,
[Wood Mat'l Code] AS WOODMATL, DMATERIAL,
"PKey"
FROM [Player_Master].[Wood Detail]
WHERE "First Day" = @FIRSTDAY AND [Survey ID] = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.name
),

PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY "PKey") AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE
FROM BALLTABLE
INNER JOIN
( SELECT
name, [Putter Sequence No] AS PUTTERCLUBCODE, DCLUBCODE,
[Putter Brand Code] AS PUTTERBRAND, DBRANDCODE,
[Putter Model Code] AS PUTTERMODEL, DMODELCODE, 
[Putter Size Code] AS PUTTERSIZE, DSIZECODE,
"PKey"
FROM [Player_Master].[Putter Detail]
WHERE "First Day" = @FIRSTDAY AND [Survey ID] = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.name
),

WEDGETABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY "PKey") AS WEDGENUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WEDGECLUBCODE, DCLUBCODE, WEDGEBRAND, DBRANDCODE, WEDGEMODEL, DMODELCODE, WEDGETYPE, DTYPECODE
FROM BALLTABLE
INNER JOIN
( SELECT
name, [Wedge Club Code] AS WEDGECLUBCODE, DCLUBCODE,
[Wedge Brand Code] AS WEDGEBRAND, DBRANDCODE,
[Wedge Model Code] AS WEDGEMODEL, DMODELCODE, 
[Wedge Type Code] AS WEDGETYPE, DTYPECODE,
"PKey"
FROM [Player_Master].[Wedge Detail]
WHERE "First Day" = @FIRSTDAY AND [Survey ID] = @SID 
) X
ON BALLTABLE.PLAYERNAME = X.name
),

SHAFTTABLE AS (
SELECT Pkey,
[Shaft Club Code],
[Shaft Equip Type],
[Shaft Mfgr Code] AS SHAFTMFGR, DMFGRCODE AS DSHAFTMFGRCODE,
[Shaft Brand Code] AS SHAFTBRAND, DBRANDCODE AS DSHAFTBRANDCODE,
[Shaft Model Code] AS SHAFTMODEL, DMODELCODE AS DSHAFTMODELCODE,
[Shaft Mat'l Code] AS SHAFTMATL, DMATERIAL AS DSHAFTMATLCODE
FROM Player_master.[Shaft Detail] a
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID),

GRIPTABLE AS (
SELECT Pkey,
[Grip Club Code],
[Grip Equip Type],
[Grip Mfgr Code] AS GRIPMFGR, DMFGRCODE AS DGRIPMFGRCODE,
[Grip Brand Code] AS GRIPBRAND, DBRANDCODE AS DGRIPBRANDCODE,
[Grip Model Code] AS GRIPMODEL, DMODELCODE AS DGRIPMODELCODE,
[Grip Mat'l Code] AS GRIPMATL, DMATERIAL AS DGRIPMATLCODE
FROM Player_master.[Grip Detail] a
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID)





SELECT COALESCE(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, woodwedge.CATEGORY) AS CATEGORY, COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE,
IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
WEDGECLUBCODE, DWEDGECLUBCODE, WEDGEBRAND, DWEDGEBRANDCODE, WEDGEMODEL, DWEDGEMODELCODE, WEDGETYPE, DWEDGETYPE,
WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
WOODCLUBCODE, DWOODCLUBCODE, WOODBRAND, DWOODBRANDCODE, WOODMODEL, DWOODMODELCODE, WOODSIZE, DWOODSIZECODE, WOODMATL, DMATERIAL,
WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND AS SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND,
ROW_NUMBER () OVER(Order By COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA, ''), Coalesce(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME), Coalesce(IRONNUMBER, WEDGEWOODNUMBER)) AS ROW_ORDER



FROM IRONTABLE
FULL OUTER JOIN

(SELECT COALESCE(WOODTABLE.PLAYERNAME, WEDGETABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(WOODTABLE.CATEGORY, WEDGETABLE.CATEGORY) AS CATEGORY, COALESCE(WOODTABLE.EXTRA, WEDGETABLE.EXTRA) AS EXTRA,
WEDGECLUBCODE, WEDGETABLE.DCLUBCODE AS DWEDGECLUBCODE, WEDGEBRAND, WEDGETABLE.DBRANDCODE AS DWEDGEBRANDCODE, WEDGEMODEL, WEDGETABLE.DMODELCODE AS DWEDGEMODELCODE, WEDGETYPE, WEDGETABLE.DTYPECODE AS DWEDGETYPE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE AS DWOODSIZECODE, WOODMATL, DMATERIAL,
COALESCE(WEDGENUMBER, WOODNUMBER) AS WEDGEWOODNUMBER FROM WOODTABLE
FULL OUTER JOIN
WEDGETABLE ON WOODTABLE.PLAYERNAME = WEDGETABLE.PLAYERNAME AND WEDGENUMBER = WOODNUMBER ) woodwedge
ON IRONTABLE.PLAYERNAME = woodwedge.PLAYERNAME AND IRONNUMBER = WEDGEWOODNUMBER

FULL OUTER JOIN 
PUTTERTABLE ON IRONTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND PUTTERNUMBER = IRONNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS IRONSHAFTNUMBER,
SHAFTMFGR AS IRONSHAFTMFGR, DSHAFTMFGRCODE AS DIRONSHAFTMFGR,
SHAFTBRAND AS IRONSHAFTBRAND, DSHAFTBRANDCODE AS DIRONSHAFTBRAND,
SHAFTMODEL AS IRONSHAFTMODEL, DSHAFTMODELCODE AS DIRONSHAFTMODEL,
SHAFTMATL AS IRONSHAFTMATL, DSHAFTMATLCODE AS DIRONSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'IRON') ironshaft ON IRONNUMBER = IRONSHAFTNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WEDGESHAFTNUMBER,
SHAFTMFGR AS WEDGESHAFTMFGR, DSHAFTMFGRCODE AS DWEDGESHAFTMFGR,
SHAFTBRAND AS WEDGESHAFTBRAND, DSHAFTBRANDCODE AS DWEDGESHAFTBRAND,
SHAFTMODEL AS WEDGESHAFTMODEL, DSHAFTMODELCODE AS DWEDGESHAFTMODEL,
SHAFTMATL AS WEDGESHAFTMATL, DSHAFTMATLCODE AS DWEDGESHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WEDG') wedgeshaft ON WEDGEWOODNUMBER = WEDGESHAFTNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WOODSHAFTNUMBER,
SHAFTMFGR AS WOODSHAFTMFGR, DSHAFTMFGRCODE AS DWOODSHAFTMFGR,
SHAFTBRAND AS WOODSHAFTBRAND, DSHAFTBRANDCODE AS DWOODSHAFTBRAND,
SHAFTMODEL AS WOODSHAFTMODEL, DSHAFTMODELCODE AS DWOODSHAFTMODEL,
SHAFTMATL AS WOODSHAFTMATL, DSHAFTMATLCODE AS DWOODSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WOOD') woodshaft ON WEDGEWOODNUMBER = WOODSHAFTNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS IRONGRIPNUMBER,
GRIPMFGR AS IRONGRIPMFGR, DGRIPMFGRCODE AS DIRONGRIPMFGR,
GRIPBRAND AS IRONGRIPBRAND, DGRIPBRANDCODE AS DIRONGRIPBRAND,
GRIPMODEL AS IRONGRIPMODEL, DGRIPMODELCODE AS DIRONGRIPMODEL,
GRIPMATL AS IRONGRIPMATL, DGRIPMATLCODE AS DIRONGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'IRON') irongrip ON IRONNUMBER = IRONGRIPNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WEDGEGRIPNUMBER,
GRIPMFGR AS WEDGEGRIPMFGR, DGRIPMFGRCODE AS DWEDGEGRIPMFGR,
GRIPBRAND AS WEDGEGRIPBRAND, DGRIPBRANDCODE AS DWEDGEGRIPBRAND,
GRIPMODEL AS WEDGEGRIPMODEL, DGRIPMODELCODE AS DWEDGEGRIPMODEL,
GRIPMATL AS WEDGEGRIPMATL, DGRIPMATLCODE AS DWEDGEGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WEDG') wedgegrip ON WEDGEWOODNUMBER = WEDGEGRIPNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WOODGRIPNUMBER,
GRIPMFGR AS WOODGRIPMFGR, DGRIPMFGRCODE AS DWOODGRIPMFGR,
GRIPBRAND AS WOODGRIPBRAND, DGRIPBRANDCODE AS DWOODGRIPBRAND,
GRIPMODEL AS WOODGRIPMODEL, DGRIPMODELCODE AS DWOODGRIPMODEL,
GRIPMATL AS WOODGRIPMATL, DGRIPMATLCODE AS DWOODGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WOOD') woodgrip ON WEDGEWOODNUMBER = WOODGRIPNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS PUTTERGRIPNUMBER,
GRIPMFGR AS PUTTERGRIPMFGR, DGRIPMFGRCODE AS DPUTTERGRIPMFGR,
GRIPBRAND AS PUTTERGRIPBRAND, DGRIPBRANDCODE AS DPUTTERGRIPBRAND,
GRIPMODEL AS PUTTERGRIPMODEL, DGRIPMODELCODE AS DPUTTERGRIPMODEL,
GRIPMATL AS PUTTERGRIPMATL, DGRIPMATLCODE AS DPUTTERGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'PUTT') puttergrip ON PUTTERNUMBER = PUTTERGRIPNUMBER

)



--  select * from [Media].[base_report]('8/4/2011', 648) ORDER BY row_order
GO
