IF OBJECT_ID('dbo.base_report') IS NOT NULL
    DROP FUNCTION [dbo].[base_report];
GO

CREATE FUNCTION [dbo].[base_report] 
(	
	@FIRSTDAY datetime,
	@SID int, 
	@GROUP_ID int,
	@VIEW_LEVEL int,
	@IS_ABBREV int = 0,
	@WOODVAR int,
	@IRONVAR int
)
RETURNS TABLE 
AS
RETURN 
(

/*  @WOODVAR
1 - drivers
2 - hybrids
3 - fairway w/ hyb
4 - fairway w/o hyb
other - all

@IRONVAR
1 - utility
other - all
*/
	
	

with cte_main as (
SELECT a.PLAYERNAME as pname, SequenceNum as LINE_NUMBER, CATEGORY, EXTRA
FROM [Player_Master].[All] a
inner JOIN [Player_master].PLAYERNAMES c on a.PLAYERNAME = c.PLAYERNAME AND a.SID = c.SID AND a.[FIRST DAY] = c.FIRSTDAY
CROSS JOIN (select top 7 SequenceNum from LKP.Sequence order by SequenceNum) q
WHERE [FIRST DAY] = @FIRSTDAY AND a.SID = @SID),



BALLTABLE AS (
SELECT 1 as BALLNUMBER, d.PLAYERNAME, 
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS BALLBRAND, DBALLBRAND,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS BALLMODEL, DBALLMODEL,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(e.[Mfgr Abbrev], e.[Mfgr Descr]) ELSE e.[Mfgr Descr] END AS GLOVEBRAND, DGLOVEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(f.[Mfgr Abbrev], f.[Mfgr Descr]) ELSE f.[Mfgr Descr] END AS SHOEBRAND, DSHOEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(g.[Mfgr Abbrev], g.[Mfgr Descr]) ELSE g.[Mfgr Descr] END AS HATBRAND, DHEADGEARBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(zzz.[Mfgr Abbrev], zzz.[Mfgr Descr]) ELSE zzz.[Mfgr Descr] END AS SHIRTBRAND, DSHIRTBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(abc.[Mfgr Abbrev], abc.[Mfgr Descr]) ELSE abc.[Mfgr Descr] END AS CADDYHEADBRAND, DCADDYHEADBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(yyy.[Mfgr Abbrev], yyy.[Mfgr Descr]) ELSE yyy.[Mfgr Descr] END AS GLASSESBRAND, DGLASSESBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(qqq.[Mfgr Abbrev], qqq.[Mfgr Descr]) ELSE qqq.[Mfgr Descr] END AS RAINGEARBRAND, DRAINGEARBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(h.[Mfgr Abbrev], h.[Mfgr Descr]) ELSE h.[Mfgr Descr] END AS BAGBRAND, DBAGBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(i.[Mfgr Abbrev], i.[Mfgr Descr]) ELSE i.[Mfgr Descr] END AS SPIKEBRAND, DSPIKEBRAND,
(CASE WHEN (i.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN j.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN j.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN j.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN j.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN j.[Model Lvl3] END) END) AS SPIKEMODEL, DSPIKEMODEL
FROM [Player_Master].[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] e ON GLOVEBRAND = e.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] f ON SHOEBRAND = f.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON HEADGEARBRAND = g.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] zzz ON SHIRTBRAND = zzz.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] abc ON CADDYHEADBRAND = abc.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] yyy ON GLASSESBRAND = yyy.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] qqq ON RAINGEARBRAND = qqq.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] h ON BAGBRAND = h.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] i ON SPIKEBRAND = i.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] j ON SPIKEMODEL = j.[Model Code]
WHERE [FIRST DAY] = @FIRSTDAY AND d.SID = @SID
),


IRONTABLE as 
(select * from (
SELECT row_number() OVER(PARTITION BY Name ORDER BY c.[PKey] ASC) as IRONNUMBER, [Iron Club Code],
Name as PLAYERNAME, [Iron Club Code] AS IRONCLUBCODE, DCLUBCODE, 
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS IRONBRAND, DBRANDCODE, 
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups with (nolock) WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS IRONMODEL, DMODELCODE, 
NULL AS IRONTYPE, NULL AS DTYPECODE
FROM [Player_Master].[Iron Detail] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d ON c.[Survey ID] = d.SID and c.Name = d.PLAYERNAME and c.[First Day] = d.FIRSTDAY 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Iron Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Iron Model Code] = b.[Model Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID) z
where @IRONVAR = 0 Or (@IRONVAR = 1 And [Iron Club Code] like '%^%')
),



WOODTABLE AS (
SELECT  row_number() OVER(PARTITION BY Name ORDER BY [PKey] ASC) as WOODNUMBER,
name as PLAYERNAME, 
[Wood Club Code] AS WOODCLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WOODBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups with (nolock) WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WOODMODEL, DMODELCODE,
c.[Size Descr] AS WOODSIZE, DSIZECODE,
COALESCE(d.[Matl Abbrev], d.[Matl Descr]) AS WOODMATL, DMATERIAL,
ISDRIVER
FROM [Player_Master].[Wood Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wood Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wood Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Wood Size Code] = [Size Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON [Wood Mat'l Code] = [Matl Code]
WHERE [First Day] = @FIRSTDAY AND 
		[Survey ID] = @SID 
		and
		(@WOODVAR = 0 Or 
			 (@WOODVAR = 1 and ISDRIVER = 1) Or
			 (@WOODVAR = 2 and [Wood Club Code] = 'HYB') or
			 (@WOODVAR = 3 and ISDRIVER = 0) or
			 (@WOODVAR = 4 and ISDRIVER = 0 and [Wood Club Code] <> 'HYB') OR
			 (@WOODVAR = 5 and [Wood Club Code] <> 'HYB')
		)
		
		
		--	 --(ISDRIVER = 1 And @WOODVAR = 1) OR
		--	 --(ISDRIVER = 0 And (@WOODVAR = 3 OR (@WOODVAR = 4 and [Wood Club Code] <> 'HYB') OR (@WOODVAR = 2 and [Wood Club Code] = 'HYB'))) OR
		--	 --(@WOODVAR = 5 and [Wood Club Code] <> 'HYB')
		
		--and
		--COALESCE(ISDRIVER, 0) = CASE WHEN @WOODVAR = 1 THEN 1 ELSE COALESCE(ISDRIVER, 0) END
		-- hybrids
		--AND [Wood Club Code] = CASE WHEN @WOODVAR = 2 THEN 'HYB' ELSE [Wood Club Code] END
		-- fairways w/ hybrids
		--AND ISDRIVER <> CASE WHEN @WOODVAR = 3 THEN 1 ELSE 4 END
		-- fairways w/o hybrids
		--AND (ISDRIVER <> CASE WHEN @WOODVAR = 4 THEN 1 ELSE 4 END
		--AND [Wood Club Code] <> CASE WHEN @WOODVAR = 4 THEN 'HYB' ELSE 'X' END)
		-- woods w/o hybrids
		--AND [Wood Club Code] <> CASE WHEN @WOODVAR = 5 THEN 'HYB' ELSE 'X' END 
		--and 
		--((@WOODVAR = 1 and ISDRIVER = 1) OR 
		--	 (@WOODVAR = 2 and [Wood Club Code] = 'HYB') or
		--	 (@WOODVAR = 3 and ISDRIVER = 0) or
		--	 (@WOODVAR = 4 and ISDRIVER = 0 and [Wood Club Code] <> 'HYB') OR
		--	 (@WOODVAR = 5 and [Wood Club Code] <> 'HYB'))
		
		--and ISDRIVER = case when @WOODVAR in (1, 5) then 1 else 0
		--and [Wood Club Code] = case when @WOODVAR in (2, 
				 
),



PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY name ORDER BY [PKey]) AS PUTTERNUMBER,
name as PLAYERNAME, 
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS PUTTERBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS PUTTERMODEL, DMODELCODE,
c.[Size Descr] AS PUTTERSIZE, DSIZECODE
FROM [Player_Master].[Putter Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Putter Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Putter Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Putter Size Code] = [Size Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
),





WEDGETABLE AS (
SELECT
row_number() OVER(PARTITION BY name ORDER BY [PKey]) AS WEDGENUMBER,
name as PLAYERNAME, [Wedge Club Code] AS WEDGECLUBCODE, DCLUBCODE, CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WEDGEBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN COALESCE(mg.modelgroup + '; ' + isnull(mg.[AttributeBounce],'') + isnull(mg.[AttributeGrind],''), b.[Model Descr]) ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN COALESCE(mg.modelgroup + '; ' + isnull(mg.[AttributeBounce],'') + isnull(mg.[AttributeGrind],''), b.[Model Descr]) WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WEDGEMODEL, DMODELCODE,
c.[Type Descr] AS WEDGETYPE, DTYPECODE
FROM [Player_Master].[Wedge Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wedge Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wedge Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Type Codes and Description] c ON [Wedge Type Code] = [Type Code]
LEFT OUTER JOIN LKP.ModelGroup mg ON [Wedge Model Code] = mg.ModelCode
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
),


SHAFTTABLE AS (
SELECT row_number() OVER(PARTITION BY name, [Shaft Equip Type] ORDER BY [PKey]) AS SHAFTNUMBER,
Name AS PLAYERNAME, [Shaft Club Code], DCLUBCODE, [Shaft Equip Type], 
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS SHAFTMFGR, DMFGRCODE AS DSHAFTMFGRCODE,  
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS SHAFTBRAND,DBRANDCODE AS DSHAFTBRANDCODE, 
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups with (nolock) WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS SHAFTMODEL, DMODELCODE AS DSHAFTMODELCODE,
f.[Flex Descr] AS SHAFTFLEX, [DFLEXCODE] AS DSHAFTFLEX,
COALESCE(e.[Matl Abbrev], e.[Matl Descr]) AS SHAFTMATL, 
DMATERIAL AS DSHAFTMATLCODE
FROM Player_master.[Shaft Detail] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.[Shaft Mfgr Code] = b.[Mfgr Code]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.[Shaft Brand Code] = c.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.[Shaft Model Code] = d.[Model Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.[Shaft Mat'l Code] = e.[Matl Code]
LEFT OUTER JOIN LKP.[Flex Codes and Desc] f  with (nolock) on a.[Shaft Flex Code] = f.[Flex Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID),




GRIPTABLE AS (
SELECT row_number() OVER(PARTITION BY name, [Grip Equip Type] ORDER BY [PKey]) AS GRIPNUMBER,
Name AS PLAYERNAME, [Grip Club Code], DCLUBCODE, [Grip Equip Type], 
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS GRIPMFGR, DMFGRCODE AS DGRIPMFGRCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS GRIPBRAND, DBRANDCODE AS DGRIPBRANDCODE,
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups with (nolock) WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS GRIPMODEL, DMODELCODE AS DGRIPMODELCODE,
COALESCE(e.[Matl Abbrev], e.[Matl Descr]) AS GRIPMATL, DMATERIAL AS DGRIPMATLCODE
FROM Player_master.[Grip Detail] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.[Grip Mfgr Code] = b.[Mfgr Code]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.[Grip Brand Code] = c.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.[Grip Model Code] = d.[Model Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.[Grip Mat'l Code] = e.[Matl Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID),






--select PLAYERNAME, CATEGORY, EXTRA,
--BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
--IRONCLUBCODE, DIRONCLUBCODE, IRONBRAND, DIRONBRANDCODE, IRONMODEL, DIRONMODELCODE, IRONSIZE, DIRONSIZECODE,
--IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTFLEX, DIRONSHAFTFLEX, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
--IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
--IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
--IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE, WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE, PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
--WEDGECLUBCODE, DWEDGECLUBCODE, WEDGEBRAND, DWEDGEBRANDCODE, WEDGEMODEL, DWEDGEMODELCODE, WEDGETYPE, DWEDGETYPE,
--WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTFLEX, DWEDGESHAFTFLEX, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
--WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
--WOODCLUBCODE, DWOODCLUBCODE, WOODBRAND, DWOODBRANDCODE, WOODMODEL, DWOODMODELCODE, WOODSIZE, DWOODSIZECODE, WOODMATL, DMATERIAL,
--WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTFLEX, DWOODSHAFTFLEX, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
--WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
--PUTTERBRAND, DPUTTERBRANDCODE, PUTTERMODEL, DPUTTERMODELCODE, PUTTERSIZE, DPUTTERSIZECODE,
--PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
--GLOVEBRAND, DGLOVEBRAND, SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SHIRTBRAND, DSHIRTBRAND,CADDYHEADBRAND, DCADDYHEADBRAND,GLASSESBRAND, DGLASSESBRAND,RAINGEARBRAND, DRAINGEARBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL


cte1 as (
select pname,
		LINE_NUMBER,
		coalesce(irontable.PLAYERNAME, WEDGETABLE.PLAYERNAME, WOODTABLE.PLAYERNAME) AS PLAYERNAME,
		CATEGORY, EXTRA, BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
		IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE,IRONTABLE.IRONTYPE AS IRONSIZE, IRONTABLE.DTYPECODE AS DIRONSIZECODE,
		IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTFLEX, DIRONSHAFTFLEX, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
		IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
		WEDGECLUBCODE, WEDGETABLE.DCLUBCODE AS DWEDGECLUBCODE, WEDGEBRAND, WEDGETABLE.DBRANDCODE AS DWEDGEBRANDCODE, WEDGEMODEL, WEDGETABLE.DMODELCODE AS DWEDGEMODELCODE, WEDGETYPE, WEDGETABLE.DTYPECODE AS DWEDGETYPE,
		WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTFLEX, DWEDGESHAFTFLEX, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
		WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
		WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE AS DWOODSIZECODE, WOODMATL, DMATERIAL,
		WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTFLEX, DWOODSHAFTFLEX, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
		WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
		PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
		PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
		GLOVEBRAND, DGLOVEBRAND, SHOEBRAND AS SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND,
		SHIRTBRAND, DSHIRTBRAND,CADDYHEADBRAND, DCADDYHEADBRAND,GLASSESBRAND, DGLASSESBRAND,RAINGEARBRAND, DRAINGEARBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL,
		IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
		IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE, WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE, PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
		ROW_NUMBER() over(order by extra, pname, LINE_NUMBER) as ROW_ORDER
FROM cte_main
left outer join IRONTABLE ON cte_main.pname = IRONTABLE.PLAYERNAME AND IRONNUMBER = LINE_NUMBER
left OUTER JOIN WEDGETABLE ON cte_main.pname = WEDGETABLE.PLAYERNAME AND WEDGENUMBER = LINE_NUMBER
left OUTER JOIN WOODTABLE ON cte_main.pname = WOODTABLE.PLAYERNAME AND WOODNUMBER = LINE_NUMBER
left outer join PUTTERTABLE ON cte_main.pname = PUTTERTABLE.PLAYERNAME AND PUTTERNUMBER = LINE_NUMBER
left outer join BALLTABLE ON cte_main.pname = BALLTABLE.PLAYERNAME AND BALLNUMBER = LINE_NUMBER
left outer join
	(SELECT PLAYERNAME, SHAFTNUMBER AS IRONSHAFTNUMBER, [Shaft Club Code] as IRONSHAFTCLUBCODE, DCLUBCODE as DIRONSHAFTCLUBCODE, SHAFTMFGR AS IRONSHAFTMFGR, DSHAFTMFGRCODE AS DIRONSHAFTMFGR, SHAFTBRAND AS IRONSHAFTBRAND, DSHAFTBRANDCODE AS DIRONSHAFTBRAND,
	    SHAFTMODEL AS IRONSHAFTMODEL, DSHAFTMODELCODE AS DIRONSHAFTMODEL, SHAFTFLEX as IRONSHAFTFLEX, DSHAFTFLEX as DIRONSHAFTFLEX, SHAFTMATL AS IRONSHAFTMATL, DSHAFTMATLCODE AS DIRONSHAFTMATERIAL
        FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'IRON') ironshaft 
ON cte_main.pname = ironshaft.PLAYERNAME AND IRONSHAFTNUMBER = LINE_NUMBER
left outer join
	(SELECT PLAYERNAME, SHAFTNUMBER AS WEDGESHAFTNUMBER, [Shaft Club Code] as WEDGESHAFTCLUBCODE, DCLUBCODE as DWEDGESHAFTCLUBCODE, SHAFTMFGR AS WEDGESHAFTMFGR, DSHAFTMFGRCODE AS DWEDGESHAFTMFGR, SHAFTBRAND AS WEDGESHAFTBRAND, DSHAFTBRANDCODE AS DWEDGESHAFTBRAND,
		SHAFTMODEL AS WEDGESHAFTMODEL, DSHAFTMODELCODE AS DWEDGESHAFTMODEL, SHAFTFLEX as WEDGESHAFTFLEX, DSHAFTFLEX as DWEDGESHAFTFLEX, SHAFTMATL AS WEDGESHAFTMATL, DSHAFTMATLCODE AS DWEDGESHAFTMATERIAL
		FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WEDG') wedgeshaft 
ON cte_main.pname = wedgeshaft.PLAYERNAME AND WEDGESHAFTNUMBER = LINE_NUMBER
left outer join
	(SELECT PLAYERNAME, SHAFTNUMBER AS WOODSHAFTNUMBER, [Shaft Club Code] as WOODSHAFTCLUBCODE, DCLUBCODE as DWOODSHAFTCLUBCODE, SHAFTMFGR AS WOODSHAFTMFGR, DSHAFTMFGRCODE AS DWOODSHAFTMFGR, SHAFTBRAND AS WOODSHAFTBRAND, DSHAFTBRANDCODE AS DWOODSHAFTBRAND,
		SHAFTMODEL AS WOODSHAFTMODEL, DSHAFTMODELCODE AS DWOODSHAFTMODEL, SHAFTFLEX as WOODSHAFTFLEX, DSHAFTFLEX as DWOODSHAFTFLEX, SHAFTMATL AS WOODSHAFTMATL, DSHAFTMATLCODE AS DWOODSHAFTMATERIAL
		FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WOOD') woodshaft 
ON cte_main.pname = woodshaft.PLAYERNAME AND WOODSHAFTNUMBER = LINE_NUMBER
left outer join
	(SELECT PLAYERNAME, GRIPNUMBER AS IRONGRIPNUMBER, [Grip Club Code] as IRONGRIPCLUBCODE, DCLUBCODE as DIRONGRIPCLUBCODE, GRIPMFGR AS IRONGRIPMFGR, DGRIPMFGRCODE AS DIRONGRIPMFGR, GRIPBRAND AS IRONGRIPBRAND, DGRIPBRANDCODE AS DIRONGRIPBRAND,
		GRIPMODEL AS IRONGRIPMODEL, DGRIPMODELCODE AS DIRONGRIPMODEL, GRIPMATL AS IRONGRIPMATL, DGRIPMATLCODE AS DIRONGRIPMATERIAL
		FROM GRIPTABLE WHERE [Grip Equip Type] = 'IRON') irongrip 
ON cte_main.pname = irongrip.PLAYERNAME AND IRONGRIPNUMBER = LINE_NUMBER
left outer join
	(SELECT PLAYERNAME, GRIPNUMBER AS WEDGEGRIPNUMBER, [Grip Club Code] as WEDGEGRIPCLUBCODE, DCLUBCODE as DWEDGEGRIPCLUBCODE, GRIPMFGR AS WEDGEGRIPMFGR, DGRIPMFGRCODE AS DWEDGEGRIPMFGR, GRIPBRAND AS WEDGEGRIPBRAND, DGRIPBRANDCODE AS DWEDGEGRIPBRAND,
		GRIPMODEL AS WEDGEGRIPMODEL, DGRIPMODELCODE AS DWEDGEGRIPMODEL, GRIPMATL AS WEDGEGRIPMATL, DGRIPMATLCODE AS DWEDGEGRIPMATERIAL
		FROM GRIPTABLE WHERE [Grip Equip Type] = 'WEDG') wedgegrip 
ON cte_main.pname = wedgegrip.PLAYERNAME AND WEDGEGRIPNUMBER = LINE_NUMBER
left outer join
	(SELECT PLAYERNAME, GRIPNUMBER AS WOODGRIPNUMBER, [Grip Club Code] as WOODGRIPCLUBCODE, DCLUBCODE as DWOODGRIPCLUBCODE, GRIPMFGR AS WOODGRIPMFGR, DGRIPMFGRCODE AS DWOODGRIPMFGR, GRIPBRAND AS WOODGRIPBRAND, DGRIPBRANDCODE AS DWOODGRIPBRAND,
		GRIPMODEL AS WOODGRIPMODEL, DGRIPMODELCODE AS DWOODGRIPMODEL, GRIPMATL AS WOODGRIPMATL, DGRIPMATLCODE AS DWOODGRIPMATERIAL 
		FROM GRIPTABLE WHERE [Grip Equip Type] = 'WOOD') woodgrip 
ON cte_main.pname = woodgrip.PLAYERNAME AND WOODGRIPNUMBER = LINE_NUMBER
left outer join
	(SELECT PLAYERNAME, GRIPNUMBER AS PUTTERGRIPNUMBER, [Grip Club Code] as PUTTERGRIPCLUBCODE, DCLUBCODE as DPUTTERGRIPCLUBCODE, GRIPMFGR AS PUTTERGRIPMFGR, DGRIPMFGRCODE AS DPUTTERGRIPMFGR, GRIPBRAND AS PUTTERGRIPBRAND, DGRIPBRANDCODE AS DPUTTERGRIPBRAND,
		GRIPMODEL AS PUTTERGRIPMODEL, DGRIPMODELCODE AS DPUTTERGRIPMODEL, GRIPMATL AS PUTTERGRIPMATL, DGRIPMATLCODE AS DPUTTERGRIPMATERIAL
		FROM GRIPTABLE WHERE [Grip Equip Type] = 'PUTT') puttergrip 
ON cte_main.pname = puttergrip.PLAYERNAME AND PUTTERGRIPNUMBER = LINE_NUMBER)





--select PLAYERNAME, CATEGORY, EXTRA,
--BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
--IRONCLUBCODE, DIRONCLUBCODE, IRONBRAND, DIRONBRANDCODE, IRONMODEL, DIRONMODELCODE, IRONSIZE, DIRONSIZECODE,
--IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTFLEX, DIRONSHAFTFLEX, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
--IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
--IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
--IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE, WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE, PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
--WEDGECLUBCODE, DWEDGECLUBCODE, WEDGEBRAND, DWEDGEBRANDCODE, WEDGEMODEL, DWEDGEMODELCODE, WEDGETYPE, DWEDGETYPE,
--WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTFLEX, DWEDGESHAFTFLEX, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
--WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
--WOODCLUBCODE, DWOODCLUBCODE, WOODBRAND, DWOODBRANDCODE, WOODMODEL, DWOODMODELCODE, WOODSIZE, DWOODSIZECODE, WOODMATL, DMATERIAL,
--WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTFLEX, DWOODSHAFTFLEX, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
--WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
--PUTTERBRAND, DPUTTERBRANDCODE, PUTTERMODEL, DPUTTERMODELCODE, PUTTERSIZE, DPUTTERSIZECODE,
--PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
--GLOVEBRAND, DGLOVEBRAND, SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SHIRTBRAND, DSHIRTBRAND,CADDYHEADBRAND, DCADDYHEADBRAND,GLASSESBRAND, DGLASSESBRAND,RAINGEARBRAND, DRAINGEARBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL

select *
from cte1 
where PLAYERNAME is not null









)
GO
