IF OBJECT_ID('dbo.base_report_byplayer_old') IS NOT NULL
    DROP FUNCTION [dbo].[base_report_byplayer_old];
GO

CREATE FUNCTION [dbo].[base_report_byplayer_old] 
(	
	@FIRSTDAY date,
	@SID int, 
	@GROUP_ID int,
	@VIEW_LEVEL int,
	@IS_ABBREV int = 0,
	@WOODVAR int,
	@IRONVAR int,
	@PLAYERLOOKUP varchar(100) = '',
	@TOUR varchar(100)
)
RETURNS TABLE 
AS
RETURN 
(

/*  @WOODVAR
1 - drivers
2 - hybrids
3 - fairway w/ hyb
4 - fairway w/o hyb
5 - Wood w/o hyb
other - all

@IRONVAR
1 - utility
other - all
*/

-- changed by Charles 5/28/2019

with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, d.SID, d.[FIRST DAY], CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS BALLBRAND, DBALLBRAND,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS BALLMODEL, DBALLMODEL,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(e.[Mfgr Abbrev], e.[Mfgr Descr]) ELSE e.[Mfgr Descr] END AS GLOVEBRAND, DGLOVEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(f.[Mfgr Abbrev], f.[Mfgr Descr]) ELSE f.[Mfgr Descr] END AS SHOEBRAND, DSHOEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(g.[Mfgr Abbrev], g.[Mfgr Descr]) ELSE g.[Mfgr Descr] END AS HATBRAND, DHEADGEARBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(zzz.[Mfgr Abbrev], zzz.[Mfgr Descr]) ELSE zzz.[Mfgr Descr] END AS SHIRTBRAND, DSHIRTBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(abc.[Mfgr Abbrev], abc.[Mfgr Descr]) ELSE abc.[Mfgr Descr] END AS CADDYHEADBRAND, DCADDYHEADBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(yyy.[Mfgr Abbrev], yyy.[Mfgr Descr]) ELSE yyy.[Mfgr Descr] END AS GLASSESBRAND, DGLASSESBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(qqq.[Mfgr Abbrev], qqq.[Mfgr Descr]) ELSE qqq.[Mfgr Descr] END AS RAINGEARBRAND, DRAINGEARBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(h.[Mfgr Abbrev], h.[Mfgr Descr]) ELSE h.[Mfgr Descr] END AS BAGBRAND, DBAGBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(i.[Mfgr Abbrev], i.[Mfgr Descr]) ELSE i.[Mfgr Descr] END AS SPIKEBRAND, DSPIKEBRAND,
(CASE WHEN (i.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN j.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN j.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN j.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN j.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN j.[Model Lvl3] END) END) AS SPIKEMODEL, DSPIKEMODEL
FROM [Player_Master].[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Code]
LEFT OUTER JOIN [Player_master].PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] e ON GLOVEBRAND = e.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] f ON SHOEBRAND = f.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON HEADGEARBRAND = g.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] zzz ON SHIRTBRAND = zzz.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] abc ON CADDYHEADBRAND = abc.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] yyy ON GLASSESBRAND = yyy.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] qqq ON RAINGEARBRAND = qqq.[Mfgr Code]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] h ON BAGBRAND = h.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] i ON SPIKEBRAND = i.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] j ON SPIKEMODEL = j.[Model Code]
WHERE year([FIRST DAY]) = year(@FIRSTDAY) AND d.PLAYERNAME = @PLAYERLOOKUP
),

SHAFTTABLE AS (
SELECT a.[Survey ID] as SID, [First Day], Pkey,
[Name], [Shaft Club Code],
--needed for the column naming conventions
[Shaft Club Code] AS IRONSHAFTCLUBCODE,  DCLUBCODE AS DIRONSHAFTCLUBCODE,
[Shaft Club Code] AS WOODSHAFTCLUBCODE, DCLUBCODE AS DWOODSHAFTCLUBCODE,
[Shaft Club Code] AS WEDGESHAFTCLUBCODE, DCLUBCODE AS DWEDGESHAFTCLUBCODE,
[Shaft Club Code] AS PUTTERSHAFTCLUBCODE, DCLUBCODE AS DPUTTERSHAFTCLUBCODE,
[Shaft Equip Type],
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS SHAFTMFGR, DMFGRCODE AS DSHAFTMFGRCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS SHAFTBRAND, DBRANDCODE AS DSHAFTBRANDCODE,
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS SHAFTMODEL, DMODELCODE AS DSHAFTMODELCODE,
--
f.[Flex Descr] AS SHAFTFLEX, [DFLEXCODE] AS DSHAFTFLEX,
--
COALESCE(e.[Matl Abbrev], e.[Matl Descr]) AS SHAFTMATL, DMATERIAL AS DSHAFTMATLCODE
FROM Player_master.[Shaft Detail] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.[Shaft Mfgr Code] = b.[Mfgr Code]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.[Shaft Brand Code] = c.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.[Shaft Model Code] = d.[Model Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.[Shaft Mat'l Code] = e.[Matl Code]
--
LEFT OUTER JOIN LKP.[Flex Codes and Desc] f on a.[Shaft Flex Code] = f.[Flex Descr]
--
WHERE year([FIRST DAY]) = year(@FIRSTDAY) AND Name = @PLAYERLOOKUP),

GRIPTABLE AS (
SELECT a.[Survey ID] as SID, [First Day], Pkey,
[Name], [Grip Club Code],
[Grip Club Code] AS IRONGRIPCLUBCODE, DCLUBCODE AS DIRONGRIPCLUBCODE,
[Grip Club Code] AS WOODGRIPCLUBCODE, DCLUBCODE AS DWOODGRIPCLUBCODE,
[Grip Club Code] AS WEDGEGRIPCLUBCODE, DCLUBCODE AS DWEDGEGRIPCLUBCODE,
[Grip Club Code] AS PUTTERGRIPCLUBCODE, DCLUBCODE AS DPUTTERGRIPCLUBCODE,
[Grip Equip Type],
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS GRIPMFGR, DMFGRCODE AS DGRIPMFGRCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS GRIPBRAND, DBRANDCODE AS DGRIPBRANDCODE,
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS GRIPMODEL, DMODELCODE AS DGRIPMODELCODE,
COALESCE(e.[Matl Abbrev], e.[Matl Descr]) AS GRIPMATL, DMATERIAL AS DGRIPMATLCODE
FROM Player_master.[Grip Detail] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.[Grip Mfgr Code] = b.[Mfgr Code]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.[Grip Brand Code] = c.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.[Grip Model Code] = d.[Model Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.[Grip Mat'l Code] = e.[Matl Code]
WHERE year([FIRST DAY]) = year(@FIRSTDAY) AND Name = @PLAYERLOOKUP),

IRONSHAFTTABLE AS (
SELECT SID as sidshaft, [First Day] as fdshaft, [Pkey] AS IRONSHAFTNUMBER, Name, IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE,
IRONSHAFTMFGR, DIRONSHAFTMFGR,
IRONSHAFTBRAND, DIRONSHAFTBRAND,
IRONSHAFTMODEL, DIRONSHAFTMODEL,
--
IRONSHAFTFLEX, DIRONSHAFTFLEX,
--
IRONSHAFTMATL, DIRONSHAFTMATERIAL FROM
(SELECT [PKey], SID, [First Day], row_number() OVER(PARTITION BY Name ORDER BY [PKey]) AS SUBIRONSHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE,
SHAFTMFGR AS IRONSHAFTMFGR, DSHAFTMFGRCODE AS DIRONSHAFTMFGR,
SHAFTBRAND AS IRONSHAFTBRAND, DSHAFTBRANDCODE AS DIRONSHAFTBRAND,
SHAFTMODEL AS IRONSHAFTMODEL, DSHAFTMODELCODE AS DIRONSHAFTMODEL,
--
SHAFTFLEX AS IRONSHAFTFLEX, DSHAFTFLEX AS DIRONSHAFTFLEX,
--
SHAFTMATL AS IRONSHAFTMATL, DSHAFTMATLCODE AS DIRONSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'IRON') subironshaft
),

IRONGRIPTABLE AS (
SELECT SID as sidgrip, [First Day] as fdgrip, Pkey AS IRONGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name] AS IRONGRIPNAME,
IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE,
GRIPMFGR AS IRONGRIPMFGR, DGRIPMFGRCODE AS DIRONGRIPMFGR,
GRIPBRAND AS IRONGRIPBRAND, DGRIPBRANDCODE AS DIRONGRIPBRAND,
GRIPMODEL AS IRONGRIPMODEL, DGRIPMODELCODE AS DIRONGRIPMODEL,
GRIPMATL AS IRONGRIPMATL, DGRIPMATLCODE AS DIRONGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'IRON'
),

SUBIRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.Name, I.SID ORDER BY I.[first day], [PKey] ASC) AS IRONNUMBER,
coalesce(I.SID, BALLTABLE.SID) as SID, COALESCE(I.[FIRST DAY], BALLTABLE.[FIRST DAY]) as [FIRST DAY], COALESCE(BALLTABLE.PLAYERNAME, I.Name) AS PLAYERNAME, COALESCE(BALLTABLE.CATEGORY, I.CATEGORY) AS CATEGORY, COALESCE(BALLTABLE.EXTRA, I.EXTRA) AS EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SHIRTBRAND, DSHIRTBRAND,GLASSESBRAND, DGLASSESBRAND,RAINGEARBRAND, DRAINGEARBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, IRONTYPE, DTYPECODE, [PKey]
FROM BALLTABLE
RIGHT OUTER JOIN
(SELECT
row_number() OVER(PARTITION BY Name, SID ORDER BY [first day] asc, [PKey] ASC) AS SUBIRONNUMBER, * FROM
--irons

( SELECT SID, [First Day],
Name, CATEGORY, EXTRA, [Iron Club Code] AS IRONCLUBCODE, DCLUBCODE,  
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS IRONBRAND, DBRANDCODE, 

(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS IRONMODEL, DMODELCODE, NULL AS IRONTYPE, NULL AS DTYPECODE, c.[PKey]
FROM [Player_Master].[Iron Detail] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d ON c.[Survey ID] = d.SID and c.Name = d.PLAYERNAME and c.[First Day] = d.FIRSTDAY 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Iron Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Iron Model Code] = b.[Model Code]
WHERE year([FIRST DAY]) = year(@FIRSTDAY) AND Name = @PLAYERLOOKUP
)subtable) AS I
ON BALLTABLE.PLAYERNAME = I.name
and BALLTABLE.BALLNUMBER = SUBIRONNUMBER
and balltable.SID = I.SID
),


IRONTABLE AS (
SELECT * FROM SUBIRONTABLE a
LEFT OUTER JOIN
IRONSHAFTTABLE b ON a.IRONNUMBER = b.IRONSHAFTNUMBER AND a.PLAYERNAME = b.Name and a.SID = b.sidshaft
LEFT OUTER JOIN
IRONGRIPTABLE c ON a.IRONNUMBER = c.IRONGRIPNUMBER AND a.PLAYERNAME = c.IRONGRIPNAME and a.SID = c.sidgrip
--IRONGRIPTABLE c ON b.IRONSHAFTNUMBER = c.IRONGRIPNUMBER AND a.PLAYERNAME = c.IRONGRIPNAME
--where RIGHT(IRONCLUBCODE, 1) = (CASE WHEN @IRONVAR = 1 THEN '^' ELSE RIGHT(IRONCLUBCODE, 1) END)
where IRONCLUBCODE like CASE WHEN @IRONVAR = 1 THEN '%^%' ELSE IRONCLUBCODE END
),



WOODSHAFTTABLE AS (
SELECT SID as sidshaft, [First Day] as fdshaft, [Pkey] AS WOODSHAFTNUMBER, Name, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE,
WOODSHAFTMFGR, DWOODSHAFTMFGR,
WOODSHAFTBRAND, DWOODSHAFTBRAND,
WOODSHAFTMODEL, DWOODSHAFTMODEL,
--
WOODSHAFTFLEX, DWOODSHAFTFLEX,
--
WOODSHAFTMATL, DWOODSHAFTMATERIAL FROM
(SELECT SID, [First Day], [PKey], row_number() OVER(PARTITION BY Name ORDER BY [PKey]) AS SUBWOODSHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE,
SHAFTMFGR AS WOODSHAFTMFGR, DSHAFTMFGRCODE AS DWOODSHAFTMFGR,
SHAFTBRAND AS WOODSHAFTBRAND, DSHAFTBRANDCODE AS DWOODSHAFTBRAND,
SHAFTMODEL AS WOODSHAFTMODEL, DSHAFTMODELCODE AS DWOODSHAFTMODEL,
--
SHAFTFLEX AS WOODSHAFTFLEX, DSHAFTFLEX AS DWOODSHAFTFLEX,
--
SHAFTMATL AS WOODSHAFTMATL, DSHAFTMATLCODE AS DWOODSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WOOD') subwoodshaft
),

WOODGRIPTABLE AS (
SELECT SID AS sidgrip, [First Day] as sidfd, Pkey AS WOODGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name] AS WOODGRIPNAME,
WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE,
GRIPMFGR AS WOODGRIPMFGR, DGRIPMFGRCODE AS DWOODGRIPMFGR,
GRIPBRAND AS WOODGRIPBRAND, DGRIPBRANDCODE AS DWOODGRIPBRAND,
GRIPMODEL AS WOODGRIPMODEL, DGRIPMODELCODE AS DWOODGRIPMODEL,
GRIPMATL AS WOODGRIPMATL, DGRIPMATLCODE AS DWOODGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WOOD'
),

SUBWOODTABLE AS (
SELECT W.SID, W.[FIRST DAY],
row_number() OVER(PARTITION BY PLAYERNAME, W.SID ORDER BY W.[first day], [PKey]) AS WOODNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, ISDRIVER, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
	( SELECT ww.[Survey ID] as SID, ww.[First Day],
name, [Wood Club Code] AS WOODCLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WOODBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WOODMODEL, DMODELCODE,
c.[Size Descr] AS WOODSIZE, DSIZECODE,
COALESCE(d.[Matl Abbrev], d.[Matl Descr]) AS WOODMATL, DMATERIAL,
[PKey], ISDRIVER
FROM [Player_Master].[Wood Detail] ww
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wood Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wood Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Wood Size Code] = [Size Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON [Wood Mat'l Code] = [Matl Code]
WHERE year([FIRST DAY]) = year(@FIRSTDAY) AND Name = @PLAYERLOOKUP
) W
ON BALLTABLE.PLAYERNAME = W.name and BALLTABLE.SID = W.SID
),

WOODTABLE AS (
SELECT * FROM SUBWOODTABLE a
LEFT OUTER JOIN
WOODSHAFTTABLE b ON a.WOODNUMBER = b.WOODSHAFTNUMBER AND a.PLAYERNAME = b.Name and a.SID = b.sidshaft
LEFT OUTER JOIN
WOODGRIPTABLE c ON b.WOODSHAFTNUMBER = c.WOODGRIPNUMBER AND a.PLAYERNAME = c.WOODGRIPNAME and a.SID = c.sidfd 
WHERE
 -- drivers
COALESCE(ISDRIVER, 0) = CASE WHEN @WOODVAR = 1 THEN 1 ELSE COALESCE(ISDRIVER, 0) END
 -- hybrids
AND WOODCLUBCODE = CASE WHEN @WOODVAR = 2 THEN 'HYB' ELSE WOODCLUBCODE END
 -- fairways w/ hybrids
AND ISDRIVER <> CASE WHEN @WOODVAR = 3 THEN 1 ELSE 4 END
 -- fairways w/o hybrids
AND (ISDRIVER <> CASE WHEN @WOODVAR = 4 THEN 1 ELSE 4 END
     AND WOODCLUBCODE <> CASE WHEN @WOODVAR = 4 THEN 'HYB' ELSE 'X' END)
-- woods w/o hybrids
AND WOODCLUBCODE <> CASE WHEN @WOODVAR = 5 THEN 'HYB' ELSE 'X' END
),


PUTTERTABLE AS (
SELECT W.SID, W.[FIRST DAY],
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME, W.SID ORDER BY W.[first day], [PKey]) AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE
FROM BALLTABLE
INNER JOIN
( SELECT [Survey ID] as SID, [First Day],
name, [Putter Sequence No] AS PUTTERCLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS PUTTERBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS PUTTERMODEL, DMODELCODE,
c.[Size Descr] AS PUTTERSIZE, DSIZECODE,
[PKey]
FROM [Player_Master].[Putter Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Putter Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Putter Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Putter Size Code] = [Size Code]
WHERE year([FIRST DAY]) = year(@FIRSTDAY) AND Name = @PLAYERLOOKUP
) W
ON BALLTABLE.PLAYERNAME = W.name and BALLTABLE.SID = W.SID
),

WEDGETABLE AS (
SELECT X.SID, x.[first day],
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME, X.SID ORDER BY X.[first day], [PKey]) AS WEDGENUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WEDGECLUBCODE, DCLUBCODE, WEDGEBRAND, DBRANDCODE, WEDGEMODEL, DMODELCODE, WEDGETYPE, DTYPECODE
FROM BALLTABLE
INNER JOIN
( SELECT [Survey ID] as SID, [First Day],
name, [Wedge Club Code] AS WEDGECLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WEDGEBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WEDGEMODEL, DMODELCODE,
c.[Type Descr] AS WEDGETYPE, DTYPECODE,
[PKey]
FROM [Player_Master].[Wedge Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wedge Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wedge Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Type Codes and Description] c ON [Wedge Type Code] = [Type Code]
WHERE year([FIRST DAY]) = year(@FIRSTDAY) AND Name = @PLAYERLOOKUP 
) X
ON BALLTABLE.PLAYERNAME = X.name and BALLTABLE.SID = X.SID
)


SELECT 
pmtt.[TOURNAMENT NAME] + ' / ' + CAST(year(COALESCE(IRONTABLE.[FIRST DAY], woodwedge.[FIRST DAY])) as varchar(10)) + '-' + CAST(month(COALESCE(IRONTABLE.[FIRST DAY], woodwedge.[FIRST DAY])) as varchar(10)) + '-' + CAST(day(COALESCE(IRONTABLE.[FIRST DAY], woodwedge.[FIRST DAY])) as varchar(10)) as TOURNAMENT
, COALESCE(IRONTABLE.SID, woodwedge.sid) as SID, COALESCE(IRONTABLE.[FIRST DAY], woodwedge.[FIRST DAY]) as [FIRST DAY],
COALESCE(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME) AS PLAYERNAME, 
COALESCE(IRONTABLE.CATEGORY, woodwedge.CATEGORY) AS CATEGORY, 
COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE, IRONTABLE.IRONTYPE AS IRONSIZE, IRONTABLE.DTYPECODE AS DIRONSIZECODE,
IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTFLEX, DIRONSHAFTFLEX, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
--IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE, WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE, PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
WEDGECLUBCODE, DWEDGECLUBCODE, WEDGEBRAND, DWEDGEBRANDCODE, WEDGEMODEL, DWEDGEMODELCODE, WEDGETYPE, DWEDGETYPE,
WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTFLEX, DWEDGESHAFTFLEX, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
--WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
WOODCLUBCODE, DWOODCLUBCODE, WOODBRAND, DWOODBRANDCODE, WOODMODEL, DWOODMODELCODE, WOODSIZE, DWOODSIZECODE, WOODMATL, DMATERIAL,
WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTFLEX, DWOODSHAFTFLEX, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
--WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND AS SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SHIRTBRAND, DSHIRTBRAND,GLASSESBRAND, DGLASSESBRAND,RAINGEARBRAND, DRAINGEARBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL,
ROW_NUMBER () OVER(partition by COALESCE(IRONTABLE.SID, woodwedge.sid) Order By COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA, ''), 
Coalesce(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME), 
Coalesce(IRONNUMBER, WEDGEWOODNUMBER)

) AS ROW_ORDER



FROM IRONTABLE --BALLTABLE

--LEFT OUTER JOIN IRONTABLE ON BALLTABLE.PLAYERNAME = IRONTABLE.PLAYERNAME AND BALLTABLE.BALLNUMBER = IRONTABLE.IRONNUMBER

FULL OUTER JOIN

(SELECT COALESCE(WOODTABLE.SID, WEDGETABLE.SID) as SID, COALESCE(WOODTABLE.[FIRST DAY], WEDGETABLE.[FIRST DAY]) as [FIRST DAY], COALESCE(WOODTABLE.PLAYERNAME, WEDGETABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(WOODTABLE.CATEGORY, WEDGETABLE.CATEGORY) AS CATEGORY, COALESCE(WOODTABLE.EXTRA, WEDGETABLE.EXTRA) AS EXTRA,
WEDGECLUBCODE, WEDGETABLE.DCLUBCODE AS DWEDGECLUBCODE, WEDGEBRAND, WEDGETABLE.DBRANDCODE AS DWEDGEBRANDCODE, WEDGEMODEL, WEDGETABLE.DMODELCODE AS DWEDGEMODELCODE, WEDGETYPE, WEDGETABLE.DTYPECODE AS DWEDGETYPE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE AS DWOODSIZECODE, WOODMATL, DMATERIAL,
WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WOODSHAFTMFGR, DWOODSHAFTMFGR,WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTFLEX, DWOODSHAFTFLEX, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
--WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WOODSHAFTMFGR, DWOODSHAFTMFGR,WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
COALESCE(WEDGENUMBER, WOODNUMBER) AS WEDGEWOODNUMBER FROM WOODTABLE
FULL OUTER JOIN
WEDGETABLE ON WOODTABLE.PLAYERNAME = WEDGETABLE.PLAYERNAME AND WEDGENUMBER = WOODNUMBER and woodtable.sid = wedgetable.SID ) woodwedge
ON IRONTABLE.PLAYERNAME = woodwedge.PLAYERNAME AND IRONNUMBER = WEDGEWOODNUMBER and irontable.SID = woodwedge.sid

FULL OUTER JOIN 
PUTTERTABLE ON PUTTERTABLE.PLAYERNAME  = woodwedge.PLAYERNAME AND PUTTERNUMBER = WEDGEWOODNUMBER and woodwedge.SID = PUTTERTABLE.SID

LEFT OUTER JOIN
(SELECT SID, [FIRST DAY], [Pkey] AS WEDGESHAFTNUMBER,   --SELECT ROW_NUMBER () OVER(Order by Pkey, [Name]) AS WEDGESHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
SHAFTMFGR AS WEDGESHAFTMFGR, DSHAFTMFGRCODE AS DWEDGESHAFTMFGR,
SHAFTBRAND AS WEDGESHAFTBRAND, DSHAFTBRANDCODE AS DWEDGESHAFTBRAND,
SHAFTMODEL AS WEDGESHAFTMODEL, DSHAFTMODELCODE AS DWEDGESHAFTMODEL,
--
SHAFTFLEX AS WEDGESHAFTFLEX, DSHAFTFLEX AS DWEDGESHAFTFLEX,
--
SHAFTMATL AS WEDGESHAFTMATL, DSHAFTMATLCODE AS DWEDGESHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WEDG') wedgeshaft ON WEDGEWOODNUMBER = WEDGESHAFTNUMBER AND wedgeshaft.Name = woodwedge.PLAYERNAME and wedgeshaft.SID = woodwedge.SID

LEFT OUTER JOIN
(SELECT SID, [FIRST DAY], Pkey AS WEDGEGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE,
GRIPMFGR AS WEDGEGRIPMFGR, DGRIPMFGRCODE AS DWEDGEGRIPMFGR,
GRIPBRAND AS WEDGEGRIPBRAND, DGRIPBRANDCODE AS DWEDGEGRIPBRAND,
GRIPMODEL AS WEDGEGRIPMODEL, DGRIPMODELCODE AS DWEDGEGRIPMODEL,
GRIPMATL AS WEDGEGRIPMATL, DGRIPMATLCODE AS DWEDGEGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WEDG') wedgegrip ON WEDGEWOODNUMBER = WEDGEGRIPNUMBER AND wedgegrip.Name = woodwedge.PLAYERNAME AND wedgegrip.SID = woodwedge.SID

LEFT OUTER JOIN
(SELECT SID, [FIRST DAY], Pkey AS PUTTERGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
GRIPMFGR AS PUTTERGRIPMFGR, DGRIPMFGRCODE AS DPUTTERGRIPMFGR,
GRIPBRAND AS PUTTERGRIPBRAND, DGRIPBRANDCODE AS DPUTTERGRIPBRAND,
GRIPMODEL AS PUTTERGRIPMODEL, DGRIPMODELCODE AS DPUTTERGRIPMODEL,
GRIPMATL AS PUTTERGRIPMATL, DGRIPMATLCODE AS DPUTTERGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'PUTT') puttergrip ON PUTTERNUMBER = PUTTERGRIPNUMBER AND puttergrip.Name = PUTTERTABLE.PLAYERNAME AND puttergrip.SID = PUTTERTABLE.SID

LEFT OUTER JOIN
player_master.TOURNAMENTS_TABLE pmtt on COALESCE(IRONTABLE.SID, woodwedge.sid) = pmtt.SID and YEAR(pmtt.[FIRST DAY]) = YEAR(@FIRSTDAY) and ISFLASH = 0 and [TYPE] = @TOUR

)
GO
