IF OBJECT_ID('Flash.all_equipment_func') IS NOT NULL
    DROP FUNCTION [Flash].[all_equipment_func];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [Flash].[all_equipment_func] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(

with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, a.[Mfgr Code] AS BALLBRAND, DBALLBRAND, b.[Model Code] AS BALLMODEL, DBALLMODEL,
e.[Mfgr Code] AS GLOVEBRAND, DGLOVEBRAND, f.[Mfgr Code] AS SHOEBRAND, DSHOEBRAND, g.[Mfgr Code] AS HATBRAND, DHEADGEARBRAND,
h.[Mfgr Code] AS BAGBRAND, DBAGBRAND 
FROM [Input].[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Descr]
LEFT OUTER JOIN [Player_master].PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] e ON GLOVEBRAND = e.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] f ON SHOEBRAND = f.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON HEADGEARBRAND = g.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] h ON BAGBRAND = h.[Mfgr Descr] 
WHERE [FIRST DAY] = @FIRSTDAY AND d.SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.Name ORDER BY [PKey] ASC) AS IRONNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.Name) AS PLAYERNAME, COALESCE(BALLTABLE.CATEGORY, I.CATEGORY) AS CATEGORY, COALESCE(BALLTABLE.EXTRA, I.EXTRA) AS EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, IRONTYPE, DTYPECODE, [PKey]
FROM BALLTABLE
RIGHT OUTER JOIN
(SELECT
row_number() OVER(PARTITION BY Name ORDER BY [PKey] ASC) AS SUBIRONNUMBER, * FROM
--irons
( SELECT
Name, CATEGORY, EXTRA, [Iron Club Code] AS IRONCLUBCODE, DCLUBCODE, a.[Mfgr Descr] AS IRONBRAND, DBRANDCODE, b.[Model Descr] AS IRONMODEL, DMODELCODE, NULL AS IRONTYPE, NULL AS DTYPECODE, c.[PKey]
FROM [Player_Master].[Iron Detail] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d ON c.[Survey ID] = d.SID and c.Name = d.PLAYERNAME and c.[First Day] = d.FIRSTDAY 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Iron Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Iron Model Code] = b.[Model Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
GROUP BY Name, CATEGORY, EXTRA, [Iron Club Code], a.[Mfgr Descr], b.[Model Descr], c.[PKey], DCLUBCODE, DBRANDCODE, DMODELCODE
UNION ALL
--wedges
SELECT name, CATEGORY, EXTRA, [Wedge Club Code] AS IRONCLUBCODE, DCLUBCODE, a.[Mfgr Descr] AS IRONBRAND, DBRANDCODE, b.[Model Descr] AS IRONMODEL, DMODELCODE, t.[Type Descr] AS IRONTYPE, DTYPECODE, c.[PKey] + 10
FROM [Player_Master].[Wedge Detail] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d on c.[First Day] = d.FIRSTDAY and c.[Survey ID] = d.SID and c.Name = d.PLAYERNAME 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wedge Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wedge Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Type Codes and Description] t ON [Wedge Type Code] = t.[type code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
GROUP BY Name, CATEGORY, EXTRA, [Wedge Club Code], a.[Mfgr Descr], b.[Model Descr], c.[PKey], DCLUBCODE, DBRANDCODE, DMODELCODE, t.[Type Descr], DTYPECODE
)subtable) AS I
ON BALLTABLE.PLAYERNAME = I.name
and BALLTABLE.BALLNUMBER = SUBIRONNUMBER 
),

WOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS WOODNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME, CLUBCODE AS WOODCLUBCODE, DCLUBCODE,
a.[Mfgr Code] AS WOODBRAND, DBRANDCODE,
b.[Model Code] AS WOODMODEL, DMODELCODE, 
c.[Size Code] AS WOODSIZE, DSIZECODE,
d.[Matl Code] AS WOODMATL, DMATERIAL,
[PKey]
FROM [Input].[Wood]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON MATERIAL = [Matl Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.PLAYERNAME
),

PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME, CLUBCODE AS PUTTERCLUBCODE, DSEQUENCENO,
a.[Mfgr Code] AS PUTTERBRAND, DBRANDCODE,
b.[Model Code] AS PUTTERMODEL, DMODELCODE, 
c.[Size Code] AS PUTTERSIZE, DSIZECODE,
[PKey]
FROM [Input].[Putter]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONTABLE.PLAYERNAME, WOODTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, WOODTABLE.CATEGORY) AS CATEGORY, COALESCE(IRONTABLE.EXTRA, WOODTABLE.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE, IRONTABLE.IRONTYPE, DTYPECODE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE AS DWOODSIZECODE, WOODMATL, DMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND AS SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND

FROM IRONTABLE
FULL OUTER JOIN
WOODTABLE ON IRONTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND IRONNUMBER = WOODNUMBER
FULL OUTER JOIN 
PUTTERTABLE ON IRONTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND PUTTERNUMBER = IRONNUMBER


)
GO
