IF OBJECT_ID('Flash.base_reportzzz') IS NOT NULL
    DROP FUNCTION [Flash].[base_reportzzz];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [Flash].[base_report] 
(	
	@FIRSTDAY date,
	@SID int, 
	@GROUP_ID int,
	@VIEW_LEVEL int,
	@IS_ABBREV int = 0,
	@WOODVAR int,
	@IRONVAR int
)
RETURNS TABLE 
AS
RETURN 
(

/*  @WOODVAR
1 - drivers
2 - hybrids
3 - fairway w/ hyb
4 - fairway w/o hyb
other - all

@IRONVAR
1 - utility
other - all
*/




with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS BALLBRAND, DBALLBRAND,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS BALLMODEL, DBALLMODEL,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(e.[Mfgr Abbrev], e.[Mfgr Descr]) ELSE e.[Mfgr Descr] END AS GLOVEBRAND, DGLOVEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(f.[Mfgr Abbrev], f.[Mfgr Descr]) ELSE f.[Mfgr Descr] END AS SHOEBRAND, DSHOEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(g.[Mfgr Abbrev], g.[Mfgr Descr]) ELSE g.[Mfgr Descr] END AS HATBRAND, DHEADGEARBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(zzz.[Mfgr Abbrev], zzz.[Mfgr Descr]) ELSE zzz.[Mfgr Descr] END AS SHIRTBRAND, DSHIRTBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(h.[Mfgr Abbrev], h.[Mfgr Descr]) ELSE h.[Mfgr Descr] END AS BAGBRAND, DBAGBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(i.[Mfgr Abbrev], i.[Mfgr Descr]) ELSE i.[Mfgr Descr] END AS SPIKEBRAND, DSPIKEBRAND,
(CASE WHEN (i.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN j.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN j.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN j.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN j.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN j.[Model Lvl3] END) END) AS SPIKEMODEL, DSPIKEMODEL
FROM Input.[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Descr]
LEFT OUTER JOIN [Player_master].PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] e ON GLOVEBRAND = e.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] f ON SHOEBRAND = f.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON HEADGEARBRAND = g.[Mfgr Descr]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] zzz ON SHIRTBRAND = zzz.[Mfgr Descr]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] h ON BAGBRAND = h.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] i ON SPIKEBRAND = i.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] j ON SPIKEMODEL = j.[Model Descr]
WHERE [FIRST DAY] = @FIRSTDAY AND d.SID = @SID
),

SHAFTTABLE AS (
SELECT Pkey,
[PLAYERNAME] AS [Name], SHAFTCLUBCODE AS [Shaft Club Code],
--needed for the column naming conventions
SHAFTCLUBCODE AS IRONSHAFTCLUBCODE,  DCLUBCODE AS DIRONSHAFTCLUBCODE,
SHAFTCLUBCODE AS WOODSHAFTCLUBCODE, DCLUBCODE AS DWOODSHAFTCLUBCODE,
SHAFTCLUBCODE AS WEDGESHAFTCLUBCODE, DCLUBCODE AS DWEDGESHAFTCLUBCODE,
SHAFTCLUBCODE AS PUTTERSHAFTCLUBCODE, DCLUBCODE AS DPUTTERSHAFTCLUBCODE,
SHAFTEQUIPTYPE AS [Shaft Equip Type],
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS SHAFTMFGR, DMFGRCODE AS DSHAFTMFGRCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS SHAFTBRAND, DBRANDCODE AS DSHAFTBRANDCODE,
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS SHAFTMODEL, DMODELCODE AS DSHAFTMODELCODE,
f.[Flex Descr] AS SHAFTFLEX, DSHAFTFLEX AS DSHAFTFLEX,
COALESCE(e.[Matl Abbrev], e.[Matl Descr]) AS SHAFTMATL, DMATLCODE AS DSHAFTMATLCODE
FROM Input.[Shaft] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.[SHAFTMFGR] = b.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.[SHAFTBRAND] = c.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.[SHAFTMODEL] = d.[Model Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.[SHAFTMATL] = e.[Matl Descr]
LEFT OUTER JOIN LKP.[Flex Codes and Desc] f on a.[SHAFTFLEX] = f.[Flex Descr]
WHERE [First Day] = @FIRSTDAY AND [SID] = @SID),

GRIPTABLE AS (
SELECT Pkey,
PLAYERNAME AS [Name], GRIPCLUBCODE AS [Grip Club Code],
GRIPCLUBCODE AS IRONGRIPCLUBCODE, DCLUBCODE AS DIRONGRIPCLUBCODE,
GRIPCLUBCODE AS WOODGRIPCLUBCODE, DCLUBCODE AS DWOODGRIPCLUBCODE,
GRIPCLUBCODE AS WEDGEGRIPCLUBCODE, DCLUBCODE AS DWEDGEGRIPCLUBCODE,
GRIPCLUBCODE AS PUTTERGRIPCLUBCODE, DCLUBCODE AS DPUTTERGRIPCLUBCODE,
GRIPEQUIPTYPE AS [Grip Equip Type],
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS GRIPMFGR, DMFGRCODE AS DGRIPMFGRCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS GRIPBRAND, DBRANDCODE AS DGRIPBRANDCODE,
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS GRIPMODEL, DMODELCODE AS DGRIPMODELCODE,
COALESCE(e.[Matl Abbrev], e.[Matl Descr]) AS GRIPMATL, DMATERIAL AS DGRIPMATLCODE
FROM Input.[Grip] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.GRIPMFGR = b.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.GRIPBRAND = c.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.GRIPMODEL = d.[Model Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.GRIPMATL = e.[Matl Descr]
WHERE [First Day] = @FIRSTDAY AND [SID] = @SID),

IRONSHAFTTABLE AS (
SELECT [Pkey] AS IRONSHAFTNUMBER, Name, IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE,
IRONSHAFTMFGR, DIRONSHAFTMFGR,
IRONSHAFTBRAND, DIRONSHAFTBRAND,
IRONSHAFTMODEL, DIRONSHAFTMODEL,
IRONSHAFTFLEX, DIRONSHAFTFLEX,
IRONSHAFTMATL, DIRONSHAFTMATERIAL FROM
(SELECT [PKey], row_number() OVER(PARTITION BY Name ORDER BY [PKey]) AS SUBIRONSHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE,
SHAFTMFGR AS IRONSHAFTMFGR, DSHAFTMFGRCODE AS DIRONSHAFTMFGR,
SHAFTBRAND AS IRONSHAFTBRAND, DSHAFTBRANDCODE AS DIRONSHAFTBRAND,
SHAFTMODEL AS IRONSHAFTMODEL, DSHAFTMODELCODE AS DIRONSHAFTMODEL,
SHAFTFLEX AS IRONSHAFTFLEX, DSHAFTFLEX AS DIRONSHAFTFLEX,
SHAFTMATL AS IRONSHAFTMATL, DSHAFTMATLCODE AS DIRONSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'IRON') subironshaft
),

IRONGRIPTABLE AS (
SELECT Pkey AS IRONGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name] AS IRONGRIPNAME,
IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE,
GRIPMFGR AS IRONGRIPMFGR, DGRIPMFGRCODE AS DIRONGRIPMFGR,
GRIPBRAND AS IRONGRIPBRAND, DGRIPBRANDCODE AS DIRONGRIPBRAND,
GRIPMODEL AS IRONGRIPMODEL, DGRIPMODELCODE AS DIRONGRIPMODEL,
GRIPMATL AS IRONGRIPMATL, DGRIPMATLCODE AS DIRONGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'IRON'
),

SUBIRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.Name ORDER BY [PKey] ASC) AS IRONNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.Name) AS PLAYERNAME, COALESCE(BALLTABLE.CATEGORY, I.CATEGORY) AS CATEGORY, COALESCE(BALLTABLE.EXTRA, I.EXTRA) AS EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SHIRTBRAND, DSHIRTBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, IRONTYPE, DTYPECODE, [PKey]
FROM BALLTABLE
RIGHT OUTER JOIN
(SELECT
row_number() OVER(PARTITION BY Name ORDER BY [PKey] ASC) AS SUBIRONNUMBER, * FROM
--irons
( SELECT
d.PLAYERNAME AS Name, CATEGORY, EXTRA, CLUBCODE AS IRONCLUBCODE, DCLUBCODE, 
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS IRONBRAND, DBRANDCODE, 
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS IRONMODEL, DMODELCODE, NULL AS IRONTYPE, NULL AS DTYPECODE, c.[PKey]
FROM Input.[Iron] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d ON c.[SID] = d.SID and c.PLAYERNAME = d.PLAYERNAME and c.[First Day] = d.FIRSTDAY 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
WHERE [First Day] = @FIRSTDAY AND c.[SID] = @SID 
)subtable) AS I
ON BALLTABLE.PLAYERNAME = I.name
and BALLTABLE.BALLNUMBER = SUBIRONNUMBER 
),


IRONTABLE AS (
SELECT * FROM SUBIRONTABLE a
LEFT OUTER JOIN
IRONSHAFTTABLE b ON a.IRONNUMBER = b.IRONSHAFTNUMBER AND a.PLAYERNAME = b.Name
LEFT OUTER JOIN
IRONGRIPTABLE c ON a.IRONNUMBER = c.IRONGRIPNUMBER AND a.PLAYERNAME = c.IRONGRIPNAME
--IRONGRIPTABLE c ON b.IRONSHAFTNUMBER = c.IRONGRIPNUMBER AND a.PLAYERNAME = c.IRONGRIPNAME
--where RIGHT(IRONCLUBCODE, 1) = (CASE WHEN @IRONVAR = 1 THEN '^' ELSE RIGHT(IRONCLUBCODE, 1) END)
where IRONCLUBCODE like CASE WHEN @IRONVAR = 1 THEN '%^%' ELSE IRONCLUBCODE END
),


WOODSHAFTTABLE AS (
SELECT [Pkey] AS WOODSHAFTNUMBER, Name, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE,
WOODSHAFTMFGR, DWOODSHAFTMFGR,
WOODSHAFTBRAND, DWOODSHAFTBRAND,
WOODSHAFTMODEL, DWOODSHAFTMODEL,
WOODSHAFTFLEX, DWOODSHAFTFLEX,
WOODSHAFTMATL, DWOODSHAFTMATERIAL FROM
(SELECT [PKey], row_number() OVER(PARTITION BY Name ORDER BY [PKey]) AS SUBWOODSHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE,
SHAFTMFGR AS WOODSHAFTMFGR, DSHAFTMFGRCODE AS DWOODSHAFTMFGR,
SHAFTBRAND AS WOODSHAFTBRAND, DSHAFTBRANDCODE AS DWOODSHAFTBRAND,
SHAFTMODEL AS WOODSHAFTMODEL, DSHAFTMODELCODE AS DWOODSHAFTMODEL,
SHAFTFLEX AS WOODSHAFTFLEX, DSHAFTFLEX AS DWOODSHAFTFLEX,
SHAFTMATL AS WOODSHAFTMATL, DSHAFTMATLCODE AS DWOODSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WOOD') subwoodshaft
),

WOODGRIPTABLE AS (
SELECT Pkey AS WOODGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name] AS WOODGRIPNAME,
WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE,
GRIPMFGR AS WOODGRIPMFGR, DGRIPMFGRCODE AS DWOODGRIPMFGR,
GRIPBRAND AS WOODGRIPBRAND, DGRIPBRANDCODE AS DWOODGRIPBRAND,
GRIPMODEL AS WOODGRIPMODEL, DGRIPMODELCODE AS DWOODGRIPMODEL,
GRIPMATL AS WOODGRIPMATL, DGRIPMATLCODE AS DWOODGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WOOD'
),

SUBWOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS WOODNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, ISDRIVER, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME as name, CLUBCODE AS WOODCLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WOODBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WOODMODEL, DMODELCODE,
c.[Size Descr] AS WOODSIZE, DSIZECODE,
COALESCE(d.[Matl Abbrev], d.[Matl Descr]) AS WOODMATL, DMATERIAL,
[PKey], ISDRIVER
FROM Input.[Wood]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON MATERIAL = [Matl Descr]
WHERE [First Day] = @FIRSTDAY AND [SID] = @SID
) W
ON BALLTABLE.PLAYERNAME = W.name
),

WOODTABLE AS (
SELECT * FROM SUBWOODTABLE a
LEFT OUTER JOIN
WOODSHAFTTABLE b ON a.WOODNUMBER = b.WOODSHAFTNUMBER AND a.PLAYERNAME = b.Name
LEFT OUTER JOIN
WOODGRIPTABLE c ON b.WOODSHAFTNUMBER = c.WOODGRIPNUMBER AND a.PLAYERNAME = c.WOODGRIPNAME
WHERE
 -- drivers
COALESCE(ISDRIVER, 0) = CASE WHEN @WOODVAR = 1 THEN 1 ELSE COALESCE(ISDRIVER, 0) END
 -- hybrids
AND WOODCLUBCODE = CASE WHEN @WOODVAR = 2 THEN 'HYB' ELSE WOODCLUBCODE END
 -- fairways w/ hybrids
AND ISDRIVER <> CASE WHEN @WOODVAR = 3 THEN 1 ELSE 4 END
 -- fairways w/o hybrids
AND ISDRIVER <> CASE WHEN @WOODVAR = 4 THEN 1 ELSE 4 END
AND WOODCLUBCODE <> CASE WHEN @WOODVAR = 4 THEN 'HYB' ELSE 'X' END
),


PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME as name, CLUBCODE AS PUTTERCLUBCODE, DSEQUENCENO AS DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS PUTTERBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS PUTTERMODEL, DMODELCODE,
c.[Size Descr] AS PUTTERSIZE, DSIZECODE,
[PKey]
FROM Input.[Putter]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
WHERE [First Day] = @FIRSTDAY AND [SID] = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.name
),

WEDGETABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS WEDGENUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WEDGECLUBCODE, DCLUBCODE, WEDGEBRAND, DBRANDCODE, WEDGEMODEL, DMODELCODE, WEDGETYPE, DTYPECODE
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME as name, CLUBCODE AS WEDGECLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WEDGEBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WEDGEMODEL, DMODELCODE,
c.[TYPE Descr] AS WEDGETYPE, DTYPECODE,
[PKey]
FROM Input.[Wedge]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Type Codes and Description] c ON [Type] = [Type Descr]
WHERE [First Day] = @FIRSTDAY AND [SID] = @SID 
) X
ON BALLTABLE.PLAYERNAME = X.name
)




--select * from BALLTABLE
 

SELECT COALESCE(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, woodwedge.CATEGORY) AS CATEGORY, COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE, IRONTABLE.IRONTYPE AS IRONSIZE, IRONTABLE.DTYPECODE AS DIRONSIZECODE,
IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTFLEX, DIRONSHAFTFLEX, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE, WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE, PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
WEDGECLUBCODE, DWEDGECLUBCODE, WEDGEBRAND, DWEDGEBRANDCODE, WEDGEMODEL, DWEDGEMODELCODE, WEDGETYPE, DWEDGETYPE,
WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTFLEX, DWEDGESHAFTFLEX, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
WOODCLUBCODE, DWOODCLUBCODE, WOODBRAND, DWOODBRANDCODE, WOODMODEL, DWOODMODELCODE, WOODSIZE, DWOODSIZECODE, WOODMATL, DMATERIAL,
WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTFLEX, DWOODSHAFTFLEX, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND AS SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SHIRTBRAND, DSHIRTBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL,
ROW_NUMBER () OVER(Order By COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA, ''), Coalesce(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME), Coalesce(IRONNUMBER, WEDGEWOODNUMBER)) AS ROW_ORDER



FROM IRONTABLE --BALLTABLE

--LEFT OUTER JOIN IRONTABLE ON BALLTABLE.PLAYERNAME = IRONTABLE.PLAYERNAME AND BALLTABLE.BALLNUMBER = IRONTABLE.IRONNUMBER

FULL OUTER JOIN

(SELECT COALESCE(WOODTABLE.PLAYERNAME, WEDGETABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(WOODTABLE.CATEGORY, WEDGETABLE.CATEGORY) AS CATEGORY, COALESCE(WOODTABLE.EXTRA, WEDGETABLE.EXTRA) AS EXTRA,
WEDGECLUBCODE, WEDGETABLE.DCLUBCODE AS DWEDGECLUBCODE, WEDGEBRAND, WEDGETABLE.DBRANDCODE AS DWEDGEBRANDCODE, WEDGEMODEL, WEDGETABLE.DMODELCODE AS DWEDGEMODELCODE, WEDGETYPE, WEDGETABLE.DTYPECODE AS DWEDGETYPE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE AS DWOODSIZECODE, WOODMATL, DMATERIAL,
WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WOODSHAFTMFGR, DWOODSHAFTMFGR,WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTFLEX, DWOODSHAFTFLEX, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
COALESCE(WEDGENUMBER, WOODNUMBER) AS WEDGEWOODNUMBER FROM WOODTABLE
FULL OUTER JOIN
WEDGETABLE ON WOODTABLE.PLAYERNAME = WEDGETABLE.PLAYERNAME AND WEDGENUMBER = WOODNUMBER ) woodwedge
ON IRONTABLE.PLAYERNAME = woodwedge.PLAYERNAME AND IRONNUMBER = WEDGEWOODNUMBER

FULL OUTER JOIN 
PUTTERTABLE ON IRONTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND PUTTERNUMBER = IRONNUMBER

LEFT OUTER JOIN
(SELECT [Pkey] AS WEDGESHAFTNUMBER,   --SELECT ROW_NUMBER () OVER(Order by Pkey, [Name]) AS WEDGESHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
SHAFTMFGR AS WEDGESHAFTMFGR, DSHAFTMFGRCODE AS DWEDGESHAFTMFGR,
SHAFTBRAND AS WEDGESHAFTBRAND, DSHAFTBRANDCODE AS DWEDGESHAFTBRAND,
SHAFTMODEL AS WEDGESHAFTMODEL, DSHAFTMODELCODE AS DWEDGESHAFTMODEL,
SHAFTFLEX AS WEDGESHAFTFLEX, DSHAFTFLEX AS DWEDGESHAFTFLEX,
SHAFTMATL AS WEDGESHAFTMATL, DSHAFTMATLCODE AS DWEDGESHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WEDG') wedgeshaft ON WEDGEWOODNUMBER = WEDGESHAFTNUMBER AND wedgeshaft.Name = woodwedge.PLAYERNAME

LEFT OUTER JOIN
(SELECT Pkey AS WEDGEGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE,
GRIPMFGR AS WEDGEGRIPMFGR, DGRIPMFGRCODE AS DWEDGEGRIPMFGR,
GRIPBRAND AS WEDGEGRIPBRAND, DGRIPBRANDCODE AS DWEDGEGRIPBRAND,
GRIPMODEL AS WEDGEGRIPMODEL, DGRIPMODELCODE AS DWEDGEGRIPMODEL,
GRIPMATL AS WEDGEGRIPMATL, DGRIPMATLCODE AS DWEDGEGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WEDG') wedgegrip ON WEDGEWOODNUMBER = WEDGEGRIPNUMBER AND wedgegrip.Name = woodwedge.PLAYERNAME

LEFT OUTER JOIN
(SELECT Pkey AS PUTTERGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
GRIPMFGR AS PUTTERGRIPMFGR, DGRIPMFGRCODE AS DPUTTERGRIPMFGR,
GRIPBRAND AS PUTTERGRIPBRAND, DGRIPBRANDCODE AS DPUTTERGRIPBRAND,
GRIPMODEL AS PUTTERGRIPMODEL, DGRIPMODELCODE AS DPUTTERGRIPMODEL,
GRIPMATL AS PUTTERGRIPMATL, DGRIPMATLCODE AS DPUTTERGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'PUTT') puttergrip ON PUTTERNUMBER = PUTTERGRIPNUMBER AND puttergrip.Name = PUTTERTABLE.PLAYERNAME





/*
with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS BALLBRAND, DBALLBRAND,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS BALLMODEL, DBALLMODEL,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(e.[Mfgr Abbrev], e.[Mfgr Descr]) ELSE e.[Mfgr Descr] END AS GLOVEBRAND, DGLOVEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(f.[Mfgr Abbrev], f.[Mfgr Descr]) ELSE f.[Mfgr Descr] END AS SHOEBRAND, DSHOEBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(g.[Mfgr Abbrev], g.[Mfgr Descr]) ELSE g.[Mfgr Descr] END AS HATBRAND, DHEADGEARBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(h.[Mfgr Abbrev], h.[Mfgr Descr]) ELSE h.[Mfgr Descr] END AS BAGBRAND, DBAGBRAND,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(i.[Mfgr Abbrev], i.[Mfgr Descr]) ELSE i.[Mfgr Descr] END AS SPIKEBRAND, DSPIKEBRAND,
(CASE WHEN (i.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN j.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN j.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN j.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN j.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN j.[Model Lvl3] END) END) AS SPIKEMODEL, DSPIKEMODEL
FROM [Input].[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Descr]
LEFT OUTER JOIN [Player_master].PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] e ON GLOVEBRAND = e.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] f ON SHOEBRAND = f.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON HEADGEARBRAND = g.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] h ON BAGBRAND = h.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] i ON SPIKEBRAND = i.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] j ON SPIKEMODEL = j.[Model Descr]
WHERE [FIRST DAY] = @FIRSTDAY AND d.SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.Name ORDER BY [PKey] ASC) AS IRONNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.Name) AS PLAYERNAME, COALESCE(BALLTABLE.CATEGORY, I.CATEGORY) AS CATEGORY, COALESCE(BALLTABLE.EXTRA, I.EXTRA) AS EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, IRONTYPE, DTYPECODE, [PKey]
FROM BALLTABLE
RIGHT OUTER JOIN
(SELECT
row_number() OVER(PARTITION BY Name ORDER BY [PKey] ASC) AS SUBIRONNUMBER, * FROM
--irons
( SELECT
c.PLAYERNAME AS Name, CATEGORY, EXTRA, CLUBCODE AS IRONCLUBCODE, DCLUBCODE, a.[Mfgr Descr] AS IRONBRAND, DBRANDCODE, (CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS IRONMODEL, DMODELCODE, NULL AS IRONTYPE, NULL AS DTYPECODE, c.[PKey]
FROM [Input].[Iron] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d ON c.SID = d.SID and c.PLAYERNAME = d.PLAYERNAME and c.[First Day] = d.FIRSTDAY 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
WHERE [First Day] = @FIRSTDAY AND c.SID = @SID 
/*UNION ALL
--wedges
SELECT name, CATEGORY, EXTRA, [Wedge Club Code] AS IRONCLUBCODE, DCLUBCODE, a.[Mfgr Descr] AS IRONBRAND, DBRANDCODE, (CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS IRONMODEL, DMODELCODE, t.[Type Descr] AS IRONTYPE, DTYPECODE, c.[PKey] + 10
FROM [Player_Master].[Wedge Detail] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d on c.[First Day] = d.FIRSTDAY and c.[Survey ID] = d.SID and c.Name = d.PLAYERNAME 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wedge Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wedge Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Type Codes and Description] t ON [Wedge Type Code] = t.[type code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID */
)subtable) AS I
ON BALLTABLE.PLAYERNAME = I.name
and BALLTABLE.BALLNUMBER = SUBIRONNUMBER 
),

WOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS WOODNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, ISDRIVER, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME AS name, CLUBCODE AS WOODCLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WOODBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WOODMODEL, DMODELCODE,
c.[Size Descr] AS WOODSIZE, DSIZECODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(d.[Matl Abbrev], d.[Matl Descr]) ELSE d.[Matl Descr] END AS WOODMATL, DMATERIAL,
[PKey], ISDRIVER
FROM [Input].[Wood]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON MATERIAL = [Matl Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID AND
 -- drivers
COALESCE(ISDRIVER, 0) = CASE WHEN @WOODVAR = 1 THEN 1 ELSE COALESCE(ISDRIVER, 0) END
 -- hybrids
AND CLUBCODE = CASE WHEN @WOODVAR = 2 THEN 'HYB' ELSE CLUBCODE END
 -- fairways w/ hybrids
AND ISDRIVER <> CASE WHEN @WOODVAR = 3 THEN 1 ELSE 4 END
 -- fairways w/o hybrids
AND ISDRIVER <> CASE WHEN @WOODVAR = 4 THEN 1 ELSE 4 END
AND CLUBCODE <> CASE WHEN @WOODVAR = 4 THEN 'HYB' ELSE 'X' END
) W
ON BALLTABLE.PLAYERNAME = W.name
),

PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME AS name, CLUBCODE AS PUTTERCLUBCODE, DSEQUENCENO AS DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS PUTTERBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS PUTTERMODEL, DMODELCODE,
c.[Size Descr] AS PUTTERSIZE, DSIZECODE,
[PKey]
FROM [Input].[Putter]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.name
),

WEDGETABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS WEDGENUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WEDGECLUBCODE, DCLUBCODE, WEDGEBRAND, DBRANDCODE, WEDGEMODEL, DMODELCODE, WEDGETYPE, DTYPECODE
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME AS name, CLUBCODE AS WEDGECLUBCODE, DCLUBCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) ELSE a.[Mfgr Descr] END AS WEDGEBRAND, DBRANDCODE,
(CASE WHEN (a.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN b.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN b.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN b.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN b.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN b.[Model Lvl3] END) END) AS WEDGEMODEL, DMODELCODE,
c.[Type Descr] AS WEDGETYPE, DTYPECODE,
[PKey]
FROM [Input].[Wedge]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Type Codes and Description] c ON TYPE = [Type Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID 
) X
ON BALLTABLE.PLAYERNAME = X.name
),

SHAFTTABLE AS (
SELECT Pkey,
PLAYERNAME AS name,
SHAFTCLUBCODE AS [Shaft Club Code],
--needed for the column naming conventions
SHAFTCLUBCODE AS IRONSHAFTCLUBCODE,  DCLUBCODE AS DIRONSHAFTCLUBCODE,
SHAFTCLUBCODE AS WOODSHAFTCLUBCODE, DCLUBCODE AS DWOODSHAFTCLUBCODE,
SHAFTCLUBCODE AS WEDGESHAFTCLUBCODE, DCLUBCODE AS DWEDGESHAFTCLUBCODE,
SHAFTCLUBCODE AS PUTTERSHAFTCLUBCODE, DCLUBCODE AS DPUTTERSHAFTCLUBCODE,
SHAFTEQUIPTYPE AS [Shaft Equip Type],
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS SHAFTMFGR, DMFGRCODE AS DSHAFTMFGRCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS SHAFTBRAND, DBRANDCODE AS DSHAFTBRANDCODE,
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS SHAFTMODEL, DMODELCODE AS DSHAFTMODELCODE,
e.[Matl Descr] AS SHAFTMATL, DMATLCODE AS DSHAFTMATLCODE
FROM Input.[Shaft] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.SHAFTMFGR = b.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.SHAFTBRAND = c.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.SHAFTMODEL = d.[Model Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.SHAFTMATL = e.[Matl Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID),

GRIPTABLE AS (
SELECT Pkey,
PLAYERNAME AS Name,
GRIPCLUBCODE AS [Grip Club Code],
GRIPCLUBCODE AS IRONGRIPCLUBCODE, DCLUBCODE AS DIRONGRIPCLUBCODE,
GRIPCLUBCODE AS WOODGRIPCLUBCODE, DCLUBCODE AS DWOODGRIPCLUBCODE,
GRIPCLUBCODE AS WEDGEGRIPCLUBCODE, DCLUBCODE AS DWEDGEGRIPCLUBCODE,
GRIPCLUBCODE AS PUTTERGRIPCLUBCODE, DCLUBCODE AS DPUTTERGRIPCLUBCODE,
GRIPEQUIPTYPE AS [Grip Equip Type],
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(b.[Mfgr Abbrev], b.[Mfgr Descr]) ELSE b.[Mfgr Descr] END AS GRIPMFGR, DMFGRCODE AS DGRIPMFGRCODE,
CASE WHEN @IS_ABBREV = 1 THEN COALESCE(c.[Mfgr Abbrev], c.[Mfgr Descr]) ELSE c.[Mfgr Descr] END AS GRIPBRAND, DBRANDCODE AS DGRIPBRANDCODE,
(CASE WHEN (c.[Mfgr Descr] IN (SELECT COMPANY FROM LKP.Company_Groups WHERE GROUP_ID = @GROUP_ID)) THEN d.[Model Descr] ELSE (SELECT CASE WHEN @VIEW_LEVEL = 0 THEN d.[Model Descr] WHEN @VIEW_LEVEL = 1 THEN d.[Model Lvl1] WHEN @VIEW_LEVEL = 2 THEN d.[Model Lvl2] WHEN @VIEW_LEVEL = 3 THEN d.[Model Lvl3] END) END) AS GRIPMODEL, DMODELCODE AS DGRIPMODELCODE,
e.[Matl Descr] AS GRIPMATL, DMATERIAL AS DGRIPMATLCODE
FROM Input.[Grip] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.GRIPMFGR = b.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.GRIPBRAND = c.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.GRIPMODEL = d.[Model Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.GRIPMATL = e.[Matl Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID)


--select * from SHAFTTABLE
 

SELECT COALESCE(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, woodwedge.CATEGORY) AS CATEGORY, COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE, IRONTABLE.IRONTYPE AS IRONSIZE, IRONTABLE.DTYPECODE AS DIRONSIZECODE,
IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE, WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE, WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE, WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE, PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
WEDGECLUBCODE, DWEDGECLUBCODE, WEDGEBRAND, DWEDGEBRANDCODE, WEDGEMODEL, DWEDGEMODELCODE, WEDGETYPE, DWEDGETYPE,
WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
WOODCLUBCODE, DWOODCLUBCODE, WOODBRAND, DWOODBRANDCODE, WOODMODEL, DWOODMODELCODE, WOODSIZE, DWOODSIZECODE, WOODMATL, DMATERIAL,
WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND AS SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND, SPIKEBRAND, DSPIKEBRAND, SPIKEMODEL, DSPIKEMODEL,
ROW_NUMBER () OVER(Order By COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA, ''), Coalesce(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME), Coalesce(IRONNUMBER, WEDGEWOODNUMBER)) AS ROW_ORDER



FROM IRONTABLE --BALLTABLE

--LEFT OUTER JOIN IRONTABLE ON BALLTABLE.PLAYERNAME = IRONTABLE.PLAYERNAME AND BALLTABLE.BALLNUMBER = IRONTABLE.IRONNUMBER

FULL OUTER JOIN

(SELECT COALESCE(WOODTABLE.PLAYERNAME, WEDGETABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(WOODTABLE.CATEGORY, WEDGETABLE.CATEGORY) AS CATEGORY, COALESCE(WOODTABLE.EXTRA, WEDGETABLE.EXTRA) AS EXTRA,
WEDGECLUBCODE, WEDGETABLE.DCLUBCODE AS DWEDGECLUBCODE, WEDGEBRAND, WEDGETABLE.DBRANDCODE AS DWEDGEBRANDCODE, WEDGEMODEL, WEDGETABLE.DMODELCODE AS DWEDGEMODELCODE, WEDGETYPE, WEDGETABLE.DTYPECODE AS DWEDGETYPE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE AS DWOODSIZECODE, WOODMATL, DMATERIAL,
COALESCE(WEDGENUMBER, WOODNUMBER) AS WEDGEWOODNUMBER FROM WOODTABLE
FULL OUTER JOIN
WEDGETABLE ON WOODTABLE.PLAYERNAME = WEDGETABLE.PLAYERNAME AND WEDGENUMBER = WOODNUMBER ) woodwedge
ON IRONTABLE.PLAYERNAME = woodwedge.PLAYERNAME AND IRONNUMBER = WEDGEWOODNUMBER

FULL OUTER JOIN 
PUTTERTABLE ON IRONTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND PUTTERNUMBER = IRONNUMBER

LEFT OUTER JOIN
(SELECT Pkey AS IRONSHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, Name,
IRONSHAFTCLUBCODE, DIRONSHAFTCLUBCODE,
SHAFTMFGR AS IRONSHAFTMFGR, DSHAFTMFGRCODE AS DIRONSHAFTMFGR,
SHAFTBRAND AS IRONSHAFTBRAND, DSHAFTBRANDCODE AS DIRONSHAFTBRAND,
SHAFTMODEL AS IRONSHAFTMODEL, DSHAFTMODELCODE AS DIRONSHAFTMODEL,
SHAFTMATL AS IRONSHAFTMATL, DSHAFTMATLCODE AS DIRONSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'IRON') ironshaft ON IRONNUMBER = IRONSHAFTNUMBER AND ironshaft.Name = IRONTABLE.PLAYERNAME

LEFT OUTER JOIN
(SELECT [Pkey] AS WEDGESHAFTNUMBER,   --SELECT ROW_NUMBER () OVER(Order by Pkey, [Name]) AS WEDGESHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
WEDGESHAFTCLUBCODE, DWEDGESHAFTCLUBCODE,
SHAFTMFGR AS WEDGESHAFTMFGR, DSHAFTMFGRCODE AS DWEDGESHAFTMFGR,
SHAFTBRAND AS WEDGESHAFTBRAND, DSHAFTBRANDCODE AS DWEDGESHAFTBRAND,
SHAFTMODEL AS WEDGESHAFTMODEL, DSHAFTMODELCODE AS DWEDGESHAFTMODEL,
SHAFTMATL AS WEDGESHAFTMATL, DSHAFTMATLCODE AS DWEDGESHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WEDG') wedgeshaft ON WEDGEWOODNUMBER = WEDGESHAFTNUMBER AND wedgeshaft.Name = woodwedge.PLAYERNAME

LEFT OUTER JOIN
( 
SELECT [Pkey] AS WOODSHAFTNUMBER, Name, WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE,
WOODSHAFTMFGR, DWOODSHAFTMFGR,
WOODSHAFTBRAND, DWOODSHAFTBRAND,
WOODSHAFTMODEL, DWOODSHAFTMODEL,
WOODSHAFTMATL, DWOODSHAFTMATERIAL FROM
(SELECT [PKey], row_number() OVER(PARTITION BY Name ORDER BY [PKey]) AS SUBWOODSHAFTNUMBER,
[Shaft Club Code] AS SHAFTCLUBCODE, [Name],
WOODSHAFTCLUBCODE, DWOODSHAFTCLUBCODE,
SHAFTMFGR AS WOODSHAFTMFGR, DSHAFTMFGRCODE AS DWOODSHAFTMFGR,
SHAFTBRAND AS WOODSHAFTBRAND, DSHAFTBRANDCODE AS DWOODSHAFTBRAND,
SHAFTMODEL AS WOODSHAFTMODEL, DSHAFTMODELCODE AS DWOODSHAFTMODEL,
SHAFTMATL AS WOODSHAFTMATL, DSHAFTMATLCODE AS DWOODSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WOOD' ) subwoodshafttable
LEFT OUTER JOIN WOODTABLE b ON subwoodshafttable.Name = b.PLAYERNAME AND subwoodshafttable.SUBWOODSHAFTNUMBER = b.WOODNUMBER 
WHERE
-- drivers
COALESCE(ISDRIVER, 0) = CASE WHEN @WOODVAR = 1 THEN 1 ELSE COALESCE(ISDRIVER, 0) END
 -- hybrids
AND SHAFTCLUBCODE = CASE WHEN @WOODVAR = 2 THEN 'HYB' ELSE SHAFTCLUBCODE END
 -- fairways w/ hybrids
AND COALESCE(ISDRIVER, 0) <> CASE WHEN @WOODVAR = 3 THEN 1 ELSE 4 END
 -- fairways w/o hybrids
AND COALESCE(ISDRIVER, 0) <> CASE WHEN @WOODVAR = 4 THEN 1 ELSE 4 END
AND SHAFTCLUBCODE <> CASE WHEN @WOODVAR = 4 THEN 'HYB' ELSE 'X' END 
) woodshaft ON WEDGEWOODNUMBER = WOODSHAFTNUMBER AND woodshaft.Name = woodwedge.PLAYERNAME

LEFT OUTER JOIN
(SELECT Pkey AS IRONGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
IRONGRIPCLUBCODE, DIRONGRIPCLUBCODE,
GRIPMFGR AS IRONGRIPMFGR, DGRIPMFGRCODE AS DIRONGRIPMFGR,
GRIPBRAND AS IRONGRIPBRAND, DGRIPBRANDCODE AS DIRONGRIPBRAND,
GRIPMODEL AS IRONGRIPMODEL, DGRIPMODELCODE AS DIRONGRIPMODEL,
GRIPMATL AS IRONGRIPMATL, DGRIPMATLCODE AS DIRONGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'IRON') irongrip ON IRONNUMBER = IRONGRIPNUMBER AND irongrip.Name = IRONTABLE.PLAYERNAME

LEFT OUTER JOIN
(SELECT Pkey AS WEDGEGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
WEDGEGRIPCLUBCODE, DWEDGEGRIPCLUBCODE,
GRIPMFGR AS WEDGEGRIPMFGR, DGRIPMFGRCODE AS DWEDGEGRIPMFGR,
GRIPBRAND AS WEDGEGRIPBRAND, DGRIPBRANDCODE AS DWEDGEGRIPBRAND,
GRIPMODEL AS WEDGEGRIPMODEL, DGRIPMODELCODE AS DWEDGEGRIPMODEL,
GRIPMATL AS WEDGEGRIPMATL, DGRIPMATLCODE AS DWEDGEGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WEDG') wedgegrip ON WEDGEWOODNUMBER = WEDGEGRIPNUMBER AND wedgegrip.Name = woodwedge.PLAYERNAME

LEFT OUTER JOIN
(SELECT Pkey AS WOODGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
WOODGRIPCLUBCODE, DWOODGRIPCLUBCODE,
GRIPMFGR AS WOODGRIPMFGR, DGRIPMFGRCODE AS DWOODGRIPMFGR,
GRIPBRAND AS WOODGRIPBRAND, DGRIPBRANDCODE AS DWOODGRIPBRAND,
GRIPMODEL AS WOODGRIPMODEL, DGRIPMODELCODE AS DWOODGRIPMODEL,
GRIPMATL AS WOODGRIPMATL, DGRIPMATLCODE AS DWOODGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WOOD') woodgrip ON WEDGEWOODNUMBER = WOODGRIPNUMBER AND woodgrip.Name = woodwedge.PLAYERNAME

LEFT OUTER JOIN
(SELECT Pkey AS PUTTERGRIPNUMBER,
[Grip Club Code] AS GRIPCLUBCODE, [Name],
PUTTERGRIPCLUBCODE, DPUTTERGRIPCLUBCODE,
GRIPMFGR AS PUTTERGRIPMFGR, DGRIPMFGRCODE AS DPUTTERGRIPMFGR,
GRIPBRAND AS PUTTERGRIPBRAND, DGRIPBRANDCODE AS DPUTTERGRIPBRAND,
GRIPMODEL AS PUTTERGRIPMODEL, DGRIPMODELCODE AS DPUTTERGRIPMODEL,
GRIPMATL AS PUTTERGRIPMATL, DGRIPMATLCODE AS DPUTTERGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'PUTT') puttergrip ON PUTTERNUMBER = PUTTERGRIPNUMBER AND puttergrip.Name = PUTTERTABLE.PLAYERNAME


*/


)



--  select * from [Media].[base_report]('8/4/2011', 648) ORDER BY row_order
GO
