IF OBJECT_ID('Flash.ball_driver_putter_glove_shoes_func') IS NOT NULL
    DROP FUNCTION [Flash].[ball_driver_putter_glove_shoes_func];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [Flash].[ball_driver_putter_glove_shoes_func] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(

with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, a.[Mfgr Code] AS BALLBRAND, DBALLBRAND, b.[Model Code] AS BALLMODEL, DBALLMODEL, e.[Mfgr Code] AS GLOVEBRAND, DGLOVEBRAND,
f.[Mfgr Code] as SHOEBRAND, DSHOEBRAND
FROM Input.[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Descr] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Descr]
LEFT OUTER JOIN Player_Master.PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] e on GLOVEBRAND = e.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] f on SHOEBRAND = f.[Mfgr Descr]
WHERE [FIRST DAY] = @FIRSTDAY AND d.SID = @SID
),


DRIVERTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.PLAYERNAME ORDER BY [PKey] ASC) AS DRIVERNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.PLAYERNAME) AS PLAYERNAME, CATEGORY, EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND, SHOEBRAND, DSHOEBRAND, GLOVEBRAND, DGLOVEBRAND,
WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATERIAL, DMATERIAL, [PKey]
FROM BALLTABLE
INNER JOIN
(SELECT
row_number() OVER(PARTITION BY PLAYERNAME ORDER BY [PKey] ASC) AS SUBDRIVERNUMBER,
PLAYERNAME, CLUBCODE AS WOODCLUBCODE, DCLUBCODE, a.[Mfgr Code] AS WOODBRAND, DBRANDCODE, b.[Model Code] AS WOODMODEL, DMODELCODE,
[Size Code] AS WOODSIZE, DSIZECODE, [Matl Code] AS WOODMATERIAL, DMATERIAL, [PKey]
FROM Input.Wood
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON MATERIAL = [Matl Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID and ISDRIVER = 1) AS I
ON BALLTABLE.PLAYERNAME = I.PLAYERNAME
and BALLTABLE.BALLNUMBER = SUBDRIVERNUMBER 
),

PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERCLUBCODE, DSEQUENCENO, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE, PUTTERMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
PLAYERNAME, CLUBCODE AS PUTTERCLUBCODE, DSEQUENCENO,
a.[Mfgr Code] AS PUTTERBRAND, DBRANDCODE,
b.[Model Code] AS PUTTERMODEL, DMODELCODE, 
c.[Size Descr] AS PUTTERSIZE, DSIZECODE,
d.[Matl Descr] AS PUTTERMATL, DMATERIAL,
[PKey]
FROM Input.Putter
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = [Size Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON MATERIAL = [Matl Descr]
WHERE [First Day] = @FIRSTDAY AND SID = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(DRIVERTABLE.PLAYERNAME, PUTTERTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(DRIVERTABLE.CATEGORY, PUTTERTABLE.CATEGORY) AS CATEGORY, COALESCE(DRIVERTABLE.EXTRA, PUTTERTABLE.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
WOODCLUBCODE, DRIVERTABLE.DCLUBCODE, WOODBRAND, DRIVERTABLE.DBRANDCODE AS DDRIVERBRANDCODE, WOODMODEL, DRIVERTABLE.DMODELCODE AS DDRIVERMODELCODE,
DRIVERTABLE.WOODSIZE, DRIVERTABLE.DSIZECODE AS DDRIVERSIZECODE, DRIVERTABLE.WOODMATERIAL, DRIVERTABLE.DMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND

FROM DRIVERTABLE
FULL OUTER JOIN
PUTTERTABLE ON DRIVERTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND DRIVERNUMBER = PUTTERNUMBER
)
GO
