DROP FUNCTION IF EXISTS [Media].[base_report];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [Media].[base_report] 
(	
	@FIRSTDAY date,
	@SID int
)
RETURNS TABLE 
AS
RETURN 
(


with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, a.[Mfgr Descr] AS BALLBRAND, DBALLBRAND, b.[Model Descr] AS BALLMODEL, DBALLMODEL,
e.[Mfgr Descr] AS GLOVEBRAND, DGLOVEBRAND, f.[Mfgr Descr] AS SHOEBRAND, DSHOEBRAND, g.[Mfgr Descr] AS HATBRAND, DHEADGEARBRAND, h.[Mfgr Descr] AS BAGBRAND, DBAGBRAND 
FROM [Player_Master].[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Code]
LEFT OUTER JOIN [Player_master].PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] e ON GLOVEBRAND = e.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] f ON SHOEBRAND = f.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON HEADGEARBRAND = g.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] h ON BAGBRAND = h.[Mfgr Code] 
WHERE [FIRST DAY] = @FIRSTDAY AND d.SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.Name ORDER BY [PKey] ASC) AS IRONNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.Name) AS PLAYERNAME, COALESCE(BALLTABLE.CATEGORY, I.CATEGORY) AS CATEGORY, COALESCE(BALLTABLE.EXTRA, I.EXTRA) AS EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, [PKey]
FROM BALLTABLE
RIGHT OUTER JOIN
(SELECT
row_number() OVER(PARTITION BY Name ORDER BY [PKey] ASC) AS SUBIRONNUMBER, * FROM
--irons
( SELECT
Name, CATEGORY, EXTRA, [Iron Club Code] AS IRONCLUBCODE, DCLUBCODE, a.[Mfgr Descr] AS IRONBRAND, DBRANDCODE, b.[Model Descr] AS IRONMODEL, DMODELCODE, c.[PKey]
FROM [Player_Master].[Iron Detail] c
LEFT OUTER JOIN Player_Master.PLAYERNAMES d ON c.[Survey ID] = d.SID and c.Name = d.PLAYERNAME and c.[First Day] = d.FIRSTDAY 
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Iron Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Iron Model Code] = b.[Model Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
GROUP BY Name, CATEGORY, EXTRA, [Iron Club Code], a.[Mfgr Descr], b.[Model Descr], c.[PKey], DCLUBCODE, DBRANDCODE, DMODELCODE)
subtable) AS I
ON BALLTABLE.PLAYERNAME = I.name
and BALLTABLE.BALLNUMBER = SUBIRONNUMBER 
),

WOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS WOODNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
name, [Wood Club Code] AS WOODCLUBCODE, DCLUBCODE,
ISNULL(a.[Mfgr Abbrev], a.[Mfgr Descr]) AS WOODBRAND, DBRANDCODE,
b.[Model Descr] AS WOODMODEL, DMODELCODE, 
c.[Size Descr] AS WOODSIZE, DSIZECODE,
ISNULL(d.[Matl Abbrev], d.[Matl Descr]) AS WOODMATL, DMATERIAL,
[PKey]
FROM [Player_Master].[Wood Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wood Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wood Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Wood Size Code] = [Size Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON [Wood Mat'l Code] = [Matl Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.name
),

PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE
FROM BALLTABLE
INNER JOIN
( SELECT
name, [Putter Sequence No] AS PUTTERCLUBCODE, DCLUBCODE,
ISNULL(a.[Mfgr Abbrev], a.[Mfgr Descr]) AS PUTTERBRAND, DBRANDCODE,
b.[Model Descr] AS PUTTERMODEL, DMODELCODE, 
c.[Size Descr] AS PUTTERSIZE, DSIZECODE,
[PKey]
FROM [Player_Master].[Putter Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Putter Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Putter Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Putter Size Code] = [Size Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.name
),

WEDGETABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS WEDGENUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, WEDGECLUBCODE, DCLUBCODE, WEDGEBRAND, DBRANDCODE, WEDGEMODEL, DMODELCODE, WEDGETYPE, DTYPECODE
FROM BALLTABLE
INNER JOIN
( SELECT
name, [Wedge Club Code] AS WEDGECLUBCODE, DCLUBCODE,
ISNULL(a.[Mfgr Abbrev], a.[Mfgr Descr]) AS WEDGEBRAND, DBRANDCODE,
b.[Model Descr] AS WEDGEMODEL, DMODELCODE, 
c.[Type Descr] AS WEDGETYPE, DTYPECODE,
[PKey]
FROM [Player_Master].[Wedge Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wedge Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wedge Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Type Codes and Description] c ON [Wedge Type Code] = [Type Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
) X
ON BALLTABLE.PLAYERNAME = X.name
),

SHAFTTABLE AS (
SELECT Pkey,
[Shaft Club Code],
[Shaft Equip Type],
b.[Mfgr Descr] AS SHAFTMFGR, DMFGRCODE AS DSHAFTMFGRCODE,
c.[Mfgr Descr] AS SHAFTBRAND, DBRANDCODE AS DSHAFTBRANDCODE,
d.[Model Descr] AS SHAFTMODEL, DMODELCODE AS DSHAFTMODELCODE,
e.[Matl Descr] AS SHAFTMATL, DMATERIAL AS DSHAFTMATLCODE
FROM Player_master.[Shaft Detail] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.[Shaft Mfgr Code] = b.[Mfgr Code]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.[Shaft Brand Code] = c.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.[Shaft Model Code] = d.[Model Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.[Shaft Mat'l Code] = e.[Matl Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID),

GRIPTABLE AS (
SELECT Pkey,
[Grip Club Code],
[Grip Equip Type],
b.[Mfgr Descr] AS GRIPMFGR, DMFGRCODE AS DGRIPMFGRCODE,
c.[Mfgr Descr] AS GRIPBRAND, DBRANDCODE AS DGRIPBRANDCODE,
d.[Model Descr] AS GRIPMODEL, DMODELCODE AS DGRIPMODELCODE,
e.[Matl Descr] AS GRIPMATL, DMATERIAL AS DGRIPMATLCODE
FROM Player_master.[Grip Detail] a
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] b ON a.[Grip Mfgr Code] = b.[Mfgr Code]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON a.[Grip Brand Code] = c.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] d ON a.[Grip Model Code] = d.[Model Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] e ON a.[Grip Mat'l Code] = e.[Matl Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID)





SELECT COALESCE(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, woodwedge.CATEGORY) AS CATEGORY, COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
IRONCLUBCODE, IRONTABLE.DCLUBCODE AS DIRONCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE AS DIRONBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE AS DIRONMODELCODE,
IRONSHAFTMFGR, DIRONSHAFTMFGR, IRONSHAFTBRAND, DIRONSHAFTBRAND, IRONSHAFTMODEL, DIRONSHAFTMODEL, IRONSHAFTMATL, DIRONSHAFTMATERIAL,
IRONGRIPMFGR, DIRONGRIPMFGR, IRONGRIPBRAND, DIRONGRIPBRAND, IRONGRIPMODEL, DIRONGRIPMODEL, IRONGRIPMATL, DIRONGRIPMATERIAL,
WEDGECLUBCODE, DWEDGECLUBCODE, WEDGEBRAND, DWEDGEBRANDCODE, WEDGEMODEL, DWEDGEMODELCODE, WEDGETYPE, DWEDGETYPE,
WEDGESHAFTMFGR, DWEDGESHAFTMFGR, WEDGESHAFTBRAND, DWEDGESHAFTBRAND, WEDGESHAFTMODEL, DWEDGESHAFTMODEL, WEDGESHAFTMATL, DWEDGESHAFTMATERIAL,
WEDGEGRIPMFGR, DWEDGEGRIPMFGR, WEDGEGRIPBRAND, DWEDGEGRIPBRAND, WEDGEGRIPMODEL, DWEDGEGRIPMODEL, WEDGEGRIPMATL, DWEDGEGRIPMATERIAL,
WOODCLUBCODE, DWOODCLUBCODE, WOODBRAND, DWOODBRANDCODE, WOODMODEL, DWOODMODELCODE, WOODSIZE, DWOODSIZECODE, WOODMATL, DMATERIAL,
WOODSHAFTMFGR, DWOODSHAFTMFGR, WOODSHAFTBRAND, DWOODSHAFTBRAND, WOODSHAFTMODEL, DWOODSHAFTMODEL, WOODSHAFTMATL, DWOODSHAFTMATERIAL,
WOODGRIPMFGR, DWOODGRIPMFGR, WOODGRIPBRAND, DWOODGRIPBRAND, WOODGRIPMODEL, DWOODGRIPMODEL, WOODGRIPMATL, DWOODGRIPMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE AS DPUTTERBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE AS DPUTTERMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE AS DPUTTERSIZECODE,
PUTTERGRIPMFGR, DPUTTERGRIPMFGR, PUTTERGRIPBRAND, DPUTTERGRIPBRAND, PUTTERGRIPMODEL, DPUTTERGRIPMODEL, PUTTERGRIPMATL, DPUTTERGRIPMATERIAL,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND AS SHOESBRAND, DSHOEBRAND, HATBRAND, DHEADGEARBRAND, BAGBRAND, DBAGBRAND,
ROW_NUMBER () OVER(Order By COALESCE(IRONTABLE.EXTRA, woodwedge.EXTRA, ''), Coalesce(IRONTABLE.PLAYERNAME, woodwedge.PLAYERNAME), Coalesce(IRONNUMBER, WEDGEWOODNUMBER)) AS ROW_ORDER



FROM IRONTABLE
FULL OUTER JOIN

(SELECT COALESCE(WOODTABLE.PLAYERNAME, WEDGETABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(WOODTABLE.CATEGORY, WEDGETABLE.CATEGORY) AS CATEGORY, COALESCE(WOODTABLE.EXTRA, WEDGETABLE.EXTRA) AS EXTRA,
WEDGECLUBCODE, WEDGETABLE.DCLUBCODE AS DWEDGECLUBCODE, WEDGEBRAND, WEDGETABLE.DBRANDCODE AS DWEDGEBRANDCODE, WEDGEMODEL, WEDGETABLE.DMODELCODE AS DWEDGEMODELCODE, WEDGETYPE, WEDGETABLE.DTYPECODE AS DWEDGETYPE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE AS DWOODCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE AS DWOODBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE AS DWOODMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE AS DWOODSIZECODE, WOODMATL, DMATERIAL,
COALESCE(WEDGENUMBER, WOODNUMBER) AS WEDGEWOODNUMBER FROM WOODTABLE
FULL OUTER JOIN
WEDGETABLE ON WOODTABLE.PLAYERNAME = WEDGETABLE.PLAYERNAME AND WEDGENUMBER = WOODNUMBER ) woodwedge
ON IRONTABLE.PLAYERNAME = woodwedge.PLAYERNAME AND IRONNUMBER = WEDGEWOODNUMBER

FULL OUTER JOIN 
PUTTERTABLE ON IRONTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND PUTTERNUMBER = IRONNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS IRONSHAFTNUMBER,
SHAFTMFGR AS IRONSHAFTMFGR, DSHAFTMFGRCODE AS DIRONSHAFTMFGR,
SHAFTBRAND AS IRONSHAFTBRAND, DSHAFTBRANDCODE AS DIRONSHAFTBRAND,
SHAFTMODEL AS IRONSHAFTMODEL, DSHAFTMODELCODE AS DIRONSHAFTMODEL,
SHAFTMATL AS IRONSHAFTMATL, DSHAFTMATLCODE AS DIRONSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'IRON') ironshaft ON IRONNUMBER = IRONSHAFTNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WEDGESHAFTNUMBER,
SHAFTMFGR AS WEDGESHAFTMFGR, DSHAFTMFGRCODE AS DWEDGESHAFTMFGR,
SHAFTBRAND AS WEDGESHAFTBRAND, DSHAFTBRANDCODE AS DWEDGESHAFTBRAND,
SHAFTMODEL AS WEDGESHAFTMODEL, DSHAFTMODELCODE AS DWEDGESHAFTMODEL,
SHAFTMATL AS WEDGESHAFTMATL, DSHAFTMATLCODE AS DWEDGESHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WEDG') wedgeshaft ON WEDGEWOODNUMBER = WEDGESHAFTNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WOODSHAFTNUMBER,
SHAFTMFGR AS WOODSHAFTMFGR, DSHAFTMFGRCODE AS DWOODSHAFTMFGR,
SHAFTBRAND AS WOODSHAFTBRAND, DSHAFTBRANDCODE AS DWOODSHAFTBRAND,
SHAFTMODEL AS WOODSHAFTMODEL, DSHAFTMODELCODE AS DWOODSHAFTMODEL,
SHAFTMATL AS WOODSHAFTMATL, DSHAFTMATLCODE AS DWOODSHAFTMATERIAL
FROM SHAFTTABLE WHERE [Shaft Equip Type] = 'WOOD') woodshaft ON WEDGEWOODNUMBER = WOODSHAFTNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS IRONGRIPNUMBER,
GRIPMFGR AS IRONGRIPMFGR, DGRIPMFGRCODE AS DIRONGRIPMFGR,
GRIPBRAND AS IRONGRIPBRAND, DGRIPBRANDCODE AS DIRONGRIPBRAND,
GRIPMODEL AS IRONGRIPMODEL, DGRIPMODELCODE AS DIRONGRIPMODEL,
GRIPMATL AS IRONGRIPMATL, DGRIPMATLCODE AS DIRONGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'IRON') irongrip ON IRONNUMBER = IRONGRIPNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WEDGEGRIPNUMBER,
GRIPMFGR AS WEDGEGRIPMFGR, DGRIPMFGRCODE AS DWEDGEGRIPMFGR,
GRIPBRAND AS WEDGEGRIPBRAND, DGRIPBRANDCODE AS DWEDGEGRIPBRAND,
GRIPMODEL AS WEDGEGRIPMODEL, DGRIPMODELCODE AS DWEDGEGRIPMODEL,
GRIPMATL AS WEDGEGRIPMATL, DGRIPMATLCODE AS DWEDGEGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WEDG') wedgegrip ON WEDGEWOODNUMBER = WEDGEGRIPNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS WOODGRIPNUMBER,
GRIPMFGR AS WOODGRIPMFGR, DGRIPMFGRCODE AS DWOODGRIPMFGR,
GRIPBRAND AS WOODGRIPBRAND, DGRIPBRANDCODE AS DWOODGRIPBRAND,
GRIPMODEL AS WOODGRIPMODEL, DGRIPMODELCODE AS DWOODGRIPMODEL,
GRIPMATL AS WOODGRIPMATL, DGRIPMATLCODE AS DWOODGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'WOOD') woodgrip ON WEDGEWOODNUMBER = WOODGRIPNUMBER

LEFT OUTER JOIN
(SELECT ROW_NUMBER () OVER(Order by Pkey) AS PUTTERGRIPNUMBER,
GRIPMFGR AS PUTTERGRIPMFGR, DGRIPMFGRCODE AS DPUTTERGRIPMFGR,
GRIPBRAND AS PUTTERGRIPBRAND, DGRIPBRANDCODE AS DPUTTERGRIPBRAND,
GRIPMODEL AS PUTTERGRIPMODEL, DGRIPMODELCODE AS DPUTTERGRIPMODEL,
GRIPMATL AS PUTTERGRIPMATL, DGRIPMATLCODE AS DPUTTERGRIPMATERIAL
FROM GRIPTABLE WHERE [Grip Equip Type] = 'PUTT') puttergrip ON PUTTERNUMBER = PUTTERGRIPNUMBER

)



--  select * from [Media].[base_report]('8/4/2011', 648) ORDER BY row_order
GO
