DROP PROCEDURE IF EXISTS [CR_Looseleaf].[All];
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE [CR_Looseleaf].[All]
	@FIRSTNAME varchar(50),
	@LASTNAME varchar(50),
	@LOOKUPDATE date
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @PLAYERNAME VARCHAR(65);
  IF (@LASTNAME <> '' AND @FIRSTNAME <> '')
  SET @PLAYERNAME = @LASTNAME + ', ' + @FIRSTNAME;
  ELSE
  SET @PLAYERNAME = @FIRSTNAME;

  DECLARE @FIRSTDAY date;
  SET @FIRSTDAY = (SELECT MAX([FIRST DAY]) from [Player_Master].[All] with (nolock)
  where PLAYERNAME = @PLAYERNAME and [FIRST DAY] < @LOOKUPDATE);


SELECT BALLBRAND, BALLMODEL, BALLMATERIAL, BALLMISC, BAGBRAND, GLOVEBRAND, SHOEBRAND,
  SPIKEBRAND, SPIKEMODEL, SHIRTBRAND, HEADGEARBRAND, CADDYHEADBRAND, GLASSESBRAND, RAINGEARBRAND, RAINCOVERBRAND, TOWELBRAND, TRAVELBAGBRAND, RANGEPLAYERBRAND, RANGECADDYBRAND, LAUNCHMONITORBRAND
FROM (

SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS BALLBRAND, COALESCE("Model Abbrev", "Model Descr") AS BALLMODEL, "Matl Descr" AS BALLMATERIAL, "Misc Descr" AS BALLMISC, PLAYERNAME, ADDEDBY
FROM (
SELECT TOP 1 BALLBRAND, BALLMODEL, BALLMATERIAL, BALLMISC, PLAYERNAME, '' AS ADDEDBY
FROM
(Select * from [Player_Master].[All] with (nolock)
where "FIRST DAY" < @LOOKUPDATE) aa
WHERE PLAYERNAME = @PLAYERNAME AND BALLBRAND IS NOT NULL
ORDER BY "FIRST DAY" DESC
) aaa
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON BALLBRAND = "Mfgr Code"
LEFT OUTER JOIN LKP.[Model Codes and Descr] with (nolock) ON BALLMODEL = "Model Code"
LEFT OUTER JOIN LKP.[Material Codes and Descript] with (nolock) ON BALLMATERIAL = "Matl Code"
LEFT OUTER JOIN LKP.[Miscellaneous Codes and Des] with (nolock) ON BALLMISC = "Misc Code"
) a

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS BAGBRAND, PLAYERNAME
FROM (
SELECT TOP 1 BAGBRAND, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE) bb
WHERE PLAYERNAME = @PLAYERNAME AND BAGBRAND IS NOT NULL
ORDER BY "FIRST DAY" DESC
) bbb
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock)
 ON BAGBRAND = "Mfgr Code"
) b ON a.PLAYERNAME = b.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS GLOVEBRAND, PLAYERNAME
FROM (
SELECT TOP 1 GLOVEBRAND, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE) cc
 WHERE PLAYERNAME = @PLAYERNAME AND GLOVEBRAND IS NOT NULL
 ORDER BY "FIRST DAY" DESC
) ccc
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock)
 ON GLOVEBRAND = "Mfgr Code"
) c ON a.PLAYERNAME = c.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS SHOEBRAND, PLAYERNAME
FROM (
SELECT TOP 1 SHOEBRAND, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE) dd
 WHERE PLAYERNAME = @PLAYERNAME AND SHOEBRAND IS NOT NULL
 ORDER BY "FIRST DAY" DESC
) ddd
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock)
 ON SHOEBRAND = "Mfgr Code"
) d ON a.PLAYERNAME = d.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS SPIKEBRAND, COALESCE("Model Abbrev", "Model Descr") AS SPIKEMODEL, PLAYERNAME
FROM (
SELECT TOP 1 SPIKEBRAND, SPIKEMODEL, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE) ee
 WHERE PLAYERNAME = @PLAYERNAME AND SPIKEBRAND IS NOT NULL
 ORDER BY "FIRST DAY" DESC
) eee
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON SPIKEBRAND = "Mfgr Code"
LEFT OUTER JOIN LKP.[Model Codes and Descr] with (nolock) ON SPIKEMODEL = "Model Code"
) e ON a.PLAYERNAME = e.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS SHIRTBRAND, PLAYERNAME
FROM (
SELECT TOP 1 SHIRTBRAND, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE) ff
 WHERE PLAYERNAME = @PLAYERNAME AND SHIRTBRAND IS NOT NULL
 ORDER BY "FIRST DAY" DESC
) fff
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON SHIRTBRAND = "Mfgr Code"
) f ON a.PLAYERNAME = f.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS HEADGEARBRAND, PLAYERNAME
FROM (
SELECT TOP 1 HEADGEARBRAND, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND HEADGEARBRAND IS NOT NULL
 ORDER BY "FIRST DAY" DESC
) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON HEADGEARBRAND = "Mfgr Code"
) g ON a.PLAYERNAME = g.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS CADDYHEADBRAND, PLAYERNAME
FROM (
SELECT TOP 1 CADDYHEADBRAND, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND CADDYHEADBRAND IS NOT NULL
 ORDER BY "FIRST DAY" DESC
) hhh
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON CADDYHEADBRAND = "Mfgr Code"
) h ON a.PLAYERNAME = h.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS GLASSESBRAND, PLAYERNAME
FROM (
SELECT TOP 1 GLASSESBRAND, PLAYERNAME
FROM
(Select * from [Player_Master].[All] with (nolock)
 where "FIRST DAY" < @LOOKUPDATE and "FIRST DAY" > '1/1/2013') gg
 WHERE PLAYERNAME = @PLAYERNAME AND GLASSESBRAND IS NOT NULL
 ORDER BY "FIRST DAY" DESC
) iii
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON GLASSESBRAND = "Mfgr Code"
) i ON a.PLAYERNAME = i.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS RAINGEARBRAND, PLAYERNAME FROM (
SELECT TOP 1 RAINGEARBRAND, PLAYERNAME FROM
(Select * from [Player_Master].[All] with (nolock) where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND RAINGEARBRAND IS NOT NULL ORDER BY "FIRST DAY" DESC ) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON RAINGEARBRAND = "Mfgr Code") r ON a.PLAYERNAME = r.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS RAINCOVERBRAND, PLAYERNAME FROM (
SELECT TOP 1 RAINCOVERBRAND, PLAYERNAME FROM
(Select * from [Player_Master].[All] with (nolock) where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND RAINCOVERBRAND IS NOT NULL ORDER BY "FIRST DAY" DESC ) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON RAINCOVERBRAND = "Mfgr Code") rc ON a.PLAYERNAME = rc.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS RANGEPLAYERBRAND, PLAYERNAME FROM (
SELECT TOP 1 RANGEPLAYERBRAND, PLAYERNAME FROM
(Select * from [Player_Master].[All] with (nolock) where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND RANGEPLAYERBRAND IS NOT NULL ORDER BY "FIRST DAY" DESC ) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON RANGEPLAYERBRAND = "Mfgr Code") rgp ON a.PLAYERNAME = rgp.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS RANGECADDYBRAND, PLAYERNAME FROM (
SELECT TOP 1 RANGECADDIEBRAND, PLAYERNAME FROM
(Select * from [Player_Master].[All] with (nolock) where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND RANGECADDIEBRAND IS NOT NULL ORDER BY "FIRST DAY" DESC ) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON RANGECADDIEBRAND = "Mfgr Code") rgc ON a.PLAYERNAME = rgc.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS TOWELBRAND, PLAYERNAME FROM (
SELECT TOP 1 TOWELBRAND, PLAYERNAME FROM
(Select * from [Player_Master].[All] with (nolock) where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND TOWELBRAND IS NOT NULL ORDER BY "FIRST DAY" DESC ) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON TOWELBRAND = "Mfgr Code") tw ON a.PLAYERNAME = tw.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS TRAVELBAGBRAND, PLAYERNAME FROM (
SELECT TOP 1 TRAVELBAGBRAND, PLAYERNAME FROM
(Select * from [Player_Master].[All] with (nolock) where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND TRAVELBAGBRAND IS NOT NULL ORDER BY "FIRST DAY" DESC ) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON TRAVELBAGBRAND = "Mfgr Code") tb ON a.PLAYERNAME = tb.PLAYERNAME

LEFT OUTER JOIN (
SELECT TOP 1 COALESCE("Mfgr Abbrev", "Mfgr Descr") AS LAUNCHMONITORBRAND, PLAYERNAME FROM (
SELECT TOP 1 LAUNCHMONITORBRAND, PLAYERNAME FROM
(Select * from [Player_Master].[All] with (nolock) where "FIRST DAY" < @LOOKUPDATE) gg
 WHERE PLAYERNAME = @PLAYERNAME AND LAUNCHMONITORBRAND IS NOT NULL ORDER BY "FIRST DAY" DESC ) ggg
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] with (nolock) ON LAUNCHMONITORBRAND = "Mfgr Code") lm ON a.PLAYERNAME = lm.PLAYERNAME

END
GO
