DROP PROCEDURE IF EXISTS [CR_Proofing].[All];
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE [CR_Proofing].[All]
	@FIRSTNAME varchar(50),
	@LASTNAME varchar(50),
	@FIRSTDAY date

AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @PLAYERNAME VARCHAR(65);
	IF (@LASTNAME <> '' AND @FIRSTNAME <> '')
	SET @PLAYERNAME = @LASTNAME + ', ' + @FIRSTNAME;
	ELSE
	SET @PLAYERNAME = @FIRSTNAME;

IF (@PLAYERNAME<>'')
BEGIN

SELECT COALESCE(a."Mfgr Abbrev", a."Mfgr Descr") AS BALLBRAND,
COALESCE(b."Model Abbrev", b."Model Descr") AS BALLMODEL,
BALLMATERIAL, BALLMISC,
COALESCE(c."Mfgr Abbrev", c."Mfgr Descr") AS BAGBRAND,
COALESCE(d."Mfgr Abbrev", d."Mfgr Descr") AS GLOVEBRAND,
COALESCE(e."Mfgr Abbrev", e."Mfgr Descr") AS SHOEBRAND,
COALESCE(f."Mfgr Abbrev", f."Mfgr Descr") AS SPIKEBRAND,
COALESCE(g."Model Abbrev", g."Model Descr") AS SPIKEMODEL,
COALESCE(h."Mfgr Abbrev", h."Mfgr Descr") AS SHIRTBRAND,
COALESCE(i."Mfgr Abbrev", i."Mfgr Descr") AS HEADGEARBRAND,
COALESCE(j."Mfgr Abbrev", j."Mfgr Descr") AS CADDYHEADBRAND,
COALESCE(l."Mfgr Abbrev", l."Mfgr Descr") AS GLASSESBRAND,
COALESCE(o."Mfgr Abbrev", o."Mfgr Descr") AS RAINGEARBRAND,
COALESCE(p."Mfgr Abbrev", p."Mfgr Descr") AS RAINCOVERBRAND,
COALESCE(q."Mfgr Abbrev", q."Mfgr Descr") AS TOWELBRAND,
COALESCE(r."Mfgr Abbrev", r."Mfgr Descr") AS TRAVELBAGBRAND,
COALESCE(m."Mfgr Abbrev", m."Mfgr Descr") AS RANGEPLAYERBRAND,
COALESCE(n."Mfgr Abbrev", n."Mfgr Descr") AS RANGECADDYBRAND,
COALESCE(lm."Mfgr Abbrev", lm."Mfgr Descr") AS LAUNCHMONITORBRAND

FROM [Input].[All] z
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BALLBRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON BALLMODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] c ON BAGBRAND = c."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON GLOVEBRAND = d."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] e ON SHOEBRAND = e."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] f ON SPIKEBRAND = f."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] g ON SPIKEMODEL = g."Model Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] h ON SHIRTBRAND = h."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] i ON HEADGEARBRAND = i."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] j ON CADDYHEADBRAND = j."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] l ON GLASSESBRAND = l."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] m ON RANGEPLAYERBRAND = m."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] n ON RANGECADDIEBRAND = n."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] o ON RAINGEARBRAND = o."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] p ON RAINCOVERBRAND = p."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] q ON TOWELBRAND = q."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] r ON TRAVELBAGBRAND = r."Mfgr Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] lm ON LAUNCHMONITORBRAND = lm."Mfgr Descr"

--execute CR_Proofing.[All] 'JOE', 'AFFRUNTI', '1/13/2011'

WHERE PLAYERNAME = @PLAYERNAME AND "FIRST DAY" = @FIRSTDAY

END
ELSE
SELECT 'BALLBRANDBALLBRAND' AS BALLBRAND,
'BALLMODELBALLMODEL' AS BALLMODEL,
'BALLMATERIAL' AS BALLMATERIAL,
'BALLMISC' AS BALLMISC,
'BAGBRANDBAGBRAND' AS BAGBRAND,
'GLOVEBRANDGLOVEBRAND' AS GLOVEBRAND,
'SHOEBRANDSHOEBRAND' AS SHOEBRAND,
'SPIKEBRANDSPIKEBRAND' AS SPIKEBRAND,
'SPIKEMODELSPIKEMODEL' AS SPIKEMODEL,
'SHIRTBRANDSHIRTBRAND' AS SHIRTBRAND,
'HEADGEARBRANDHEADGEARBRAND' AS HEADGEARBRAND,
'CADDYHEADBRANDCADDYHEADBRAND' AS CADDYHEADBRAND,
'GLASSESBRANDGLASSESBRAND' AS GLASSESBRAND,
'RAINGEARBRANDRAINGEARBRAND' AS RAINGEARBRAND,
'RAINCOVERBRANDRAINCOVERBRAND' AS RAINCOVERBRAND,
'TOWELBRANDTOWELBRAND' AS TOWELBRAND,
'TRAVELBAGBRANDTRAVELBAGBRAND' AS TRAVELBAGBRAND,
'RANGEPLAYERBRANDRANGEPLAYERBRAND' AS RANGEPLAYERBRAND,
'RANGECADDIEBRANDRANGECADDIEBRAND' AS RANGECADDYBRAND,
'LAUNCHMONITORBRANDLAUNCHMONITORBRAND' AS LAUNCHMONITORBRAND

FROM [Input].[All]

END
GO
