IF OBJECT_ID('CR_Proofing.Irons') IS NOT NULL
    DROP PROCEDURE [CR_Proofing].[Irons];
GO

CREATE PROCEDURE [CR_Proofing].[Irons]
	-- Add the parameters for the stored procedure here

	@FIRSTNAME varchar(50),
	@LASTNAME varchar(50),
	@FIRSTDAY date,
	@IRONSHAFTVIS varchar(10) = 'True',
	@IRONGRIPVIS varchar(10) = 'True'

AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @PLAYERNAME VARCHAR(65);
	IF (@LASTNAME <> '' AND @FIRSTNAME <> '')
	SET @PLAYERNAME = @LASTNAME + ', ' + @FIRSTNAME;
	ELSE
	SET @PLAYERNAME = @FIRSTNAME;

IF (@PLAYERNAME<>'')
BEGIN
SELECT
CLUBCODE,
COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) AS BRAND,
COALESCE(b.[Model Abbrev], b.[Model Descr]) AS MODEL,
COALESCE(c.[Matl Abbrev], c.[Matl Descr]) AS MATERIAL,
[SIZE],
z.MISC,
CASE WHEN @IRONSHAFTVIS <> 'True' THEN NULL ELSE CASE WHEN COALESCE(d.[Mfgr Abbrev], d.[Mfgr Descr]) = COALESCE(e.[Mfgr Abbrev], e.[Mfgr Descr]) THEN '=' ELSE COALESCE(d.[Mfgr Abbrev], d.[Mfgr Descr]) END END AS SHAFTMFGR,
CASE WHEN @IRONSHAFTVIS <> 'True' THEN NULL ELSE COALESCE(e.[Mfgr Abbrev], e.[Mfgr Descr]) END AS SHAFTBRAND,
CASE WHEN @IRONSHAFTVIS <> 'True' THEN NULL ELSE COALESCE(f.[model abbrev], f.[Model Descr]) END AS SHAFTMODEL,
CASE WHEN @IRONSHAFTVIS <> 'True' THEN NULL ELSE SHAFTFLEX END AS SHAFTFLEX,
CASE WHEN @IRONSHAFTVIS <> 'True' THEN NULL ELSE SHAFTTYPE END AS SHAFTTYPE,
CASE WHEN @IRONSHAFTVIS <> 'True' THEN NULL ELSE COALESCE(g.[Matl Abbrev], g.[Matl Descr]) END AS SHAFTMATL,
CASE WHEN @IRONGRIPVIS <> 'True' THEN NULL ELSE CASE WHEN COALESCE(h.[Mfgr Abbrev], h.[Mfgr Descr]) = COALESCE(i.[Mfgr Abbrev], i.[Mfgr Descr]) THEN '=' ELSE COALESCE(h.[Mfgr Abbrev], h.[Mfgr Descr]) END END AS GRIPMFGR,
CASE WHEN @IRONGRIPVIS <> 'True' THEN NULL ELSE COALESCE(i.[Mfgr Abbrev], i.[Mfgr Descr]) END AS GRIPBRAND,
CASE WHEN @IRONGRIPVIS <> 'True' THEN NULL ELSE COALESCE(j.[Model Abbrev], j.[Model Descr]) END AS GRIPMODEL,
CASE WHEN @IRONGRIPVIS <> 'True' THEN NULL ELSE GRIPTYPE END AS GRIPTYPE,
CASE WHEN @IRONGRIPVIS <> 'True' THEN NULL ELSE CASE WHEN COALESCE(k.[Matl Abbrev], k.[Matl Descr]) = '(RUBB)' THEN '-' ELSE COALESCE(k.[Matl Abbrev], k.[Matl Descr]) END END AS GRIPMATL,
'True' as isvisible, @IRONSHAFTVIS AS shaftisvisible, @IRONGRIPVIS AS gripisvisible

FROM [Input].[Iron] z
LEFT OUTER JOIN (SELECT * FROM [Input].[Shaft] WHERE PLAYERNAME = @PLAYERNAME AND [FIRST DAY] = @FIRSTDAY AND SHAFTEQUIPTYPE = 'IRON') y
ON CLUBCODE = SHAFTCLUBCODE AND z.[FIRST DAY] = y.[FIRST DAY] and z.PLAYERNAME = y.PLAYERNAME AND z.[PKey] = y.[PKey]
LEFT OUTER JOIN (SELECT * FROM [Input].[Grip] WHERE PLAYERNAME = @PLAYERNAME AND [FIRST DAY] = @FIRSTDAY AND GRIPEQUIPTYPE = 'IRON') x
ON CLUBCODE = GRIPCLUBCODE AND z.[FIRST DAY] = x.[FIRST DAY] and z.PLAYERNAME = x.PLAYERNAME AND z.[PKey] = x.[PKey]

LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b.[Model Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] c ON MATERIAL = c.[Matl Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON SHAFTMFGR = d.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] e ON SHAFTBRAND = e.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] f ON SHAFTMODEL = f.[Model Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] g ON SHAFTMATL = g.[Matl Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] h ON GRIPMFGR = h.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] i ON GRIPBRAND = i.[Mfgr Descr]
LEFT OUTER JOIN LKP.[Model Codes and Descr] j ON GRIPMODEL = j.[Model Descr]
LEFT OUTER JOIN LKP.[Material Codes and Descript] k ON GRIPMATL = k.[Matl Descr]

WHERE z.PLAYERNAME = @PLAYERNAME AND z.[FIRST DAY] = @FIRSTDAY
ORDER BY z.[PKey] ASC
END
ELSE


SELECT 'CLUBCODE' AS CLUBCODE, 'WEDGEBRANDWEDGEBRAND' AS BRAND, 'WEDGEMODELWEDGEMODEL' AS MODEL, 'WEDGEMATLWEDGEMATLWEDGEMATL' AS MATERIAL, 'WEDGESIZEWEDGESIZE' AS SIZE, 'WEDGEMISCWEDGEMISC' AS MISC,
'SHAFTMFGRSHAFTMFGRSHAFTMFGR' AS SHAFTMFGR, 'SHAFTBRANDSHAFTBRANDSHAFTBRAND' AS SHAFTBRAND, 'SHAFTMODELSHAFTMODELSHAFTMODEL' AS SHAFTMODEL, 'SHAFTTYPESHAFTTYPE' AS SHAFTTYPE, 'SHAFTMATLSHAFTMATL' AS SHAFTMATL,
'GRIPMFGRGRIPMFGRGRIPMFGRGRIPMFGR' AS GRIPMFGR, 'GRIPBRANDGRIPBRANDGRIPBRAND' AS GRIPBRAND, 'GRIPMODELGRIPMODELGRIPMODEL' AS GRIPMODEL, 'GRIPTYPEGRIPTYPE' AS GRIPTYPE, 'GRIPMATLGRIPMATL' AS GRIPMATL
FROM Input.Iron;

END
GO
