IF OBJECT_ID('CR_Reports.Ball_Driver_Putter_Glove_Shoes') IS NOT NULL
    DROP PROCEDURE [CR_Reports].[Ball_Driver_Putter_Glove_Shoes];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [CR_Reports].[Ball_Driver_Putter_Glove_Shoes]
	-- Add the parameters for the stored procedure here
	
	@FIRSTDAY date,
	@SID int

AS
BEGIN


with BALLTABLE AS (
SELECT
1 AS BALLNUMBER,
d.PLAYERNAME, CATEGORY, EXTRA, a.[Mfgr Descr] AS BALLBRAND, DBALLBRAND, b.[Model Descr] AS BALLMODEL, DBALLMODEL, e.[Mfgr Descr] AS GLOVEBRAND, DGLOVEBRAND, f.[Mfgr Descr] as SHOEBRAND, DSHOEBRAND
FROM [Player_Master].[All] d
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a.[Mfgr Code] 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b.[Model Code]
LEFT OUTER JOIN Player_Master.PLAYERNAMES c on d.PLAYERNAME = c.PLAYERNAME AND c.SID = d.SID AND c.FIRSTDAY = d.[FIRST DAY]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] e on GLOVEBRAND = e.[Mfgr Code]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] f on SHOEBRAND = f.[Mfgr Code]
WHERE [FIRST DAY] = @FIRSTDAY AND d.SID = @SID
),


DRIVERTABLE as 
(SELECT
row_number() OVER(PARTITION BY I.PLAYERNAME ORDER BY [PKey] ASC) AS DRIVERNUMBER,
COALESCE(BALLTABLE.PLAYERNAME, I.PLAYERNAME) AS PLAYERNAME, CATEGORY, EXTRA, BALLMODEL, DBALLMODEL, BALLBRAND, DBALLBRAND, SHOEBRAND, DSHOEBRAND, GLOVEBRAND, DGLOVEBRAND,
WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATERIAL, DMATERIAL, [PKey]
FROM BALLTABLE
INNER JOIN
(SELECT
row_number() OVER(PARTITION BY [Name] ORDER BY [PKey] ASC) AS SUBDRIVERNUMBER,
[Name] AS PLAYERNAME, [Wood Club Code] AS WOODCLUBCODE, DCLUBCODE, a.[Mfgr Descr] AS WOODBRAND, DBRANDCODE, b.[Model Descr] AS WOODMODEL, DMODELCODE,
c.[Size Descr] AS WOODSIZE, DSIZECODE, d.[Matl Descr] AS WOODMATERIAL, DMATERIAL, [PKey]
FROM Player_Master.[Wood Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Wood Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Wood Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Wood Size Code] = [Size Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON [Wood Mat'l Code] = [Matl Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID and ISDRIVER = 1
GROUP BY [Name], [Wood Club Code], a.[Mfgr Descr], b.[Model Descr], [PKey], DCLUBCODE, DBRANDCODE, DMODELCODE, c.[Size Descr], d.[Matl Descr], DSIZECODE, DMATERIAL) AS I
ON BALLTABLE.PLAYERNAME = I.PLAYERNAME
and BALLTABLE.BALLNUMBER = SUBDRIVERNUMBER 
),

PUTTERTABLE AS (
SELECT
row_number() OVER(PARTITION BY BALLTABLE.PLAYERNAME ORDER BY [PKey]) AS PUTTERNUMBER,
BALLTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERCLUBCODE, DCLUBCODE, PUTTERBRAND, DBRANDCODE, PUTTERMODEL, DMODELCODE, PUTTERSIZE, DSIZECODE, PUTTERMATL, DMATERIAL
FROM BALLTABLE
INNER JOIN
( SELECT
[Name] AS PLAYERNAME, [Putter Sequence No] AS PUTTERCLUBCODE, DCLUBCODE,
ISNULL(a.[Mfgr Abbrev], a.[Mfgr Descr]) AS PUTTERBRAND, DBRANDCODE,
b.[Model Descr] AS PUTTERMODEL, DMODELCODE, 
c.[Size Descr] AS PUTTERSIZE, DSIZECODE,
ISNULL(d.[Matl Abbrev], d.[Matl Descr]) AS PUTTERMATL, DMATERIAL,
[PKey]
FROM Player_Master.[Putter Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON [Putter Brand Code] = a.[Mfgr Code]
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON [Putter Model Code] = b.[Model Code]
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON [Putter Size Code] = [Size Code]
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON [Putter Mat'l Code] = [Matl Code]
WHERE [First Day] = @FIRSTDAY AND [Survey ID] = @SID 
) W
ON BALLTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(DRIVERTABLE.PLAYERNAME, PUTTERTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(DRIVERTABLE.CATEGORY, PUTTERTABLE.CATEGORY) AS CATEGORY, COALESCE(DRIVERTABLE.EXTRA, PUTTERTABLE.EXTRA) AS EXTRA,
BALLBRAND, DBALLBRAND, BALLMODEL, DBALLMODEL,
WOODCLUBCODE, DRIVERTABLE.DCLUBCODE, WOODBRAND, DRIVERTABLE.DBRANDCODE, WOODMODEL, DRIVERTABLE.DMODELCODE, DRIVERTABLE.WOODSIZE, DRIVERTABLE.DSIZECODE, DRIVERTABLE.WOODMATERIAL, DRIVERTABLE.DMATERIAL,
PUTTERBRAND, PUTTERTABLE.DBRANDCODE, PUTTERMODEL, PUTTERTABLE.DMODELCODE, PUTTERSIZE, PUTTERTABLE.DSIZECODE,
GLOVEBRAND, DGLOVEBRAND, SHOEBRAND, DSHOEBRAND

FROM DRIVERTABLE
FULL OUTER JOIN
PUTTERTABLE ON DRIVERTABLE.PLAYERNAME = PUTTERTABLE.PLAYERNAME AND DRIVERNUMBER = PUTTERNUMBER
Order By COALESCE(DRIVERTABLE.EXTRA, PUTTERTABLE.EXTRA, ''), Coalesce(DRIVERTABLE.PLAYERNAME, PUTTERTABLE.PLAYERNAME), Coalesce(DRIVERNUMBER, PUTTERNUMBER);
END




/*
    -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SELECT b.PLAYERNAME, CATEGORY, EXTRA,
	ISNULL(e.[Mfgr Abbrev], e.[Mfgr Descr]) AS BALLBRAND, DBALLBRAND,
	ISNULL(f.[Model Abbrev], f.[Model Descr]) AS BALLMODEL, DBALLMODEL,
	
	j.CLUBCODE AS WOODCLUBCODE, j.DCLUBCODE,
COALESCE(k.[Mfgr Abbrev], k.[Mfgr Descr]) AS WOODBRANDCODE, j.DBRANDCODE,
COALESCE(l.[model abbrev], l.[Model Descr]) AS WOODMODEL, j.DMODELCODE,
COALESCE(m.[Matl Abbrev], m.[Matl Descr]) AS WOODMATERIAL, j.DMATERIAL,
j.SIZE AS WOODSIZE, j.DSIZECODE,
j.MISC AS WOODMISC, j.DSIZECODE,
	
	
	COALESCE(h.[Mfgr Abbrev], h.[Mfgr Descr]) AS PUTTERBRAND, g.DBRANDCODE AS DPUTTERBRAND,
	COALESCE(i.[Model Abbrev], i.[Model Descr]) AS PUTTERMODEL, g.DMODELCODE AS DPUTTERMODEL,
	COALESCE(o.[Size Abbrev], g.SIZE) AS PUTTERSIZE, g.DSIZECODE AS DPUTTERSIZE,
	COALESCE(a.[Mfgr Abbrev], a.[Mfgr Descr]) AS GLOVEBRAND, DGLOVEBRAND,
	COALESCE(d.[Mfgr Abbrev], d.[Mfgr Descr]) AS SHOEBRAND, DSHOEBRAND


FROM (SELECT * FROM Input.[All] WHERE [FIRST DAY] = @FIRSTDAY AND [SID] = @SID )  b
-- all items
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON GLOVEBRAND = a.[Mfgr Descr]  
LEFT OUTER JOIN Player_Master.PLAYERNAMES c on b.PLAYERNAME = c.PLAYERNAME AND c.FIRSTDAY = b.[FIRST DAY] and c.SID = b.SID 
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] d ON SHOEBRAND = d.[Mfgr Descr]  
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] e ON BALLBRAND = e.[Mfgr Descr]  
LEFT OUTER JOIN [LKP].[Model Codes and Descr] f ON BALLMODEL = f.[Model Descr]  
--putter
LEFT OUTER JOIN (SELECT * FROM Input.Putter where SID = @SID and [First Day] = @FIRSTDAY) g ON b.PLAYERNAME = g.PLAYERNAME
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] h ON g.BRAND = h.[Mfgr Descr]  
LEFT OUTER JOIN [LKP].[Model Codes and Descr] i ON g.MODEL = i.[Model Descr]
left outer join LKP.[Size Codes and Description] o on SIZE = [Size Descr] 
--driver
LEFT OUTER JOIN (SELECT * FROM Input.Wood where SID = @SID and [First Day] = @FIRSTDAY and ISDRIVER = 1) j ON b.PLAYERNAME = j.PLAYERNAME
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] k ON j.BRAND = k.[Mfgr Descr] 
LEFT OUTER JOIN LKP.[Model Codes and Descr] l ON j.MODEL = l.[Model Descr] 
LEFT OUTER JOIN LKP.[Material Codes and Descript] m ON j.MATERIAL = m.[Matl Descr] 
--left outer join LKP.[Size Codes and Description] p on j.SIZE = p.[Size Descr]

ORDER BY b.PLAYERNAME ASC
*/
GO
