IF OBJECT_ID('CR_Reports.Player_Info') IS NOT NULL
    DROP PROCEDURE [CR_Reports].[Player_Info];
GO

CREATE PROCEDURE [CR_Reports].[Player_Info]
	@FIRSTNAME varchar(50),
	@LASTNAME varchar(50),
	@SID int,
	@FIRSTDAY date
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @PLAYERNAME varchar(65);
	IF (@LASTNAME <> '' AND @FIRSTNAME <> '')
		SET @PLAYERNAME = @LASTNAME + ', ' + @FIRSTNAME;
	ELSE
		SET @PLAYERNAME = @FIRSTNAME;

	SELECT TOP 1 [INDEX], EXTRA, SurveyorNote AS NOTE
	FROM Player_Master.PLAYERNAMES WITH (NOLOCK)
	WHERE PLAYERNAME = @PLAYERNAME AND SID = @SID AND FIRSTDAY = @FIRSTDAY;
END
GO
