DROP PROCEDURE IF EXISTS [CR_Reports].[Iron_Wood_Putter_Grip];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [CR_Reports].[Iron_Wood_Putter_Grip]
	-- Add the parameters for the stored procedure here
	@FIRSTDAY date,
	@SID int

AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

-- exec cr_reports.iron_wood_putter_grip '9/15/2016', 293

with PLAYERTABLE AS (
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, CATEGORY, EXTRA
FROM [Player_Master].[PLAYERNAMES]
WHERE "FIRSTDAY" = @FIRSTDAY AND SID = @SID
),


IRONGRIPTABLE as 
(SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY 
CASE WHEN GRIPEQUIPTYPE = 'WEDG'
THEN "PKey" END,
CASE WHEN GRIPEQUIPTYPE = 'IRON'
THEN "PKey" END

) AS IRONNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA,
IRONCLUBCODE, DCLUBCODE, IRONGRIPMFGR, DMFGRCODE, IRONGRIPBRAND, DBRANDCODE, IRONGRIPMODEL, DMODELCODE, IRONGRIPMATL, DMATERIAL, "PKey"
FROM PLAYERTABLE
INNER JOIN
(
SELECT PLAYERNAME, GRIPCLUBCODE AS IRONCLUBCODE, DCLUBCODE, ISNULL(d."Mfgr Abbrev", d."Mfgr Descr") AS IRONGRIPMFGR, DMFGRCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS IRONGRIPBRAND, DBRANDCODE, ISNULL(b."Model Abbrev", b."Model Descr") AS IRONGRIPMODEL, DMODELCODE,
ISNULL(c."Matl Abbrev", c."Matl Descr") AS IRONGRIPMATL, DMATERIAL, "PKey", GRIPEQUIPTYPE
FROM input.GRIP
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON GRIPBRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON GRIPMODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] c ON GRIPMATL = c."Matl Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON GRIPMFGR = d."Mfgr Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND (GRIPEQUIPTYPE = 'IRON' OR GRIPEQUIPTYPE = 'WEDG')
--GROUP BY "Name", "GRIP Club Code", ISNULL(a."Mfgr Abbrev", a."Mfgr Descr"), b."Model Descr", "PKey"
) AS I
ON PLAYERTABLE.PLAYERNAME = I.PLAYERNAME
),

WOODGRIPTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS WOODNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODGRIPMFGR, DMFGRCODE, WOODGRIPBRAND, DBRANDCODE, WOODGRIPMODEL, DMODELCODE, WOODGRIPMATL, DMATERIAL
FROM PLAYERTABLE
INNER JOIN
( SELECT
PLAYERNAME, GRIPCLUBCODE AS WOODCLUBCODE, DCLUBCODE,
ISNULL(d."Mfgr Abbrev", d."Mfgr Descr") AS WOODGRIPMFGR, DMFGRCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS WOODGRIPBRAND, DBRANDCODE,
ISNULL(b."Model Abbrev", b."Model Descr") AS WOODGRIPMODEL, DMODELCODE,
ISNULL(c."Matl Abbrev", c."Matl Descr") AS WOODGRIPMATL, DMATERIAL,
"PKey"
FROM Input.GRIP
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON GRIPBRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON GRIPMODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] c ON GRIPMATL = c."Matl Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON GRIPMFGR = d."Mfgr Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND GRIPEQUIPTYPE = 'WOOD'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME
),

PUTTERGRIPTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS PUTTERNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, PUTTERCLUBCODE, DCLUBCODE, PUTTERGRIPMFGR, DMFGRCODE, PUTTERGRIPBRAND, DBRANDCODE, PUTTERGRIPMODEL, DMODELCODE, PUTTERGRIPMATL, DMATERIAL
FROM PLAYERTABLE
INNER JOIN
( SELECT
PLAYERNAME, GRIPCLUBCODE AS PUTTERCLUBCODE, DCLUBCODE,
ISNULL(d."Mfgr Abbrev", d."Mfgr Descr") AS PUTTERGRIPMFGR, DMFGRCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS PUTTERGRIPBRAND, DBRANDCODE,
ISNULL(b."Model Abbrev", b."Model Descr") AS PUTTERGRIPMODEL, DMODELCODE,
ISNULL(c."Matl Abbrev", c."Matl Descr") AS PUTTERGRIPMATL, DMATERIAL,
"PKey"
FROM Input.GRIP
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON GRIPBRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON GRIPMODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] c ON GRIPMATL = c."Matl Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON GRIPMFGR = d."Mfgr Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND GRIPEQUIPTYPE = 'PUTT'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME


)


SELECT COALESCE(IRONGRIPTABLE.PLAYERNAME, WOODGRIPTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONGRIPTABLE.CATEGORY, WOODGRIPTABLE.CATEGORY) AS CATEGORY,
COALESCE(IRONGRIPTABLE.EXTRA, WOODGRIPTABLE.EXTRA) AS EXTRA,
IRONCLUBCODE AS IRONGRIPCLUBCODE, IRONGRIPTABLE.DCLUBCODE, IRONGRIPMFGR, IRONGRIPTABLE.DMFGRCODE, IRONGRIPBRAND, IRONGRIPTABLE.DBRANDCODE, IRONGRIPMODEL, IRONGRIPTABLE.DMODELCODE, IRONGRIPMATL, IRONGRIPTABLE.DMATERIAL,
WOODCLUBCODE AS WOODGRIPCLUBCODE, WOODGRIPTABLE.DCLUBCODE, WOODGRIPMFGR, WOODGRIPTABLE.DMFGRCODE, WOODGRIPBRAND, WOODGRIPTABLE.DBRANDCODE, WOODGRIPMODEL, WOODGRIPTABLE.DMODELCODE, WOODGRIPMATL, WOODGRIPTABLE.DMATERIAL,
PUTTERCLUBCODE AS PUTTERGRIPCLUBCODE, PUTTERGRIPTABLE.DCLUBCODE, PUTTERGRIPMFGR, PUTTERGRIPTABLE.DMFGRCODE, PUTTERGRIPBRAND, PUTTERGRIPTABLE.DBRANDCODE, PUTTERGRIPMODEL, PUTTERGRIPTABLE.DMODELCODE, PUTTERGRIPMATL, PUTTERGRIPTABLE.DMATERIAL

FROM IRONGRIPTABLE
FULL OUTER JOIN
WOODGRIPTABLE ON IRONGRIPTABLE.PLAYERNAME = WOODGRIPTABLE.PLAYERNAME AND IRONNUMBER = WOODNUMBER
FULL OUTER JOIN
PUTTERGRIPTABLE ON IRONGRIPTABLE.PLAYERNAME = PUTTERGRIPTABLE.PLAYERNAME AND IRONNUMBER = PUTTERNUMBER
Order By COALESCE(IRONGRIPTABLE.EXTRA, WOODGRIPTABLE.EXTRA), Coalesce(IRONGRIPTABLE.PLAYERNAME, WOODGRIPTABLE.PLAYERNAME), Coalesce(IRONNUMBER, WOODNUMBER)


END
GO
