IF OBJECT_ID('Flash.Iron_Iron_Grip') IS NOT NULL
    DROP PROCEDURE [Flash].[Iron_Iron_Grip];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [Flash].[Iron_Iron_Grip]
	-- Add the parameters for the stored procedure here
	
	@FIRSTDAY date,
	@SID int

AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;


with PLAYERTABLE AS (
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, CATEGORY, EXTRA
FROM [Player_Master].[PLAYERNAMES]
WHERE "FIRSTDAY" = @FIRSTDAY AND SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS IRONNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, "PKey"
FROM PLAYERTABLE
INNER JOIN
(
SELECT PLAYERNAME, CLUBCODE AS IRONCLUBCODE, DCLUBCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS IRONBRAND, DBRANDCODE, ISNULL(b."Model Abbrev", b."Model Descr") AS IRONMODEL, DMODELCODE,
"PKey"
FROM input.iron
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b."Model Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID
--GROUP BY "Name", "Shaft Club Code", ISNULL(a."Mfgr Abbrev", a."Mfgr Descr"), b."Model Descr", "PKey"
) AS I
ON PLAYERTABLE.PLAYERNAME = I.PLAYERNAME
),

IRONGRIPTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS IRONGRIPNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, IRONGRIPCLUBCODE, DCLUBCODE, IRONGRIPMFGR, DMFGRCODE, IRONGRIPBRAND, DBRANDCODE, IRONGRIPMODEL, DMODELCODE, IRONGRIPMATL, DMATERIAL
FROM PLAYERTABLE
INNER JOIN
( SELECT
PLAYERNAME, GRIPCLUBCODE AS IRONGRIPCLUBCODE, DCLUBCODE,
ISNULL(d."Mfgr Abbrev", d."Mfgr Descr") AS IRONGRIPMFGR, DMFGRCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS IRONGRIPBRAND, DBRANDCODE,
ISNULL(b."Model Abbrev", b."Model Descr") AS IRONGRIPMODEL, DMODELCODE,
ISNULL(c."Matl Abbrev", c."Matl Descr") AS IRONGRIPMATL, DMATERIAL,
"PKey"
FROM input.grip
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON GRIPBRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON GRIPMODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] c ON GRIPMATL = c."Matl Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON GRIPMFGR = d."Mfgr Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND GRIPEQUIPTYPE = 'IRON'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONTABLE.PLAYERNAME, IRONGRIPTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, IRONGRIPTABLE.CATEGORY) AS CATEGORY,
COALESCE(IRONTABLE.EXTRA, IRONGRIPTABLE.EXTRA) AS EXTRA,
IRONCLUBCODE, IRONTABLE.DCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE,
IRONGRIPCLUBCODE AS GRIPCLUBCODE, IRONGRIPTABLE.DCLUBCODE, IRONGRIPMFGR AS GRIPMFGR, IRONGRIPTABLE.DMFGRCODE, IRONGRIPBRAND AS GRIPBRAND,
IRONGRIPTABLE.DBRANDCODE, IRONGRIPMODEL AS GRIPMODEL, IRONGRIPTABLE.DMODELCODE, IRONGRIPMATL AS GRIPMATL, IRONGRIPTABLE.DMATERIAL

FROM IRONTABLE
FULL OUTER JOIN
IRONGRIPTABLE ON IRONTABLE.PLAYERNAME = IRONGRIPTABLE.PLAYERNAME AND IRONNUMBER = IRONGRIPNUMBER
Order By COALESCE(IRONTABLE.EXTRA, IRONGRIPTABLE.EXTRA), Coalesce(IRONTABLE.PLAYERNAME, IRONGRIPTABLE.PLAYERNAME), Coalesce(IRONNUMBER, IRONGRIPNUMBER)


END
GO
