DROP PROCEDURE IF EXISTS [Flash].[Utility_Iron_Hybrid_Wood];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [Flash].[Utility_Iron_Hybrid_Wood]
	-- Add the parameters for the stored procedure here
	
	@FIRSTDAY date,
	@SID int

AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;


with PLAYERTABLE AS (
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, CATEGORY, EXTRA
FROM [Player_Master].[PLAYERNAMES]
WHERE "FIRSTDAY" = @FIRSTDAY AND SID = @SID
),


IRONTABLE as 
(SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS IRONNUMBER,
PLAYERTABLE.PLAYERNAME, PLAYERTABLE.CATEGORY, PLAYERTABLE.EXTRA,
IRONCLUBCODE, DCLUBCODE, IRONBRAND, DBRANDCODE, IRONMODEL, DMODELCODE, "PKey"
FROM PLAYERTABLE
INNER JOIN
(
SELECT PLAYERNAME  AS PLAYERNAME, CLUBCODE AS IRONCLUBCODE, DCLUBCODE, a."Mfgr Descr" AS IRONBRAND, DBRANDCODE, b."Model Descr" AS IRONMODEL, DMODELCODE, "PKey"
FROM input.iron
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b."Model Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND CLUBCODE LIKE '%^%'
GROUP BY PLAYERNAME , CLUBCODE, a."Mfgr Descr", b."Model Descr", "PKey", DCLUBCODE, DBRANDCODE, DMODELCODE) AS I
ON PLAYERTABLE.PLAYERNAME = I.PLAYERNAME
),

WOODTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS WOODNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODBRAND, DBRANDCODE, WOODMODEL, DMODELCODE, WOODSIZE, DSIZECODE, WOODMATL, DMATERIAL
FROM PLAYERTABLE
INNER JOIN
( SELECT
PLAYERNAME  AS PLAYERNAME, CLUBCODE AS WOODCLUBCODE, DCLUBCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS WOODBRAND, DBRANDCODE,
ISNULL(b."Model Abbrev", b."Model Descr") AS WOODMODEL, DMODELCODE,
c."Size Descr" AS WOODSIZE, DSIZECODE,
ISNULL(d."Matl Abbrev", d."Matl Descr") AS WOODMATL, DMATERIAL,
"PKey"
FROM input.wood
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON BRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON MODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON SIZE = "Size Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON MATERIAL = "Matl Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND CLUBCODE = 'HYB'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONTABLE.PLAYERNAME, WOODTABLE.PLAYERNAME) AS PLAYERNAME, COALESCE(IRONTABLE.CATEGORY, WOODTABLE.CATEGORY) AS CATEGORY,
COALESCE(IRONTABLE.EXTRA, WOODTABLE.EXTRA) AS EXTRA,
IRONCLUBCODE, IRONTABLE.DCLUBCODE, IRONBRAND, IRONTABLE.DBRANDCODE, IRONMODEL, IRONTABLE.DMODELCODE,
WOODCLUBCODE, WOODTABLE.DCLUBCODE, WOODBRAND, WOODTABLE.DBRANDCODE, WOODMODEL, WOODTABLE.DMODELCODE, WOODSIZE, WOODTABLE.DSIZECODE, WOODMATL, WOODTABLE.DMATERIAL

FROM IRONTABLE
FULL OUTER JOIN
WOODTABLE ON IRONTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND IRONNUMBER = WOODNUMBER
Order By COALESCE(IRONTABLE.EXTRA, WOODTABLE.EXTRA), Coalesce(IRONTABLE.PLAYERNAME, WOODTABLE.PLAYERNAME), Coalesce(IRONNUMBER, WOODNUMBER)




/*
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, a."Mfgr Descr" AS BALLBRAND, b."Model Descr" AS BALLMODEL
FROM [Player_Master].[All]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a."Mfgr Descr" 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b."Model Descr" 
WHERE "FIRST DAY" = @FIRSTDAY AND SID = @SID 
) BALLTABLE
LEFT OUTER JOIN
IRONTABLE ON BALLTABLE.PLAYERNAME = IRONTABLE.PLAYERNAME

FULL JOIN

WOODTABLE ON BALLTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND coalesce(IRONNUMBER,0) = coalesce(WOODNUMBER,0)

*/


--, BALLNUMBER, IRONNUMBER, WOODNUMBER
/*FROM (
SELECT
row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, a."Mfgr Descr" AS BALLBRAND, b."Model Descr" AS BALLMODEL
FROM [Player_Master].[All]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a."Mfgr Descr" 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b."Model Descr" 
WHERE "FIRST DAY" = @FIRSTDAY AND SID = @SID 
) BALLTABLE
LEFT OUTER JOIN
(
SELECT
row_number() OVER(PARTITION BY PLAYERNAME  ORDER BY "PKey") AS IRONNUMBER,
PLAYERNAME  AS PLAYERNAME, "Iron Club Descr" AS IRONCLUBCODE, a."Mfgr Descr" AS IRONBRAND, b."Model Descr" AS IRONMODEL, "PKey"
FROM Player_Master.[Iron Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON "Iron Brand Descr" = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON "Iron Model Descr" = b."Model Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID 
GROUP BY PLAYERNAME , "Iron Club Descr", a."Mfgr Descr", b."Model Descr", "PKey"
) IRONTABLE ON BALLTABLE.PLAYERNAME = IRONTABLE.PLAYERNAME
LEFT OUTER JOIN
(
SELECT
row_number() OVER(PARTITION BY PLAYERNAME  ORDER BY "PKey") AS WOODNUMBER,
PLAYERNAME  AS PLAYERNAME, "Wood Club Descr" AS WOODCLUBCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS WOODBRAND,
ISNULL(b."Model Abbrev", b."Model Descr") AS WOODMODEL,
c."Size Descr" AS WOODSIZE,
ISNULL(d."Matl Abbrev", d."Matl Descr") AS WOODMATL,
"PKey"
FROM Player_Master.[Wood Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON "Wood Brand Descr" = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON "Wood Model Descr" = b."Model Descr"
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON "Wood Size Descr" = "Size Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON "Wood Mat'l Descr" = "Matl Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID 
) WOODTABLE ON BALLTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND COALESCE(IRONNUMBER, 0) = COALESCE(WOODNUMBER, 0)

GROUP BY BALLTABLE.PLAYERNAME, BALLBRAND, BALLMODEL, IRONCLUBCODE, IRONBRAND, IRONMODEL, WOODCLUBCODE, WOODBRAND, WOODMODEL, WOODSIZE, WOODMATL
--, BALLNUMBER, IRONNUMBER, WOODNUMBER
ORDER BY BALLTABLE.PLAYERNAME
*/




/*SELECT PLAYERNAME, a."Mfgr Descr" AS BALLBRAND, b."Model Descr" AS BALLMODEL,
"Iron Club Descr" AS IRONCLUBCODE, e."Mfgr Descr" AS IRONBRAND, f."Model Descr" AS IRONMODEL,
 "Wood Club Descr" AS WOODCLUBCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS WOODBRAND,
ISNULL(b."Model Abbrev", b."Model Descr") AS WOODMODEL,
c."Size Descr" AS WOODSIZE,
ISNULL(d."Matl Abbrev", d."Matl Descr") AS WOODMATL

FROM (SELECT * FROM [Player_Master].[All] WHERE "FIRST DAY" = @FIRSTDAY AND SID = @SID) x
LEFT OUTER JOIN (SELECT * FROM Player_Master.[Iron Detail] WHERE "First Day" = @FIRSTDAY and SID = @SID) z ON PLAYERNAME = z.Name
LEFT OUTER JOIN (SELECT * FROM Player_Master.[Wood Detail] WHERE "First Day" = @FIRSTDAY and SID = @SID) y ON PLAYERNAME = y.Name
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON "Wood Brand Descr" = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON "Wood Model Descr" = b."Model Descr"
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON "Wood Size Descr" = "Size Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON "Wood Mat'l Descr" = "Matl Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] e ON "Iron Brand Descr" = e."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] f ON "Iron Model Descr" = f."Model Descr"
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON BALLBRAND = g."Mfgr Descr" 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] h ON BALLMODEL = h."Model Descr"


WHERE  x."FIRST DAY" = @FIRSTDAY AND SID = @SID */


END
GO
