DROP PROCEDURE IF EXISTS [Flash].[Iron_Wood_Shaft];
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [Flash].[Iron_Wood_Shaft]
	-- Add the parameters for the stored procedure here
	
	@FIRSTDAY date,
	@SID int

AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;


with PLAYERTABLE AS (
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, CATEGORY, EXTRA
FROM [Player_Master].[PLAYERNAMES]
WHERE "FIRSTDAY" = @FIRSTDAY AND SID = @SID
),


IRONSHAFTTABLE as 
(SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY 
CASE WHEN SHAFTEQUIPTYPE = 'WEDG'
THEN "PKey" END,
CASE WHEN SHAFTEQUIPTYPE = 'IRON'
THEN "PKey" END

) AS IRONNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA,
IRONCLUBCODE, DCLUBCODE, IRONSHAFTMFGR, DMFGRCODE, IRONSHAFTBRAND, DBRANDCODE, IRONSHAFTMODEL, DMODELCODE, IRONSHAFTMATL, DMATLCODE, "PKey"
FROM PLAYERTABLE
INNER JOIN
(
SELECT PLAYERNAME, SHAFTCLUBCODE AS IRONCLUBCODE, DCLUBCODE, ISNULL(d."Mfgr Abbrev", d."Mfgr Descr") AS IRONSHAFTMFGR, DMFGRCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS IRONSHAFTBRAND, DBRANDCODE, ISNULL(b."Model Abbrev", b."Model Descr") AS IRONSHAFTMODEL, DMODELCODE,
ISNULL(c."Matl Abbrev", c."Matl Descr") AS IRONSHAFTMATL, DMATLCODE, "PKey", SHAFTEQUIPTYPE
FROM input.shaft
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON SHAFTBRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON SHAFTMODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] c ON SHAFTMATL = c."Matl Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON SHAFTMFGR = d."Mfgr Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND (SHAFTEQUIPTYPE = 'IRON' OR SHAFTEQUIPTYPE = 'WEDG')
--GROUP BY "Name", "Shaft Club Code", ISNULL(a."Mfgr Abbrev", a."Mfgr Descr"), b."Model Descr", "PKey"
) AS I
ON PLAYERTABLE.PLAYERNAME = I.PLAYERNAME
),

WOODSHAFTTABLE AS (
SELECT
row_number() OVER(PARTITION BY PLAYERTABLE.PLAYERNAME ORDER BY "PKey") AS WOODNUMBER,
PLAYERTABLE.PLAYERNAME, CATEGORY, EXTRA, WOODCLUBCODE, DCLUBCODE, WOODSHAFTMFGR, DMFGRCODE, WOODSHAFTBRAND, DBRANDCODE, WOODSHAFTMODEL, DMODELCODE, WOODSHAFTMATL, DMATLCODE
FROM PLAYERTABLE
INNER JOIN
( SELECT
PLAYERNAME, SHAFTCLUBCODE AS WOODCLUBCODE, DCLUBCODE,
ISNULL(d."Mfgr Abbrev", d."Mfgr Descr") AS WOODSHAFTMFGR, DMFGRCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS WOODSHAFTBRAND, DBRANDCODE,
ISNULL(b."Model Abbrev", b."Model Descr") AS WOODSHAFTMODEL, DMODELCODE,
ISNULL(c."Matl Abbrev", c."Matl Descr") AS WOODSHAFTMATL, DMATLCODE,
"PKey"
FROM Input.shaft
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON SHAFTBRAND = a."Mfgr Descr"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON SHAFTMODEL = b."Model Descr"
LEFT OUTER JOIN LKP.[Material Codes and Descript] c ON SHAFTMATL = c."Matl Descr"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] d ON SHAFTMFGR = d."Mfgr Descr"
WHERE "First Day" = @FIRSTDAY AND SID = @SID AND SHAFTEQUIPTYPE = 'WOOD'
) W
ON PLAYERTABLE.PLAYERNAME = W.PLAYERNAME
)


SELECT COALESCE(IRONSHAFTTABLE.PLAYERNAME, WOODSHAFTTABLE.PLAYERNAME) AS PLAYERNAME,
COALESCE(IRONSHAFTTABLE.CATEGORY, WOODSHAFTTABLE.CATEGORY) AS CATEGORY, COALESCE(IRONSHAFTTABLE.EXTRA, WOODSHAFTTABLE.EXTRA) AS EXTRA,
IRONCLUBCODE AS IRONSHAFTCLUBCODE, IRONSHAFTTABLE.DCLUBCODE, IRONSHAFTMFGR, IRONSHAFTTABLE.DMFGRCODE, IRONSHAFTBRAND, IRONSHAFTTABLE.DBRANDCODE, IRONSHAFTMODEL, IRONSHAFTTABLE.DMODELCODE, IRONSHAFTMATL, IRONSHAFTTABLE.DMATLCODE,
WOODCLUBCODE AS WOODSHAFTCLUBCODE, WOODSHAFTTABLE.DCLUBCODE, WOODSHAFTMFGR, WOODSHAFTTABLE.DMFGRCODE, WOODSHAFTBRAND, WOODSHAFTTABLE.DBRANDCODE, WOODSHAFTMODEL, WOODSHAFTTABLE.DMODELCODE, WOODSHAFTMATL, WOODSHAFTTABLE.DMATLCODE

FROM IRONSHAFTTABLE
FULL OUTER JOIN
WOODSHAFTTABLE ON IRONSHAFTTABLE.PLAYERNAME = WOODSHAFTTABLE.PLAYERNAME AND IRONNUMBER = WOODNUMBER
Order By COALESCE(IRONSHAFTTABLE.EXTRA, WOODSHAFTTABLE.EXTRA), Coalesce(IRONSHAFTTABLE.PLAYERNAME, WOODSHAFTTABLE.PLAYERNAME), Coalesce(IRONNUMBER, WOODNUMBER)




/*
SELECT
--row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, a."Mfgr Descr" AS BALLBRAND, b."Model Descr" AS BALLMODEL
FROM [Player_Master].[All]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a."Mfgr Code" 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b."Model Code" 
WHERE "FIRST DAY" = @FIRSTDAY AND SID = @SID 
) BALLTABLE
LEFT OUTER JOIN
IRONTABLE ON BALLTABLE.PLAYERNAME = IRONTABLE.PLAYERNAME

FULL JOIN

WOODTABLE ON BALLTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND coalesce(IRONNUMBER,0) = coalesce(WOODNUMBER,0)

*/


--, BALLNUMBER, IRONNUMBER, WOODNUMBER
/*FROM (
SELECT
row_number() OVER(ORDER BY PLAYERNAME) AS BALLNUMBER,
PLAYERNAME, a."Mfgr Descr" AS BALLBRAND, b."Model Descr" AS BALLMODEL
FROM [Player_Master].[All]
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] a ON BALLBRAND = a."Mfgr Code" 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] b ON BALLMODEL = b."Model Code" 
WHERE "FIRST DAY" = @FIRSTDAY AND SID = @SID 
) BALLTABLE
LEFT OUTER JOIN
(
SELECT
row_number() OVER(PARTITION BY "Name" ORDER BY "PKey") AS IRONNUMBER,
"Name" AS PLAYERNAME, "Iron Club Code" AS IRONCLUBCODE, a."Mfgr Descr" AS IRONBRAND, b."Model Descr" AS IRONMODEL, "PKey"
FROM Player_Master.[Iron Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON "Iron Brand Code" = a."Mfgr Code"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON "Iron Model Code" = b."Model Code"
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID 
GROUP BY "Name", "Iron Club Code", a."Mfgr Descr", b."Model Descr", "PKey"
) IRONTABLE ON BALLTABLE.PLAYERNAME = IRONTABLE.PLAYERNAME
LEFT OUTER JOIN
(
SELECT
row_number() OVER(PARTITION BY "Name" ORDER BY "PKey") AS WOODNUMBER,
"Name" AS PLAYERNAME, "Wood Club Code" AS WOODCLUBCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS WOODBRAND,
ISNULL(b."Model Abbrev", b."Model Descr") AS WOODMODEL,
c."Size Descr" AS WOODSIZE,
ISNULL(d."Matl Abbrev", d."Matl Descr") AS WOODMATL,
"PKey"
FROM Player_Master.[Wood Detail]
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON "Wood Brand Code" = a."Mfgr Code"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON "Wood Model Code" = b."Model Code"
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON "Wood Size Code" = "Size Code"
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON "Wood Mat'l Code" = "Matl Code"
WHERE "First Day" = @FIRSTDAY AND "Survey ID" = @SID 
) WOODTABLE ON BALLTABLE.PLAYERNAME = WOODTABLE.PLAYERNAME AND COALESCE(IRONNUMBER, 0) = COALESCE(WOODNUMBER, 0)

GROUP BY BALLTABLE.PLAYERNAME, BALLBRAND, BALLMODEL, IRONCLUBCODE, IRONBRAND, IRONMODEL, WOODCLUBCODE, WOODBRAND, WOODMODEL, WOODSIZE, WOODMATL
--, BALLNUMBER, IRONNUMBER, WOODNUMBER
ORDER BY BALLTABLE.PLAYERNAME
*/




/*SELECT PLAYERNAME, a."Mfgr Descr" AS BALLBRAND, b."Model Descr" AS BALLMODEL,
"Iron Club Code" AS IRONCLUBCODE, e."Mfgr Descr" AS IRONBRAND, f."Model Descr" AS IRONMODEL,
 "Wood Club Code" AS WOODCLUBCODE,
ISNULL(a."Mfgr Abbrev", a."Mfgr Descr") AS WOODBRAND,
ISNULL(b."Model Abbrev", b."Model Descr") AS WOODMODEL,
c."Size Descr" AS WOODSIZE,
ISNULL(d."Matl Abbrev", d."Matl Descr") AS WOODMATL

FROM (SELECT * FROM [Player_Master].[All] WHERE "FIRST DAY" = @FIRSTDAY AND SID = @SID) x
LEFT OUTER JOIN (SELECT * FROM Player_Master.[Iron Detail] WHERE "First Day" = @FIRSTDAY and "Survey ID" = @SID) z ON PLAYERNAME = z.Name
LEFT OUTER JOIN (SELECT * FROM Player_Master.[Wood Detail] WHERE "First Day" = @FIRSTDAY and "Survey ID" = @SID) y ON PLAYERNAME = y.Name
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] a ON "Wood Brand Code" = a."Mfgr Code"
LEFT OUTER JOIN LKP.[Model Codes and Descr] b ON "Wood Model Code" = b."Model Code"
LEFT OUTER JOIN LKP.[Size Codes and Description] c ON "Wood Size Code" = "Size Code"
LEFT OUTER JOIN LKP.[Material Codes and Descript] d ON "Wood Mat'l Code" = "Matl Code"
LEFT OUTER JOIN LKP.[Manufacturer Codes and Desc] e ON "Iron Brand Code" = e."Mfgr Code"
LEFT OUTER JOIN LKP.[Model Codes and Descr] f ON "Iron Model Code" = f."Model Code"
LEFT OUTER JOIN [LKP].[Manufacturer Codes and Desc] g ON BALLBRAND = g."Mfgr Code" 
LEFT OUTER JOIN [LKP].[Model Codes and Descr] h ON BALLMODEL = h."Model Code"


WHERE  x."FIRST DAY" = @FIRSTDAY AND SID = @SID */


END
GO
