IF OBJECT_ID('MoneyBall.Fill_PrepareAndCleanUp') IS NOT NULL
    DROP PROCEDURE [MoneyBall].[Fill_PrepareAndCleanUp];
GO

-- =============================================
-- Author:		Alex Roytman
-- Create date: 02/07/2025
-- Description:	Fill table MoneyBall.WebsiteData1
-- =============================================

CREATE procedure [MoneyBall].[Fill_PrepareAndCleanUp]
(
	@Tour varchar(25),
	@PGASeason integer,
	@SportTourId tinyint
)
AS
Begin 
Print 'Start Fill_PrepareAndCleanUp'

begin tran
update [DARRELL_MASTER].[TV].[TVAudit] set Placement = 'Body' where TntFirstDay > '20250101' and Equip = 'Bag' and Placement is null
update [DARRELL_MASTER].[TV].[TVAudit] set Placement = 'Unspecified' where TntFirstDay > '20250101' and Placement is null
Update [DARRELL_MASTER].[TV].[TVAudit] set PlayerName = LTRIM(rtrim(PlayerName)) where [PlayerName]  LIKE '% ' OR [PlayerName] LIKE ' %'; Print '2'
commit tran


begin tran
update [DARRELL_MASTER].[TV].[TVAudit] set brand = replace(brand,'/','|') where brand like '%/%'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'ARBYS' where brand = 'ARBY`S'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'ARNOLD PALMER LOGO' where brand = 'ARNOLD PALMER'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'BFS' where brand = 'BFS GROUP'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'EIDE BAILLY' where brand = 'EIDEBAILLY'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'EVOLVE GOLF' where brand = 'EVOLVEGOLF'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'J. LINDEBERG' where brand = 'J LINDEBERG'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'J. STREICHER' where brand = 'J STREICHER'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'LA COSTE' where brand = 'LACOSTE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'LUMOS NETWORKS' where brand = 'LUMOS'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'RUSTOLEUM' where brand = 'RUST-OLEUM'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'SGF' where brand = 'SGF67'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'SGF' where brand = 'SGF59'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'THESCORE.COM' where brand = 'THE SCORE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'YOUNG ADJUSTMENT COMPANY' where brand = 'YOUNG ADJUSTMENT'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'WM MURRAY' where brand = 'WILLIAM MURRAY'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'ACTIVEPDF' where brand = 'ACTIVE PDF'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'CONTE OF FLORENCE' where brand = 'CONTE OF FLORNECE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'FAIRWAY & GREENE' where brand = 'FAIRWAY AND GREENE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'ASIANA' where brand = 'ASIANA AIRLINES'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'GREAT WEST' where brand = 'GREAT-WEST'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'JOHNNIE-O' where brand = 'JOHNNIE O'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'KAYNE ANDERSON' where brand = 'KAYNE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'K LOVE' where brand = 'K-LOVE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'LEVEL WEAR' where brand = 'LEVEL'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'OXFORD GOLF' where brand = 'OXFORD'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'RALPH LAUREN' where brand = 'RALPH  LAUREN'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'REALTREE' where brand = 'REAL TREE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'RUTH`S CHRIS' where brand = 'RUTH`S  CHRIS'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'RUTH`S CHRIS' where brand = 'RUTH''S CHRIS'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'SGF' where brand = 'SGF 67'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'PILL' where brand = 'THE PILL'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'WYNDHAM' where brand = 'WYNDHAM HOTEL'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'MCGETTIGAN`S' where brand = 'MCGETTIGAN'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'G-FORE' where brand = 'G/FORE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = '5HR ENERGY' where brand = '5 HR-ENERGY'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'RAIFFEISEN MEINE BANK' where brand = 'RAIFFEISEN MEINEBANK'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'PIRETTI' where brand = 'PIRRETI'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'MEGACORP' where brand = 'MEGA CORP'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'FITTEAM' where brand = 'FIT TEAM'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'TOPGOLF' where brand = 'TOP GOLF'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'AXIS1' where brand = 'AXIS 1'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'CLUBSWAN' where brand = 'CLUB SWAN'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'COLLEGE AFFILIATION' where brand = 'COLLEGE  AFFILIATION'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'DAVID HEARN FOUNDATION' where brand = 'DAVE HEARN FOUNDATION'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'EZ-GO' where brand = 'EZ -GO'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'FLECHA AZUL' where brand = 'FLETCHA AZUL'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'FLEX SEAL' where brand = 'FLEXSEAL'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'G|FORE' where brand = 'G-FORE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'JUMBOMAX' where brand = 'JUMBO MAX'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'MUTUAL OF OMAHA' where brand = 'MUTUA OF OMAHA'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'NIGHT DRAGON SECURITY' where brand = 'NIGHTDRAGON SECURITY'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'ONE STREAM' where brand = 'ONESTREAM'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'SENTINEL ONE' where brand = 'SENTINELONE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'SWITCH GRIPS' where brand = 'SWITCHGRIPS'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'TAYLORMADE' where brand = 'TAYOLORMADE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'CONCEAL.IO' where brand = 'CONCEALIO'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'EASYPOST' where brand = 'EASY POST'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'AMTRUST INSURANCE' where brand = 'AMTRUST'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'SINGLE STORE' where brand = 'SINGLESTORE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'SHINHAN BANK' where brand = 'SHINHAN'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'KEPNER-TREGOE' where brand = 'KEPNER TREGOE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'LEVEL WEAR' where brand = 'LEVELWEAR'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'THE MCCAULEY CO.' where brand = 'THE MCCULEY CO.'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'NO BULL' where brand = 'NOBULL'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'FIREMON' where brand = 'FIREMO'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'KORN FERRY' where brand = 'KORNFERRY'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'KOVITZ' where brand = 'KOVITA'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'MIZZEN & MAIN' where brand = 'MIZZEN + MAIN'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'MIZZEN & MAIN' where brand = 'MIZZEN+MAIN'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'JORDAN', model = NULL where brand = 'NIKE' and model = 'JORDAN'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = '4ACES' where brand = '4 ACES'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = '1HOTELS' where brand = '1'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'THE BATTLE`S END' where brand = 'BATTLE`S END'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'UNION HOME MORTGAGE' where brand = 'UNION  HOME MORTGAGE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'FOOTJOY' where brand = 'FOOT JOY'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'FLY HOUSE' where brand = 'FLYHOUSE'
update [DARRELL_MASTER].[TV].[TVAudit] set brand = 'AMPERSAND' where brand = '&'
update TV.TVAudit set brand = '1 HOTELS' where brand = '1HOTELS'
update TV.TVAudit set brand = '4PWT.COM' where brand = '4PWT'
update TV.TVAudit set brand = 'ABEILLE ASSURANCES' where brand = 'ABEILLE'
update TV.TVAudit set brand = 'ABEILLE ASSURANCES' where brand = 'ABELA ASSURANCE'
update TV.TVAudit set brand = 'ACER`S' where brand = 'ACERS'
update TV.TVAudit set brand = 'ADIDAS' where brand = 'ADIDDAS'
update TV.TVAudit set brand = 'ADMIRAL' where brand = 'ADIMIRAL'
update TV.TVAudit set brand = 'ADVENT HEALTH' where brand = 'ADVENTHEALTH'
update TV.TVAudit set brand = 'AEROMEXICO' where brand = 'AERO MEXICO'
update TV.TVAudit set brand = 'ALCONIX' where brand = 'ALCONICS'
update TV.TVAudit set brand = 'ALKALINE88' where brand = 'ALKALINE 88'
update TV.TVAudit set brand = 'ALSTON CONSTRUCTION' where brand = 'ALSTON'
update TV.TVAudit set brand = 'ANNEXUS' where brand = 'ANNEXUS GROUP'
update TV.TVAudit set brand = 'AOL' where brand = 'AOL.'
update TV.TVAudit set brand = 'ARNOLD PALMER LOGO' where brand = 'ARNOLD PALMER GOLF'
update TV.TVAudit set brand = 'BAJIT.COM' where brand = 'BAJIT'
update TV.TVAudit set brand = 'BAKER TILLY' where brand = 'BAKERTILLY'
update TV.TVAudit set brand = 'BANK PLUS' where brand = 'BANKPLUS'
update TV.TVAudit set brand = 'BASS PRO SHOPS' where brand = 'BASS PRO SHOP'
update TV.TVAudit set brand = 'BLUE YONDER' where brand = 'BLUEYONDER'
update TV.TVAudit set brand = 'BOUCHE' where brand = 'BOUCHEY'
update TV.TVAudit set brand = 'BRINKER`S JEWELERS' where brand = 'BRINKER`S JEWELERES'
update TV.TVAudit set brand = 'BRINKER`S JEWELERS' where brand = 'BRINKER`S JEWELER'
update TV.TVAudit set brand = 'BUBBA WHIPS' where brand = 'BUBBAWHIPS'
update TV.TVAudit set brand = 'BURBERRYS' where brand = 'BURBERRY'
update TV.TVAudit set brand = 'BURNS & WILCOX' where brand = 'BURNS & WICOX'
update TV.TVAudit set brand = 'CARDCONNECT' where brand = 'CARD CONNECT'
update TV.TVAudit set brand = 'CHERVO' where brand = 'CHRERVO'
update TV.TVAudit set brand = 'CJ GROUP' where brand = 'CJ'
update TV.TVAudit set brand = 'CJ O SHOPPING' where brand = 'CJ O SHOPPIING'
update TV.TVAudit set brand = 'CLOUD NINE' where brand = 'CLOUD 9'
update TV.TVAudit set brand = 'CLUNK' where brand = 'CLUNLC'
update TV.TVAudit set brand = 'COASTAL CLOUDS' where brand = 'COASTAL CLOUD'
update TV.TVAudit set brand = 'COCA COLA' where brand = 'COCA-COLA'
update TV.TVAudit set brand = 'COLLEGE AFFILIATION' where brand = 'COLLEGE AFFILITION'
update TV.TVAudit set brand = 'COOLBET' where brand = 'COOL BET'
update TV.TVAudit set brand = 'CO-OP' where brand = 'COOP'
update TV.TVAudit set brand = 'COSTATERRA' where brand = 'COSTA TERRA'
update TV.TVAudit set brand = 'COUNTRY INNS & SUITES' where brand = 'COUNTRY INNS AND SUITES'
update TV.TVAudit set brand = 'D.A. DAVIDSON' where brand = 'DA DAVIDSON'
update TV.TVAudit set brand = 'DAITO KENTAKU' where brand = 'DAITOKENTAKU'
update TV.TVAudit set brand = 'DEMAND SCIENCE' where brand = 'DEMAND SCEINCE'
update TV.TVAudit set brand = 'DESCENTE' where brand = 'DESCENT'
update TV.TVAudit set brand = 'DRAFT KINGS' where brand = 'DRAFTKINGS'
update TV.TVAudit set brand = 'DREAM FINDERS HOMES' where brand = 'DREAM FINDER HOMES'
update TV.TVAudit set brand = 'DRUH' where brand = 'DRUH BELT'
update TV.TVAudit set brand = 'DRUH' where brand = 'DRUH BELTS'
update TV.TVAudit set brand = 'DUFF & PHELPS' where brand = 'DUFF&PHELPS'
update TV.TVAudit set brand = 'DURAFAST 40' where brand = 'DURA FAST 40'
update TV.TVAudit set brand = 'E.HOME' where brand = 'E HOME'
update TV.TVAudit set brand = 'EARLYBIRD' where brand = 'EARLY BIRD'
update TV.TVAudit set brand = 'EASTSIDE GOLF' where brand = 'EAST SIDE GOLF'
update TV.TVAudit set brand = 'EIDE BAILLY' where brand = 'EIDE BALLY'
update TV.TVAudit set brand = 'ELITE GRIPS' where brand = 'ELITE GRIP'
update TV.TVAudit set brand = 'ELIXIRR' where brand = 'ELIX-IRR'
update TV.TVAudit set brand = 'ESCHERCLOUD AI' where brand = 'ESCHER CLOUD AI'
update TV.TVAudit set brand = 'EWING' where brand = 'EWINE'
update TV.TVAudit set brand = 'EZ-GO' where brand = 'EZ GO'
update TV.TVAudit set brand = 'FAIRCHILD ACQUISITION' where brand = 'FAIRCHILD ACQUISITIONS'
update TV.TVAudit set brand = 'FLECHA AZUL' where brand = 'FLECH AZUL'
update TV.TVAudit set brand = 'FOOTJOY' where brand = 'FOOT JOY'
update TV.TVAudit set brand = 'FOOTJOY' where brand = 'FOOJTOY'
update TV.TVAudit set brand = 'FORM FREE' where brand = 'FORMFREE'
update TV.TVAudit set brand = 'FRANKLIN TEMPLETON' where brand = 'FRANKLIN TEMP'
update TV.TVAudit set brand = 'FREEDOM 55 FINANCIAL' where brand = 'FREEDOM 55'
update TV.TVAudit set brand = 'FREEDOM 55 FINANCIAL' where brand = 'FREEDOM FINANCIAL'
update TV.TVAudit set brand = 'G|FORE' where brand = 'G FORE'
update TV.TVAudit set brand = 'G|FORE' where brand = 'GFORE'
update TV.TVAudit set brand = 'GLOIRE' where brand = 'GLOIR'
update TV.TVAudit set brand = 'GLOIRE' where brand = 'GLOIRE F'
update TV.TVAudit set brand = 'GOATLANE' where brand = 'GOATLAKE'
update TV.TVAudit set brand = 'GOATLANE' where brand = 'GOAT LANE'
update TV.TVAudit set brand = 'GOLDENWEST' where brand = 'GOLDEN WEST'
update TV.TVAudit set brand = 'GOLF 5' where brand = 'GOLF5'
update TV.TVAudit set brand = 'GOLF PRIDE' where brand = 'GOLF  PRIDE'
update TV.TVAudit set brand = 'GOOSE CREEK GOLF CLUB' where brand = 'GOOSE CREEK'
update TV.TVAudit set brand = 'GOOSE CREEK GOLF CLUB' where brand = 'GOOSE CREEK GC'
update TV.TVAudit set brand = 'GOOSE CREEK GOLF CLUB' where brand = 'GOOSE CREEK?'
update TV.TVAudit set brand = 'GREAT LIFE' where brand = 'GREATLIFE'
update TV.TVAudit set brand = 'GYM RENTAL COMPANY' where brand = 'GYMRENTAL COMPANY'
update TV.TVAudit set brand = 'HEALTH CHANNELS' where brand = 'HEALTH CHANNEL'
update TV.TVAudit set brand = 'HEART LAND' where brand = 'HEARTLAND'
update TV.TVAudit set brand = 'HOLDERNESS & BOURNE' where brand = 'HOLDERNESS'
update TV.TVAudit set brand = 'HOLDERNESS & BOURNE' where brand = 'HOLDERNESS AND BOURNE'
update TV.TVAudit set brand = 'HOME TOWN LENDERS' where brand = 'HOMETOWN LENDERS'
update TV.TVAudit set brand = 'HOMETEC' where brand = 'HOME TEC'
update TV.TVAudit set brand = 'HYFLYERS' where brand = 'HY FLYERS'
update TV.TVAudit set brand = 'ICAPITAL' where brand = 'ICAPITOL'
update TV.TVAudit set brand = 'IGL GOLF' where brand = 'IGL.GOLF'
update TV.TVAudit set brand = 'ISPS HANDA' where brand = 'ISPA HANDA'
update TV.TVAudit set brand = 'J. LINDEBERG' where brand = 'J LINDBERG'
update TV.TVAudit set brand = 'J. LINDEBERG' where brand = 'J. LINDBERG'
update TV.TVAudit set brand = 'J. LINDEBERG' where brand = 'J.LINDBERG'
update TV.TVAudit set brand = 'J. LINDEBERG' where brand = 'J.LINDEBERG'
update TV.TVAudit set brand = 'JA RESORTS & HOTELS' where brand = 'JA RESORTS AND HOTELS'
update TV.TVAudit set brand = 'JACK BUNNY' where brand = 'JACKBUNNY'
update TV.TVAudit set brand = 'JANI-KING' where brand = 'JANIKING'
update TV.TVAudit set brand = 'JET LINX' where brand = 'JET LYNX'
update TV.TVAudit set brand = 'JET LINX' where brand = 'JETLINX'
update TV.TVAudit set brand = 'JIG SAW' where brand = 'JIGSAW'
update TV.TVAudit set brand = 'J. LINDEBERG' where brand = 'JL'
update TV.TVAudit set brand = 'JOHNNIE WALKER' where brand = 'JOHHNIE WALKER'
update TV.TVAudit set brand = 'JUN & ROPE' where brand = 'JUN AND ROPE'
update TV.TVAudit set brand = 'K2INS' where brand = 'K2 INSURANCE'
update TV.TVAudit set brand = 'KB FINANCIAL' where brand = 'KB FINACIAL'
update TV.TVAudit set brand = 'KONICA MINOLTA' where brand = 'KONIKA MINOLTA'
update TV.TVAudit set brand = 'KORN FERRY' where brand = 'KORN FERRRY'
update TV.TVAudit set brand = 'KOVITZ' where brand = 'KOVITZ'
update TV.TVAudit set brand = 'KOVITZ' where brand = 'KOVITZ WEALTH MANAGEMENT'
update TV.TVAudit set brand = 'KRAMSKI' where brand = 'KRAMSKI PUTTERS'
update TV.TVAudit set brand = 'LA COSTE' where brand = 'LECOSTE'
update TV.TVAudit set brand = 'LECOM' where brand = 'LE COM'
update TV.TVAudit set brand = 'LEO CYBERSEC' where brand = 'LEO CYBER SECURITY'
update TV.TVAudit set brand = 'LEO PALACE 21' where brand = 'LEOPALACE'
update TV.TVAudit set brand = 'LG' where brand = 'LG SIGNATURE'
update TV.TVAudit set brand = 'LIFE WEAR' where brand = 'LIFEWEAR'
update TV.TVAudit set brand = 'LIFEBRAND' where brand = 'LIFE BRAND'
update TV.TVAudit set brand = 'LINCOLN FINANCIAL GROUP' where brand = 'LINCOLN FINANCIAL'
update TV.TVAudit set brand = 'LITEHOUSE' where brand = 'LITE HOUSE'
update TV.TVAudit set brand = 'LOU MALNATIS PIZZERIA' where brand = 'LOU MALNATI'
update TV.TVAudit set brand = 'LOU MALNATIS PIZZERIA' where brand = 'LOU MALNATI`S'
update TV.TVAudit set brand = 'LOUDMOUTH' where brand = 'LOUD MOUTH'
update TV.TVAudit set brand = 'MACDONALD HOTEL & RESORTS' where brand = 'MACDONALD HOTELS & RESORTS'
update TV.TVAudit set brand = 'MAESTRO DOBEL TEQUILA' where brand = 'MAESTRO DOBEL'
update TV.TVAudit set brand = 'MALBON' where brand = 'MALBON GOLF'
update TV.TVAudit set brand = 'MARCUS|GOLDMAN SACHS' where brand = 'MARCUS BY GOLMAN SACHS'
update TV.TVAudit set brand = 'MCDONALD`S' where brand = 'MCDONALDS'
update TV.TVAudit set brand = 'MCDONALD`S' where brand = 'MCDONALD''S'
update TV.TVAudit set brand = 'MIURA' where brand = 'MIURA GOLF'
update TV.TVAudit set brand = 'MIZUNO' where brand = 'MIZUNO PRO'
update TV.TVAudit set brand = 'MIZZEN & MAIN' where brand = 'MIZZEN AND MAIN'
update TV.TVAudit set brand = 'MIZZEN & MAIN' where brand = 'MIZZEN MAIN'
update TV.TVAudit set brand = 'MODERN WOODMAN' where brand = 'MODERN WOODMEN'
update TV.TVAudit set brand = 'MUGINO SATO' where brand = 'MUGINOSATO'
update TV.TVAudit set brand = 'MUNSINGWEAR' where brand = 'MUNSING WEAR'
update TV.TVAudit set brand = 'MUTUAL OF OMAHA' where brand = 'MUTUAL OMAHA'
update TV.TVAudit set brand = 'MY NAME`5 DODDIE' where brand = 'MY NAME`5 DOODIE'
update TV.TVAudit set brand = 'MY NAVI' where brand = 'MYNAVI'
update TV.TVAudit set brand = 'NATURE WORKS' where brand = 'NATUREWORKS'
update TV.TVAudit set brand = 'NEO JAPAN' where brand = 'NEOJAPAN'
update TV.TVAudit set brand = 'NEW YORK' where brand = 'NY'
update TV.TVAudit set brand = 'NIKE' where brand = 'NIIKE'
update TV.TVAudit set brand = 'NITTO CTO' where brand = 'NITTOU CTO'
update TV.TVAudit set brand = 'NO 1' where brand = 'NO1'
update TV.TVAudit set brand = 'NY GC' where brand = 'NEW YORK GC'
update TV.TVAudit set brand = 'OAKLEY' where brand = 'OAKLY'
update TV.TVAudit set brand = 'OBAYASHI' where brand = 'OBAYBSHI'
update TV.TVAudit set brand = 'OMNI HOTELS AND RESORTS' where brand = 'OMNI HOTELS & RESORTS'
update TV.TVAudit set brand = 'ONE FLIGHT' where brand = 'ONEFLIGHT'
update TV.TVAudit set brand = 'PACER ETF`S' where brand = 'PACER ETF'
update TV.TVAudit set brand = 'PAN KOREA' where brand = 'PAN KOR'
update TV.TVAudit set brand = 'PERFICIENT' where brand = 'PERFICENT'
update TV.TVAudit set brand = 'PGA TOUR' where brand = 'PGA'
update TV.TVAudit set brand = 'PGA TOUR' where brand = 'PGATOUR'
update TV.TVAudit set brand = 'PHILLIPS & COMPANY' where brand = 'PHILLIPS AND COMPANY'
update TV.TVAudit set brand = 'PICKELBALL CENTRAL' where brand = 'PICKLEBALL CENTRAL'
update TV.TVAudit set brand = 'PIN HIGH' where brand = 'PIN HIGH GOLF'
update TV.TVAudit set brand = 'PINNACLE FREIGHT' where brand = 'PINNACLE FREIGHT?'
update TV.TVAudit set brand = 'PLUS SPRINGER MOUNTAIN FARMS' where brand = 'PLUS SPRINGER  MOUNTAIN FARMS'
update TV.TVAudit set brand = 'Q CELLS' where brand = 'QCELLS'
update TV.TVAudit set brand = 'RADICOOL' where brand = 'RADI COOL'
update TV.TVAudit set brand = 'REESE`S' where brand = 'REESE'
update TV.TVAudit set brand = 'SALESFORCE' where brand = 'SALESEFORCE'
update TV.TVAudit set brand = 'SAMANTHA THAVASA' where brand = 'SAMATHA THAVASA'
update TV.TVAudit set brand = 'SAP LEONARDO' where brand = 'SAP  LEONARDO'
update TV.TVAudit set brand = 'SERVICE CREDIT UNION' where brand = 'SERVICE CREDIT  UNION'
update TV.TVAudit set brand = 'SHEPHERD`S' where brand = 'SHEPHERDS'
update TV.TVAudit set brand = 'SIMMONS BANK' where brand = 'SIMMON BANK'
update TV.TVAudit set brand = 'SIMPLY SPIKED LEMONADE' where brand = 'SIMPLY SPIKED'
update TV.TVAudit set brand = 'SKINFOOD' where brand = 'SKIN FOOD'
update TV.TVAudit set brand = 'SKY 72' where brand = 'SKY72'
update TV.TVAudit set brand = 'SOL-PAY' where brand = 'SOLPAY'
update TV.TVAudit set brand = 'SOUTHERN PIPE & SUPPLY' where brand = 'SOUTHERN PIPE AND SUPPLY'
update TV.TVAudit set brand = 'ST CHRISTOPHER' where brand = 'ST. CHRISTOPHER'
update TV.TVAudit set brand = 'ST. ANDREWS' where brand = 'ST ANDREWS'
update TV.TVAudit set brand = 'SWAGG' where brand = 'SWAG'
update TV.TVAudit set brand = 'SYMPLR' where brand = 'SYMPIR'
update TV.TVAudit set brand = 'SYMPLR' where brand = 'SYMPL'
update TV.TVAudit set brand = 'T.P. MILLS' where brand = 'TP MILLS'
update TV.TVAudit set brand = 'TAKANOYURI' where brand = 'TAKANO YURI'
update TV.TVAudit set brand = 'TEE UP' where brand = 'TEE-UP'
update TV.TVAudit set brand = 'TENEO' where brand = 'TENCO'
update TV.TVAudit set brand = 'TENTH REVOLUTION GROUP' where brand = 'TENTH REVOLUTION'
update TV.TVAudit set brand = 'THAI AIRWAYS' where brand = 'THAI ARIWAYS'
update TV.TVAudit set brand = 'THREE BOND' where brand = 'THREEBOND'
update TV.TVAudit set brand = 'THRIVE HIVE' where brand = 'THRIVEHIVE'
update TV.TVAudit set brand = 'TIGORA' where brand = 'TIBORA'
update TV.TVAudit set brand = 'TIMBER TECH' where brand = 'TIMBERTECH'
update TV.TVAudit set brand = 'T-MOBILE' where brand = 'T MOBILE'
update TV.TVAudit set brand = 'TOHOKU KENSETSU' where brand = 'TOHOKU KENSTSU'
update TV.TVAudit set brand = 'TOMMY ARMOUR' where brand = 'T. ARMOUR'
update TV.TVAudit set brand = 'TOYO TIRES' where brand = 'TOYO TIRE'
update TV.TVAudit set brand = 'TRADITION ENERGY' where brand = 'TRADITIONAL ENERGY'
update TV.TVAudit set brand = 'TRADITION ENERGY' where brand = 'TRADITIONS ENERGY'
update TV.TVAudit set brand = 'TRANS COSMOS' where brand = 'TRANSCOSMOS'
update TV.TVAudit set brand = 'TRENDY GOLF' where brand = 'TRENDYGOLF'
update TV.TVAudit set brand = 'TRIPLE A' where brand = 'TRIPLE A A'
update TV.TVAudit set brand = 'TRKHSE' where brand = 'TRK HSE'
update TV.TVAudit set brand = 'TROUBADOUR' where brand = 'TROUBADOR'
update TV.TVAudit set brand = 'TRUE SPEC GOLF' where brand = 'TRUE SPEC'
update TV.TVAudit set brand = 'USA' where brand = 'U.S.'
update TV.TVAudit set brand = 'UNION HOME MORTGAGE' where brand = 'UNION HOME MORTGAGEG'
update TV.TVAudit set brand = 'UNITI' where brand = 'UNIFI'
update TV.TVAudit set brand = 'UNRL' where brand = 'UNRL GOLF'
update TV.TVAudit set brand = 'URBAN GOLF PERFORMANCE' where brand = 'URBAN GOLF'
update TV.TVAudit set brand = 'USA' where brand = 'UNITED STATES'
update TV.TVAudit set brand = 'USA PICKLEBALL' where brand = 'USA PICKETBALL'
update TV.TVAudit set brand = 'V12' where brand = 'V TWELVE'
update TV.TVAudit set brand = 'VALSPAR' where brand = 'VALPSAR'
update TV.TVAudit set brand = 'VANTELIN' where brand = 'VANTELINE'
update TV.TVAudit set brand = 'VASAYO' where brand = 'VASAYA'
update TV.TVAudit set brand = 'VINEYARD VINES' where brand = 'VINEYARD'
update TV.TVAudit set brand = 'VINEYARD VINES' where brand = 'VINYARD VINES'
update TV.TVAudit set brand = 'VOLKSWAGEN' where brand = 'VOLKS WAGEN'
update TV.TVAudit set brand = 'W AIRWAYZ' where brand = 'W AIRWAYS'
update TV.TVAudit set brand = 'WACOAL' where brand = 'WACOL'
update TV.TVAudit set brand = 'WASTE CONNECTIONS' where brand = 'WASTE CONNECTION'
update TV.TVAudit set brand = 'WASTE CONNECTIONS' where brand = 'WASTE CONNECTIONS INC.'
update TV.TVAudit set brand = 'WE CHAT' where brand = 'WECHAT'
update TV.TVAudit set brand = 'WEST SHORE HOME' where brand = 'WEST SHORE HOMES'
update TV.TVAudit set brand = 'WILDCAT OIL TOOLS' where brand = 'WILD CAT OIL TOOLS'
update TV.TVAudit set brand = 'WORLD WIDE TECHNOLOGY' where brand = 'WORLD WIDE TECH'
update TV.TVAudit set brand = 'XA INVESTMENTS' where brand = 'XAINVESTMENTS'
update TV.TVAudit set brand = 'ZEN-NOH' where brand = 'ZENNO'
update TV.TVAudit set brand = 'ZEN-NOH' where brand = 'ZENNOH'
update TV.TVAudit set brand = 'TITLEIST', model = 'SCOTTY CAMERON' WHERE Brand = N'SCOTTY CAMERON'

commit tran



begin tran
--update tv.TVAudit set PlayerName = replace(PlayerName,' (Amateur)',''), ProAm = 1 where PlayerName like '%(Amateur)%'
update TV.TVAudit set Playername = 'Bacot, Armando (North Carolina|5)' where Playername = 'Bacot, Armando (N. Carolina|5)'
update TV.TVAudit set Playername = 'CABRERA BELLO, RAFAEL' where Playername = 'CABRERA BELLO, RAFA'
update TV.TVAudit set Playername = 'Davis, RJ (North Carolina|4)' where Playername = 'Davis, RJ (N. Carolina|4)'
update TV.TVAudit set Playername = 'EVERY, MATTHEW' where Playername = 'EVERY, MATT'
update TV.TVAudit set Playername = 'Girard, Joseph III (Syracuse|11)' where Playername = 'Girard III, Joseph (Syracuse|11)'
update TV.TVAudit set Playername = 'HAKU, YOSHIKAZU' where Playername = 'HAKU, YOSHIKZAU'
update TV.TVAudit set Playername = 'HOSONO, YUSAKU' where Playername = 'HOSONO, YUSAKUK'
update TV.TVAudit set Playername = 'IKEMURA, TOMOYO' where Playername = 'IKUMURA, TOMOYO'
update TV.TVAudit set Playername = 'JI, EUN HEE' where Playername = 'JI, EUN-HEE'
update TV.TVAudit set Playername = 'Jones, Robert (Iowa State|12)' where Playername = 'Jones, Robert (Iowa St|12)'
update TV.TVAudit set Playername = 'KIDO, MEGUMI' where Playername = 'KIDO, ,MEGUMI'
update TV.TVAudit set Playername = 'KOZUMA, KOTONO' where Playername = 'KOZUMA, KOTONO.'
update TV.TVAudit set Playername = 'LOVE III, DAVIS' where Playername = 'LOVE, DAVIS III'
update TV.TVAudit set Playername = 'Roberts, JWan (Houston|13)' where Playername = 'Roberts, J`Wan (Houston|13)'
update TV.TVAudit set Playername = 'AHN, SUN JU' where Playername = 'AHN, SUN-JU'
update TV.TVAudit set Playername = 'ARAKI, YUNA' where Playername = 'ARAKI, YUUNA'
update TV.TVAudit set Playername = 'BALLESTER, JOSE LUIS' where Playername = 'BALLESTER, JOSELE'
update TV.TVAudit set Playername = 'CHOI, HYE JIN' where Playername = 'CHOI, HYE-JIN'
update TV.TVAudit set Playername = 'CHOI, JIN-HO' where Playername = 'CHOI, JINHO'
update TV.TVAudit set Playername = 'CHUN, IN GEE' where Playername = 'CHUN, IN-GEE'
update TV.TVAudit set Playername = 'COLOMO, JAVI' where Playername = 'COLOMO, JAVIER'
update TV.TVAudit set Playername = 'DE LA FUENTE DEL VALLE, SANTIAGO' where Playername = 'DE LA FUENTE, SANTIAGO'
update TV.TVAudit set Playername = 'FENG, SHANSHAN' where Playername = 'FENG, SHAN-HAN'
update TV.TVAudit set Playername = 'FENG, SHANSHAN' where Playername = 'FENG, SHAN-SHAN'
update TV.TVAudit set Playername = 'HAN, SEUNG-SU' where Playername = 'HAN, SEUNGSU'
update TV.TVAudit set Playername = 'HANSEN, JOACHIM B.' where Playername = 'HANSEN, JOACHIM B'
update TV.TVAudit set Playername = 'HIDALGO PORTILLO, ANGEL' where Playername = 'HIDALGO, ANGEL'
update TV.TVAudit set Playername = 'ICHIHARA, KODAI' where Playername = 'ICHIHARA, KODIA'
update TV.TVAudit set Playername = 'JEON, MI JEONG' where Playername = 'JEON, MI-JEONG'
update TV.TVAudit set Playername = 'JUNG, YEON JU' where Playername = 'JUNG, YEON-JU'
update TV.TVAudit set Playername = 'KANG, KYUNG-NAM' where Playername = 'KANG, KYUNGNAM'
update TV.TVAudit set Playername = 'KANG, SOO YUN' where Playername = 'KANG, SOO-YUN'
update TV.TVAudit set Playername = 'KATSU, MINAMI' where Playername = 'KATSU, MIMAMI'
update TV.TVAudit set Playername = 'KEEFER, JOHNNY' where Playername = 'KEEFER, JOHN'
update TV.TVAudit set Playername = 'KIM, HYUNG SUNG' where Playername = 'KIM, HYUNG-SUNG'
update TV.TVAudit set Playername = 'KIM, NARI' where Playername = 'KIM, NA-RI'
update TV.TVAudit set Playername = 'KIM, SEONGHYEON' where Playername = 'KIM, SEONG-HYEON'
update TV.TVAudit set Playername = 'KIM, SEUNG HYUK' where Playername = 'KIM, SEUNG-HYUK'
update TV.TVAudit set Playername = 'KWON, KI TAEK' where Playername = 'KWON, K T'
update TV.TVAudit set Playername = 'LEE, D.H.' where Playername = 'LEE, DONGHWAN'
update TV.TVAudit set Playername = 'LEE, D.H.' where Playername = 'LEE, DONG-HWAN'
update TV.TVAudit set Playername = 'LEE, JAE KYEOUNG' where Playername = 'LEE, JAE-KYEONG'
update TV.TVAudit set Playername = 'LEE, JAE KYEOUNG' where Playername = 'LEE, JAEKYEOUNG'
update TV.TVAudit set Playername = 'LEE, JEONG EUN6' where Playername = 'LEE, JEONGEUN6'
update TV.TVAudit set Playername = 'LEE, JI HEE' where Playername = 'LEE, JI-HEE'
update TV.TVAudit set Playername = 'LEE, RICHARD T.' where Playername = 'LEE, RICHARD T'
update TV.TVAudit set Playername = 'NEMECZ, LUKAS' where Playername = 'NEMECZ, LUCAS'
update TV.TVAudit set Playername = 'OZAKI, NAOMICHI JOE' where Playername = 'OZAKI, NAOMICHI'
update TV.TVAudit set Playername = 'PARK, EUN-SHIN' where Playername = 'PARK, EUNSHIN'
update TV.TVAudit set Playername = 'RAMSAY, RICHIE' where Playername = 'RAMSAY, RICHARD'
update TV.TVAudit set Playername = 'ROOS, JAKOBUS' where Playername = 'ROOS, JAKE'
update TV.TVAudit set Playername = 'SATOH, YASUKO' where Playername = 'SATO, YASUKO'
update TV.TVAudit set Playername = 'SATTAYABANPHOT, ONNARIN' where Playername = 'SATTAYA, ONNARIN'
update TV.TVAudit set Playername = 'SATTAYABANPHOT, ONNARIN' where Playername = 'SATTAYA, O'
update TV.TVAudit set Playername = 'SONG, YOUNG HAN' where Playername = 'SONG, YOUNG-HAN'
update TV.TVAudit set Playername = 'SVENSSON, ADAM' where Playername = 'SVENNSON, ADAM'
update TV.TVAudit set Playername = 'THITIKUL, ATTHAYA' where Playername = 'THITIKUL, ATTHAYA (Amateur)'
update TV.TVAudit set Playername = 'WANG, JEUNG-HUN' where Playername = 'WANG, JEUNGHUN'
update TV.TVAudit set Playername = 'YANG, YOUNG EUN' where Playername = 'YANG, YONG EUN'

 
update tv.TVAudit set PlayerName = 'CABRERA BELLO, RAFAEL' where PlayerName = 'CABRERA-BELLO, RAFA'
update tv.TVAudit set PlayerName = 'CABRERA BELLO, RAFAEL' where PlayerName = 'CABRERA-BELLO, RAFA'
update tv.TVAudit set PlayerName = 'SCHNIEDERJANS, OLIVER' where PlayerName = 'SCHNIEDERJANS, OLLIE'
update tv.TVAudit set PlayerName = 'FERNANDEZ-CASTANO, GONZALO' where PlayerName = 'FDEZ-CASTANO, GONZALO'
update tv.TVAudit set PlayerName = 'FERNANDEZ-CASTANO, GONZALO' where PlayerName = 'FERNANDEZ-CASTANO,GONZALO'
update tv.TVAudit set PlayerName = 'YANG, YOUNG EUN' where PlayerName = 'YANG, Y.E.'
update tv.TVAudit set PlayerName = 'PAN, CHENG TSUNG' where PlayerName = 'PAN, C.T.'
update tv.TVAudit set PlayerName = 'SPIETH, JORDAN' where PlayerName = 'SPEITH, JORDAN'
update tv.TVAudit set PlayerName = 'HOSSLER, BEAU JR.' where PlayerName = 'HOSSLER, BEAU'
update tv.TVAudit set PlayerName = 'VAN ROOYEN, ERIK' where PlayerName = 'VAN ROOYAN, ERIK'
update tv.TVAudit set PlayerName = 'JIMENEZ, MIGUEL A.' where PlayerName = 'JIMENEZ, MIGUEL ANGEL'
update tv.TVAudit set PlayerName = 'PEREIRA, GUILLERMO MITO' where PlayerName = 'PEREIRA, MITO'
update tv.TVAudit set PlayerName = REPLACE(PlayerName, ' ', ' ') where PlayerName like'% %'
update tv.TVAudit set PlayerName = REPLACE(PlayerName, '  ', ' ') where PlayerName like'%  %'
update tv.TVAudit set PlayerName = REPLACE(PlayerName, ' *', '') where PlayerName like'% *'
update tv.TVAudit set PlayerName = 'AN, BYEONG-HUN' where PlayerName = 'AN, BYEONG HUN'
update tv.TVAudit set PlayerName = 'AN, BYEONG-HUN' where PlayerName = 'AN, BEN'
update tv.TVAudit set PlayerName = 'CHANG, YI-KEUN' where PlayerName = 'CHANG, YI KEUN'
update tv.TVAudit set PlayerName = 'CHAWRASIA, S.S.P' where PlayerName = 'CHAWRASIA, SSP'
update tv.TVAudit set PlayerName = 'CHIKKARANGAPPA, S' where PlayerName = 'CHIKKARANGAPPA, S.'
update tv.TVAudit set PlayerName = 'FITZPATRICK, MATTHEW' where PlayerName = 'FITZPATRICK, MATT'
update tv.TVAudit set PlayerName = 'FUDOH, YURI' where PlayerName = 'FUDO, YURI'
update tv.TVAudit set PlayerName = 'FUJIMOTO, YOSHINORI' where PlayerName = 'FUJIMOTO, YOSINORI'
update tv.TVAudit set PlayerName = 'HO, SK' where PlayerName = 'HO, S K'
update tv.TVAudit set PlayerName = 'ICHINOSE, YUKI' where PlayerName = 'ICHINOSE, YUKU'
update tv.TVAudit set PlayerName = 'IM, SUNG-JAE' where PlayerName = 'IM, SUNGJAE'
update tv.TVAudit set PlayerName = 'IM, SUNG-JAE' where PlayerName = 'IM, SUNG JAE'
update tv.TVAudit set PlayerName = 'ZALATORIS, WILLIAM' where PlayerName = 'ZALATORIS, WILL'
update tv.TVAudit set PlayerName = 'VAN TONDER, DANIE' where PlayerName = 'VAN TONDER, DANIEL'
update tv.TVAudit set PlayerName = 'WALLACE, MATTHEW' where PlayerName = 'WALLACE, MATT'
update tv.TVAudit set PlayerName = 'LIN, YU XIN' where PlayerName = 'LIN, YUXIN'
update tv.TVAudit set PlayerName = 'WILLETT, DANIEL' where PlayerName = 'WILLETT, DANNY'
update tv.TVAudit set PlayerName = 'KIM, JOO HYUNG' where PlayerName = 'KIM, TOM'
update tv.TVAudit set PlayerName = 'KIM, JOO HYUNG' where PlayerName = 'KIM, TIM'
update tv.TVAudit set PlayerName = 'ECHAVARRIA, NICOLAS' where PlayerName = 'ECHAVARRIA, NICO'
update tv.TVAudit set PlayerName = 'KIM, SI-WOO' where PlayerName = 'KIM, SI WOO'
update tv.TVAudit set PlayerName = 'KIM, SEONGHYEON' where PlayerName = 'KIM, S.H.'
update tv.TVAudit set PlayerName = 'LEE, KYOUNG-HOON' where PlayerName = 'LEE, K.H.'
update tv.TVAudit set PlayerName = 'ALEXANDER, TYE' where PlayerName = 'ALEXANDER, TYSON'
update tv.TVAudit set PlayerName = 'VARNER, HAROLD' where PlayerName = 'VARNER III, HAROLD'
update tv.TVAudit set PlayerName = 'MCGIRT, WILLIAM' where PlayerName = 'MCGIRT, WILL'
update tv.TVAudit set PlayerName = 'GOTTERUP, CHRIS' where PlayerName = 'GOTTERUP, CHRISTOPHER'
update tv.TVAudit set PlayerName = 'KANG, SUNG-HOON' where PlayerName = 'KANG, SUNG'
update tv.TVAudit set PlayerName = 'KANG, SUNG-HOON' where PlayerName = 'KANG, S.H.'
update tv.TVAudit set PlayerName = 'SODERBERG, SEBASTION' where PlayerName = 'SODERBERG, SEBASTIAN'
update tv.TVAudit set PlayerName = 'THOMPSON, ALEXIS' where PlayerName = 'THOMPSON, LEXI'
update tv.TVAudit set PlayerName = 'GHIM, DOUGLAS' where PlayerName = 'GHIM, DOUG'
update tv.TVAudit set PlayerName = 'LOPEZ-CHACARRA, EUGENIO' where PlayerName = 'CHACARRA, EUGENIO'
update tv.TVAudit set PlayerName = 'MOLLER, NIKLAS NORGAARD' where PlayerName = 'NORGAARD, NIKLAS'
update tv.TVAudit set PlayerName = 'DAVIS, CAMERON' where PlayerName = 'DAVIS, CAM'
update tv.TVAudit set PlayerName = 'LIST, DANIEL' where PlayerName = 'LIST, DANNY'
commit tran



begin tran
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = NULL where PlayerName =''
commit tran  
 
begin tran
update [DARRELL_MASTER].[Money].[WorldRank] 
set PlayerName = ltrim(PlayerNameOriginal) 
where ltrim(PlayerNameOriginal) in (select distinct PlayerName from Player_Master.PLAYERNAMES where [firstday] > '20240101')
and PlayerName is null and PGASeason = @PGASeason
commit tran



begin tran
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = ltrim(PlayerNameOriginal) where PlayerNameOriginal like ' %'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = ltrim(PlayerNameOriginal) where PlayerName like ' %'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = REPLACE(PlayerNameOriginal, '  ', ' ') where PlayerNameOriginal like '%  %'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = REPLACE(PlayerNameOriginal, ' ,', ',') where PlayerNameOriginal like '% ,%'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'GARNISH, JORDAN' where PlayerNameOriginal = 'GARNISH , JORDAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'GARNISH, JORDAN' where PlayerNameOriginal = ' GARNISH , JORDAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'GARNISH, JORDAN' where PlayerNameOriginal = ', JORDAN  GARNISH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KOORATANAPISAN, SUTIJET' where PlayerNameOriginal = ' KOORATANAPISAN, SUTIJET'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BROWN, CHRISTOPHER' where PlayerNameOriginal = 'BROWN, CHRIS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'COLOMO, JAVI' where PlayerNameOriginal = 'COLOMO , JAVIER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'COLOMO, JAVI' where PlayerNameOriginal = ', JAVIER COLOMO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GARNISH , JORDAN' where PlayerNameOriginal = ', JORDAN  GARNISH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, JI-HOON' where PlayerNameOriginal = 'LEE(OCT 1986), JIHOON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'LEE(DEC1982), DONGHA' where PlayerNameOriginal = 'LEE(1982), DONGHA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, JI-HOON' where PlayerNameOriginal = '1986), JIHOON LEE(OCT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CABRERA BELLO, RAFAEL' where PlayerNameOriginal = 'BELLO, RAFAEL CABRERA' 
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CABRERA BELLO, RAFAEL' where PlayerNameOriginal = 'CABRERA BELLO, RAFA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CARBALLO, MIGUEL ANGEL' where PlayerNameOriginal = 'ANGEL CARBALLO, MIGUEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BECK III, JAMES' where PlayerNameOriginal = 'BECK, JAMES III'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'COCHRAN, NICHOLAS' where PlayerNameOriginal = 'COCHRAN, NICHOLAS CASE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DUNCAN, TYLER' where PlayerNameOriginal = 'DUNCAN(JUL1989), TYLER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GIACOMAZZI JR., DINO' where PlayerNameOriginal = 'GIACOMAZZI, DINO JR'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GILLBERG, OLIVER' where PlayerNameOriginal = 'GILLBERG(AM), OLIVER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HANSEN, JB' where PlayerNameOriginal = 'B HANSEN, JOACHIM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BECK III, JAMES' where PlayerNameOriginal = 'III, JAMES BECK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BECK III, JAMES' where PlayerNameOriginal = 'BECK, JAMES III'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HOWELL III, CHARLES' where PlayerNameOriginal = 'III, CHARLES HOWELL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HOWELL III, CHARLES' where PlayerNameOriginal = 'HOWELL, CHARLES'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HURLEY III, BILLY' where PlayerNameOriginal = 'III, BILLY HURLEY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BRYAN, GEORGE IV' where PlayerNameOriginal = 'IV, GEORGE BRYAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOHANNESSEN, KRISTIAN KROGH' where PlayerNameOriginal = 'JOHANNESSEN, KRISTIAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CAZAUBON, RODOLFO' where PlayerNameOriginal = 'JNR, RODOLFO CAZAUBON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GIACOMAZZI JR., DINO' where PlayerNameOriginal = 'JR., DINO GIACOMAZZI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KANAYA, TAKUMI' where PlayerNameOriginal = 'KANAYA(AM), TAKUMI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, RICHARD H.' where PlayerNameOriginal = 'H. LEE, RICHARD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LOVE III, DAVIS' where PlayerNameOriginal = 'III, DAVIS LOVE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MACINTYRE, ROBERT' where PlayerNameOriginal = 'MACINTYRE(AM), ROBERT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MADSEN, MORTEN ORUM' where PlayerNameOriginal = 'MADSEN, MORTEN ORLUM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'O`NEIL, CONOR' where PlayerNameOriginal = 'O''NEIL, CONOR'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'O`NEILL, PATRICK' where PlayerNameOriginal = 'O''NEILL, PATRICK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN PELT, BO' where PlayerNameOriginal = 'PELT, BO VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'RODRIGUEZ, JOSE DE JESUS' where PlayerNameOriginal = 'DE JESUS RODRIGUEZ, JOSE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SAINZ, CARLOS JR.' where PlayerNameOriginal = 'JR, CARLOS SAINZ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SAINZ, CARLOS JR.' where PlayerNameOriginal = 'SAINZ, CARLOS JR'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHELTON IV, ROBBY' where PlayerNameOriginal = 'SHELTON, ROBBY IV'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHELTON IV, ROBBY' where PlayerNameOriginal = 'IV, ROBBY SHELTON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DER SPUY, ROURKE' where PlayerNameOriginal = 'SPUY, ROURKE VAN DER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DEN BERG, ULRICH' where PlayerNameOriginal = 'BERG, ULRICH VAN DEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DRIEL, DARIUS' where PlayerNameOriginal = 'DRIEL, DARIUS VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN MEIJEL, LARS' where PlayerNameOriginal = 'MEIJEL, LARS VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VAN NIEKERK, DANIE' where PlayerNameOriginal = 'NIEKERK, DANIE VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VAN NIEKERK, WERNER' where PlayerNameOriginal = 'NIEKERK, WERNER VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN ROOYEN, ERIK' where PlayerNameOriginal = 'ROOYEN, ERIK VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN TONDER, DANIE' where PlayerNameOriginal = 'TONDER, DANIE VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VARNER, HAROLD' where PlayerNameOriginal = 'III, HAROLD VARNER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DER WALT, DAWIE' where PlayerNameOriginal = 'WALT, DAWIE VAN DER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DER WALT, TJAART' where PlayerNameOriginal = 'WALT, TJAART VAN DER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VAN WEST, ROBBIE' where PlayerNameOriginal = 'WEST, ROBBIE VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN ZYL, JACO' where PlayerNameOriginal = 'ZYL, JACO VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DU PLESSIS, CJ' where PlayerNameOriginal = 'PLESSIS, CJ DU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DU PLESSIS, HENNIE' where PlayerNameOriginal = 'PLESSIS, HENNIE DU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DE STEFANI, CORRADO' where PlayerNameOriginal = 'STEFANI, CORRADO DE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DEL VAL, SAMUEL' where PlayerNameOriginal = 'VAL, SAMUEL DEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DEL MORAL, CARLOS' where PlayerNameOriginal = 'MORAL, CARLOS DEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DA SILVA, ADILSON' where PlayerNameOriginal = 'SILVA, ADILSON DA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, RICHARD T.' where PlayerNameOriginal = 'T LEE, RICHARD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, RICHARD T.' where PlayerNameOriginal = 'LEE, RICHARD TAEHOON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, RICHARD T.' where PlayerNameOriginal = 'TAEHOON LEE, RICHARD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOHNSON, RICHARD S.' where PlayerNameOriginal = 'S. JOHNSON, RICHARD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JIMENEZ, MIGUEL A.' where PlayerNameOriginal = 'A JIMENEZ, MIGUEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BRADSHAW, DAVID' where PlayerNameOriginal = 'S BRADSHAW, DAVID'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CARLSSON, MAGNUS' where PlayerNameOriginal = 'A CARLSSON, MAGNUS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, JEEV MILKHA' where PlayerNameOriginal = 'MILKHA SINGH, JEEV'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DER VALK, GUIDO' where PlayerNameOriginal = 'VALK, GUIDO VAN DER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'SMITH, JORDAN L' where PlayerNameOriginal = 'L SMITH, JORDAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'HSIEH, CHI-HSIEN' where PlayerNameOriginal = 'CHI-HSIEN, HSIEH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JUNG, SUNIL' where PlayerNameOriginal = 'BELL, SUNIL RICHARD JUNG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JUNG, SUNIL' where PlayerNameOriginal = 'RICHARD JUNG BELL, SUNIL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VAN DEN BERGH, DESNE' where PlayerNameOriginal = 'BERGH, DESNE VAN DEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'LIEN, CHI-WEI' where PlayerNameOriginal = 'CHI-WEI, LIEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'BAECH CHRISTENSEN, CHRISTIAN' where PlayerNameOriginal = 'CHRISTENSEN, CHRISTIAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'BAECH CHRISTENSEN, CHRISTIAN' where PlayerNameOriginal = 'CHRISTENSEN, CHRISTIAN BAECH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'NISSEN, NIKOLAJ E' where PlayerNameOriginal = 'E NISSEN, NIKOLAJ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'HAASTRUP, MARK F' where PlayerNameOriginal = 'F HAASTRUP, MARK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'GIACOMAZZI JR., DINO' where PlayerNameOriginal = 'GIACOMAZZI, DINO JR.'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'GRADECKI, MATEUSZ' where PlayerNameOriginal = 'GRADECKI(AM), MATEUSZ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'EL HALI, KARIM' where PlayerNameOriginal = 'HALI, KARIM EL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'EL HASSANI, YOUNES' where PlayerNameOriginal = 'HASSANI, YOUNES EL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'AN, BYEONG-HUN' where PlayerNameOriginal = 'HUN AN, BYEONG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'KIM, DANIEL JAE YONG' where PlayerNameOriginal = 'JAE YONG KIM, DANIEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DE JAGER, LOUIS' where PlayerNameOriginal = 'JAGER, LOUIS DE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DEJONGE, BRENDON' where PlayerNameOriginal = 'JONGE, BRENDON DE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'POTTER-JR, TED' where PlayerNameOriginal = 'JR, TED POTTER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'POTTER-JR, TED' where PlayerNameOriginal = 'POTTER JR, TED'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'POTTER-JR, TED' where PlayerNameOriginal = 'POTTER, TED'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'ULVEMAN JUEL-BERG, PHILIP' where PlayerNameOriginal = 'JUEL-BERG, PHILIP'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'ULVEMAN JUEL-BERG, PHILIP' where PlayerNameOriginal = 'JUEL-BERG, PHILIP ULVEMAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VERLAAR, PIERRE JR.' where PlayerNameOriginal = 'JUNIOR VERLAAR(AM), PIERRE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VERLAAR, PIERRE JR.' where PlayerNameOriginal = 'VERLAAR(AM), PIERRE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VERLAAR, PIERRE JR.' where PlayerNameOriginal = 'VERLAAR(AM), PIERRE JUNIOR'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'ESTRUP, KASPER K' where PlayerNameOriginal = 'K ESTRUP, KASPER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'LOPEZ LAZZARO, JOHANN' where PlayerNameOriginal = 'LAZZARO, JOHANN LOPEZ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'LOUBSER, HERMAN' where PlayerNameOriginal = 'LOUBSER(AM), HERMAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'WANG, WEI-LUN' where PlayerNameOriginal = 'LUN, WANG WEI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'LARA, JOSE MANUEL' where PlayerNameOriginal = 'MANUEL LARA, JOSE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DI NITTO, ENRICO' where PlayerNameOriginal = 'NITTO, ENRICO DI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DE POYEN, JULIEN' where PlayerNameOriginal = 'POYEN, JULIEN DE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'MUECK, KRISTOPHER R' where PlayerNameOriginal = 'R MUECK, KRISTOPHER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'GARCIA RODRIGUEZ, SEBASTIAN' where PlayerNameOriginal = 'RODRIGUEZ, SEBASTIAN GARCIA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'SCHOEB, GREGOIRE' where PlayerNameOriginal = 'SCHOEB(AM), GREGOIRE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'MUNOZ, JUAN SEBASTIAN' where PlayerNameOriginal = 'SEBASTIAN MUNOZ, JUAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'WANG, SHIH-JUI' where PlayerNameOriginal = 'SHIH-JUI, WANG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHIN, MICAH LAUREN' where PlayerNameOriginal = 'SHIN, MICAH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DE SMIDT(AM), DARIN' where PlayerNameOriginal = 'SMIDT(AM), DARIN DE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DE SMIDT, RUAN' where PlayerNameOriginal = 'SMIDT, RUAN DE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'JOHANSEN, EIRIK TAGE' where PlayerNameOriginal = 'TAGE JOHANSEN, EIRIK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VAN DER VAART, JURRIAN' where PlayerNameOriginal = 'VAART, JURRIAN VAN DER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'LI, XIN-YANG' where PlayerNameOriginal = 'XIN-YANG, LI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'SHUN, YAT HAK' where PlayerNameOriginal = 'YAT HAK, SHUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'VON DELLINGSHAUSEN, NICOLAI' where PlayerNameOriginal = 'DELLINGSHAUSEN, NICOLAI VON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'ARNOY, JARAND EKELAND' where PlayerNameOriginal = 'EKELAND ARNOY, JARAND'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, MIN WOO' where PlayerNameOriginal = 'LEE(AM), MINWOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DE LA RIVA, EDUARDO' where PlayerNameOriginal = 'RIVA, EDUARDO DE LA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DE DECKER, ANDRE' where PlayerNameOriginal = 'DECKER, ANDRE DE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ZHANG, XINJUN' where PlayerNameOriginal = 'XINJUN, ZHANG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ZHANG, XINJUN' where PlayerNameOriginal = 'XIN-JUN, ZHANG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'HUI-LIN, ZHANG' where PlayerNameOriginal = 'HUILIN, ZHANG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHELTON, ROBBY' where PlayerNameOriginal = 'SHELTON IV, ROBBY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHELTON, ROBBY' where PlayerNameOriginal = 'SHELTON, ROBBY IV'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHELTON, ROBBY' where PlayerNameOriginal = 'IV, ROBBY SHELTON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'TAYLOR, BEN' where PlayerNameOriginal = 'TAYLOR, BENJAMIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MUNOZ, SEBASTIAN' where PlayerNameOriginal = 'MUNOZ, JUAN SEBASTIAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MUNOZ, SEBASTIAN' where PlayerNameOriginal = 'MUNOZ, SEBASTIAN J'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN PELT, BO' where PlayerNameOriginal = 'VAN PELT, BO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HWANG, JUNG-GON' where PlayerNameOriginal = 'HWANG, JUNGGON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CABRERA BELLO, RAFAEL' where PlayerNameOriginal = 'BELLO, RAFA CABRERA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, WON JOON' where PlayerNameOriginal = 'LEE, WONJOON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JACOBSON, FREDRIK' where PlayerNameOriginal = 'JACOBSON(SEPT1974), FREDDIE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GHIM, DOUGLAS' where PlayerNameOriginal = 'GHIM, DOUG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'ZALATORIS, WILLIAM', PlayerName = 'ZALATORIS, WILLIAM' where PlayerNameOriginal = 'ZALATORIS, WILL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'ABERG, LUDVIG' where PlayerNameOriginal = 'ABERG(AM), LUDVIG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'BARRON, HAYDN' where PlayerNameOriginal = 'BARRON, HAYDN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'BROWN, HAMISH' where PlayerNameOriginal = 'BROWN(AM), HAMISH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'BURKE, CHRISTIAAN' where PlayerNameOriginal = 'BURKE(AM), CHRISTIAAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'CELLI, FILIPPO' where PlayerNameOriginal = 'CELLI(AM), FILIPPO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'DOBBELAAR, LOUIS' where PlayerNameOriginal = 'DOBBELAAR(AM), LOUIS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'FITZPATRICK, MATTHEW' where PlayerNameOriginal = 'FITZPATRICK, MATT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, JOO HYUNG' where PlayerNameOriginal = 'KIM, JOOHYUNG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerNameOriginal = 'PEREIRA, GUILLERMO MITO' where PlayerNameOriginal = 'MITO PEREIRA, GUILLERMO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'WALLACE, MATTHEW' where PlayerNameOriginal = 'WALLACE, MATT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YU, KEVIN' where PlayerNameOriginal = 'YU, CHUN-AN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GORDON, WILL' where PlayerNameOriginal = 'GORDON, WILLIAM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GRIFFIN, BEN' where PlayerNameOriginal = 'GRIFFIN(MAY1996), BENJAMIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SCHMID, MATTHIAS' where PlayerNameOriginal = 'SCHMID, MATTI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'STEVENS, SAM' where PlayerNameOriginal = 'STEVENS, SAMUEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VARNER, HAROLD' where PlayerNameOriginal = 'VARNER III, HAROLD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, SI-WOO' where PlayerNameOriginal = 'KIM, SI WOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, SI-WOO' where PlayerNameOriginal = 'KIM, SIWOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YUAN, CARL' where PlayerNameOriginal = 'YUAN, YECHUN CARL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YUAN, CARL' where PlayerNameOriginal = 'CARL YUAN, YECHUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YUAN, CARL' where PlayerNameOriginal = 'CARL YECHUN, YUAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YUAN, CARL' where PlayerNameOriginal = 'YECHUN, YUAN CARL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YUAN, CARL' where PlayerNameOriginal = 'YECHUN(AM), YUAN CARL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YUAN, CARL' where PlayerNameOriginal = 'YECHUN, YUAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DUPLESSIS, HENNIE' where PlayerNameOriginal = 'DU PLESSIS, HENNIE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PARK, SANG-HYUN' where PlayerNameOriginal = 'PARK(APR1983), SANGHYUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JEON, SEONGHYEON' where PlayerNameOriginal = 'JEON(MAR1993), SEONGHYEON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, TAE-HO' where PlayerNameOriginal = 'KIM, TAEHO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'POWER-HORAN, THOMAS' where PlayerNameOriginal = 'POWER HORAN, TOM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BROWN, LUKE' where PlayerNameOriginal = 'BROWN(JUNE1998), LUKE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KANG, YUN-SEOK' where PlayerNameOriginal = 'KANG, YUNSEOK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DING, WENYI' where PlayerNameOriginal = 'WENYI(AM), DING'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHANG, WEI-LUN' where PlayerNameOriginal = 'WEI LUN, CHANG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LOPEZ RIVAROLA, JAIME' where PlayerNameOriginal = 'RIVAROLA, JAMIE LOPEZ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MAAS, CHRISTIAAN' where PlayerNameOriginal = 'MAAS(AM), CHRISTIAAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HOEY, RICO' where PlayerNameOriginal = 'HOEY, RICHARD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HART DU PREEZ, JAMES' where PlayerNameOriginal = 'DU PREEZ JNR, JAMES'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CROUCH, A J' where PlayerNameOriginal = 'CROUCH, A.J.'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LIU, YAN-WEI' where PlayerNameOriginal = 'YANWEI, LIU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VICK, TRAVIS' where PlayerNameOriginal = 'VICK(AM), TRAVIS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SUGIURA, YUTA' where PlayerNameOriginal = 'SUGIURA(AM), YUTA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, JIN-SUNG' where PlayerNameOriginal = 'KIM(DEC1989), JINSUNG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHOI, CHUN-HO' where PlayerNameOriginal = 'CHOI, CHUNHO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KOBORI, KAZUMA' where PlayerNameOriginal = 'KOBORI(AM), KAZUMA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHIARELLA, ALEXANDER' where PlayerNameOriginal = 'CHIARELLA, ALEX'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CARD, JAY' where PlayerNameOriginal = 'CARD III, JAY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PUIG, DAVID' where PlayerNameOriginal = 'PUIG CURRIUS, DAVID'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, CHANG-GI' where PlayerNameOriginal = 'LEE, CHANG GI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KELLY, TEE-K' where PlayerNameOriginal = 'KELLY, TIMOTHY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MULLANEY, JORDAN' where PlayerNameOriginal = 'MULLANEY(DEC1993), JORDAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'NAGASAWA, SHO' where PlayerNameOriginal = 'NAGASAWA(SEPT1994), SHO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YAMASHITA, MASAYUKI' where PlayerNameOriginal = 'YAMASHITA(AM), MASAYUKI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GUAN, JEFFREY' where PlayerNameOriginal = 'GUAN(AM), JEFFREY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BENNETT, SAM' where PlayerNameOriginal = 'BENNETT(AM), SAM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'WELCH, PATRICK' where PlayerNameOriginal = 'WELCH(AM), PATRICK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ROSENMUELLER, THOMAS' where PlayerNameOriginal = 'ROSENMULLER, THOMAS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MANKE, R. J.' where PlayerNameOriginal = 'MANKE, RJ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'STALLINGS JR., STEPHEN' where PlayerNameOriginal = 'STALLINGS JR, STEPHEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GABRELCIK, NICK' where PlayerNameOriginal = 'GABRELCIK(AM), NICK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SURRATT, CALEB' where PlayerNameOriginal = 'SURRATT(AM), CALEB'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MACK, WILLIE III' where PlayerNameOriginal = 'MACK III, WILLIE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JARVIS, AARON' where PlayerNameOriginal = 'JARVIS(AM), AARON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KOCH, GREGORY' where PlayerNameOriginal = 'KOCH, GREG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ZUSKA, JIRI' where PlayerNameOriginal = 'ZUSKA(AM), JIRI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'THORBJORNSEN, MICHAEL' where PlayerNameOriginal = 'THORBJORNSEN(AM), MICHAEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ORTIZ, ALVARO' where PlayerNameOriginal = 'ORTIZ BECERRA, ALVARO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BROWN, BARCLAY' where PlayerNameOriginal = 'BROWN(AM), BARCLAY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HILL, CALUM' where PlayerNameOriginal = 'HILL(NOV1994), CALUM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = '' where PlayerNameOriginal = 'HILL(NOV1994), CALUM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'FYFE, CALUM' where PlayerNameOriginal = 'FYFE, CALUM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, KI-SANG' where PlayerNameOriginal = 'LEE, KISANG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SMITH, JORDAN' where PlayerNameOriginal = 'SMITH, JORDAN L'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'TARRIO, SANTIAGO' where PlayerNameOriginal = 'TARRIO BEN, SANTIAGO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'TARRIO, SANTIAGO' where PlayerNameOriginal = 'BEN, SANTIAGO TARRIO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN TONDER, DANIE' where PlayerNameOriginal = 'TONDER, DANIEL VAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN TONDER, DANIE' where PlayerNameOriginal = 'VAN TONDER, DANIEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'WARING, PAUL' where PlayerNameOriginal = 'WARING(FEB1985), PAUL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, MIN WOO' where PlayerNameOriginal = 'WOO LEE, MIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, MIN WOO' where PlayerNameOriginal = 'WOO, MIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, MIN WOO' where PlayerNameOriginal = 'LEE, MINWOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ANGLES, PEP' where PlayerNameOriginal = 'ANGLES ROS, PEP'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ANGLES, PEP' where PlayerNameOriginal = 'ROS, PEP ANGLES'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HANSEN, JB' where PlayerNameOriginal = 'B, JOACHIM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHOI, HO-SUNG' where PlayerNameOriginal = 'CHOI, HOSUNG TORA SAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHOI, HO-SUNG' where PlayerNameOriginal = 'TORA, HOSUNG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHOI, HO-SUNG' where PlayerNameOriginal = 'TORA SAN CHOI, HOSUNG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'AN, BYEONG-HUN' where PlayerNameOriginal = 'HUN, BYEONG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'IKEDA, YUTA' where PlayerNameOriginal = 'IKEDA(DEC1985), YUTA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MCLEOD, JAKE' where PlayerNameOriginal = 'MCLEOD, JAKE IAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MCLEOD, JAKE' where PlayerNameOriginal = 'IAN MCLEOD, JAKE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PEREIRA, GUILLERMO MITO' where PlayerNameOriginal = 'MITO, GUILLERMO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PRINSLOO, JACO' where PlayerNameOriginal = 'PRINSLOO, JACO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'STRYDOM, OCKIE' where PlayerNameOriginal = 'STRYDOM, OCKIE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'STRYDOM, TRISTEN' where PlayerNameOriginal = 'STRYDOM, TRISTEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'STRYDOM, JEAN-PAUL' where PlayerNameOriginal = 'STRYDOM, JEAN-PAUL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BACHEM, NICK' where PlayerNameOriginal = 'BACHEM, NICK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BLOMSTRAND, CHRISTOFER' where PlayerNameOriginal = 'BLOMSTRAND, CHRISTOFER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CALMELS, FRANCOIS' where PlayerNameOriginal = 'CALMELS, FRANCOIS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DEL REY, ALEJANDRO' where PlayerNameOriginal = 'DEL, ALEJANDRO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DEL REY, ALEJANDRO' where PlayerNameOriginal = 'REY, ALEJANDRO DEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GERMISHUYS, DEON' where PlayerNameOriginal = 'GERMISHUYS, DEON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HAINDL, ALEX' where PlayerNameOriginal = 'HAINDL, ALEX'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HIDALGO PORTILLO, ANGEL' where PlayerNameOriginal = 'PORTILLO, ANGEL HIDALGO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HIDALGO PORTILLO, ANGEL' where PlayerNameOriginal = 'HIDALGO PORTILLO, ANGEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HIDALGO PORTILLO, ANGEL' where PlayerNameOriginal = 'HIDALGO, ANGEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HOWIE, CRAIG' where PlayerNameOriginal = 'HOWIE, CRAIG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HUNDEBOLL JORGENSEN, OLIVER' where PlayerNameOriginal = 'JORGENSEN, OLIVER HUNDEBOLL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HUNDEBOLL JORGENSEN, OLIVER' where PlayerNameOriginal = 'HUNDEBOLL JORGENSEN, OLIVER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HUNDEBOLL JORGENSEN, OLIVER' where PlayerNameOriginal = 'HUNDEBOLL, OLIVER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOSHI, KHALIN HITESH' where PlayerNameOriginal = 'JOSHI, KHALIN H'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOSHI, KHALIN HITESH' where PlayerNameOriginal = 'H, KHALIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOSHI, KHALIN HITESH' where PlayerNameOriginal = 'H JOSHI, KHALIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KARLSSON, ANTON' where PlayerNameOriginal = 'KARLSSON, ANTON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KARLSSON, ROBERT S' where PlayerNameOriginal = 'KARLSSON, ROBERT S'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KARLSSON, JESPER' where PlayerNameOriginal = 'KARLSSON, JESPER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KARLSSON, ROBERT S' where PlayerNameOriginal = 'S KARLSSON, ROBERT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, MINKYU' where PlayerNameOriginal = 'KIM(FEB2001), MINKYU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, MINKYU' where PlayerNameOriginal = 'KIM(MARCH2001), MINKYU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOHANNESSEN, KRISTIAN KROGH' where PlayerNameOriginal = 'KROGH JOHANNESSEN, KRISTIAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOHANNESSEN, KRISTIAN KROGH' where PlayerNameOriginal = 'KROGH, KRISTIAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KRUGER, JBE' where PlayerNameOriginal = 'KRUGER, JBE`'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHIN, MICAH LAUREN' where PlayerNameOriginal = 'LAUREN SHIN, MICAH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHIN, MICAH LAUREN' where PlayerNameOriginal = 'LAUREN, MICAH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SHIN, MICAH LAUREN' where PlayerNameOriginal = 'SHIN, MICAH LAUREN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LENGDEN, OSCAR' where PlayerNameOriginal = 'LENGDEN, OSCAR'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LINARD, THOMAS' where PlayerNameOriginal = 'LINARD, THOMAS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LINDBERG, MIKAEL' where PlayerNameOriginal = 'LINDBERG, MIKAEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MOOLMAN, PIETER' where PlayerNameOriginal = 'MOOLMAN, PIETER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MOLLER, NIKLAS NORGAARD' where PlayerNameOriginal = 'NORGAARD MOLLER, NIKLAS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MOLLER, NIKLAS NORGAARD' where PlayerNameOriginal = 'NORGAARD, NIKLAS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PAPADATOS, DIMI' where PlayerNameOriginal = 'PAPADATOS, DIMITRIOS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SCHAPER, JAYDEN' where PlayerNameOriginal = 'SCHAPER, JAYDEN TREY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SCHAPER, JAYDEN' where PlayerNameOriginal = 'TREY SCHAPER, JAYDEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SCHOTT, FREDERIK' where PlayerNameOriginal = 'SCHOTT, FREDERIK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'THORNTON, SIMON' where PlayerNameOriginal = 'THORNTON, SIMON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHANTANANUWAT, RATCHANON TK' where PlayerNameOriginal = 'CHANTANANUWAT(AM), RATCHANON TK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHANTANANUWAT, RATCHANON TK' where PlayerNameOriginal = 'TK CHANTANANUWAT(AM), RATCHANON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHANTANANUWAT, RATCHANON TK' where PlayerNameOriginal = 'CHANTANANUWAT(AM), RATCHANON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DRIEL, DARIUS' where PlayerNameOriginal = 'VAN, DARIUS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VILJOEN, MJ' where PlayerNameOriginal = 'VILJOEN, MJ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VIRTO, BORJA' where PlayerNameOriginal = 'VIRTO ASTUDILLO, BORJA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DOU, ZECHENG' where PlayerNameOriginal = 'ZE-CHENG, MARTY DOU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DOU, ZECHENG' where PlayerNameOriginal = 'DOU ZECHENG, MARTY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DOU, ZECHENG' where PlayerNameOriginal = 'ZECHENG, MARTY DOU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DOU, ZECHENG' where PlayerNameOriginal = 'DOU, ZE-CHENG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DOU, ZECHENG' where PlayerNameOriginal = 'DOU, MARTY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'AHLAWAT, VEER' where PlayerNameOriginal = 'AHLAWAT, VEER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ALBERTSE, LOUIS' where PlayerNameOriginal = 'ALBERTSE, LOUIS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KRISTENSEN, NICOLAI B' where PlayerNameOriginal = 'KRISTENSEN, NICOLAI B'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KRISTENSEN, NICOLAI B' where PlayerNameOriginal = 'KRISTENSEN(MAY1992), NICOLAI B'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KRISTENSEN, NICOLAI B' where PlayerNameOriginal = 'B KRISTENSEN(MAY1992), NICOLAI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KRISTENSEN, NICOLAI B' where PlayerNameOriginal = 'KRISTENSEN(MAY1992), NICOLAI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BARNES, JASON' where PlayerNameOriginal = 'BARNES, JASON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BORIBOONSUB, DENWIT DAVID' where PlayerNameOriginal = 'BORIBOONSUB, DENWIT DAVID'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BORIBOONSUB, DENWIT DAVID' where PlayerNameOriginal = 'DAVID BORIBOONSUB, DENWIT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YUAN, CARL' where PlayerNameOriginal = 'CARL, YUAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CROWE, TRACE' where PlayerNameOriginal = 'CROWE(OCT1996), TRACE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CROWE, HARRISON' where PlayerNameOriginal = 'CROWE(AM), HARRISON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DE JAGER, LOUIS' where PlayerNameOriginal = 'DE, LOUIS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DAYDOU, ALEXANDRE' where PlayerNameOriginal = 'DAYDOU, ALEXANDRE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DUPLESSIS, HENNIE' where PlayerNameOriginal = 'DU, HENNIE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'FELDBORG NIELSEN, CHRISTOPHER' where PlayerNameOriginal = 'FELDBORG, CHRISTOPHER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'FELDBORG NIELSEN, CHRISTOPHER' where PlayerNameOriginal = 'FELDBORG NIELSEN, CHRISTOPHER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'FELDBORG NIELSEN, CHRISTOPHER' where PlayerNameOriginal = 'NIELSEN, CHRISTOPHER FELDBORG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'FORSSTROM, SIMON' where PlayerNameOriginal = 'FORSSTROM, SIMON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GIRRBACH, JOEL' where PlayerNameOriginal = 'GIRRBACH, JOEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GLENNEMO, JACOB' where PlayerNameOriginal = 'GLENNEMO, JACOB'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GROENEWALD, VAUGHN' where PlayerNameOriginal = 'GROENEWALD, VAUGHN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GROENEWALD, COERT' where PlayerNameOriginal = 'GROENEWALD, COERT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHEN, GUXIN' where PlayerNameOriginal = 'GUXIN, CHEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HORTAL, ANTONIO' where PlayerNameOriginal = 'HORTAL, ANTONIO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'THIMBA, TOTO JR' where PlayerNameOriginal = 'THIMBA JNR, TOTO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'THIMBA, TOTO JR' where PlayerNameOriginal = 'JNR, TOTO THIMBA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'THIMBA, TOTO JR' where PlayerNameOriginal = 'THIMBA(JNR), TOTO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'JOHN, ALLEN' where PlayerNameOriginal = 'JOHN, ALLEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KEARNEY, NIALL' where PlayerNameOriginal = 'KEARNEY, NIALL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KEYSER, MATHIAM' where PlayerNameOriginal = 'KEYSER, MATHIAM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KOCHHAR, KARANDEEP' where PlayerNameOriginal = 'KOCHHAR, KARANDEEP'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LINDELL, OLIVER' where PlayerNameOriginal = 'LINDELL, OLIVER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LINDELL, MALTE' where PlayerNameOriginal = 'LINDELL(AM), MALTE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHANG, WEI-LUN' where PlayerNameOriginal = 'LUN, CHANG WEI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MCINTYRE, PH' where PlayerNameOriginal = 'MCINTYRE, PH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MCINTYRE, DAVID' where PlayerNameOriginal = 'MCINTYRE, DAVID'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MOSTERT, DYLAN' where PlayerNameOriginal = 'MOSTERT, DYLAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MOYNIHAN, GAVIN' where PlayerNameOriginal = 'MOYNIHAN, GAVIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'OK, TAE-HOON' where PlayerNameOriginal = 'OK, TAEHOON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'OLSEN, AKSEL KRISTOFFER' where PlayerNameOriginal = 'OLSEN, AKSEL KRISTOFFER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'OLSEN, AKSEL KRISTOFFER' where PlayerNameOriginal = 'KRISTOFFER OLSEN, AKSEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PALMER, MICHAEL' where PlayerNameOriginal = 'PALMER, MICHAEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PRAKONGVECH, SETTEE' where PlayerNameOriginal = 'PRAKONGVECH, SETTEE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SAHLSTROM, CHRISTOPHER' where PlayerNameOriginal = 'SAHLSTROM, CHRISTOPHER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BRAR, JACK SINGH' where PlayerNameOriginal = 'SINGH BRAR, JACK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, AMRITINDER' where PlayerNameOriginal = 'SINGH, AMRITINDER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, DIGVIJAY' where PlayerNameOriginal = 'SINGH(JAN1972), DIGVIJAY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, ARJUN' where PlayerNameOriginal = 'SINGH(OCT1969), ARJUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BHATIA, ARJUN SINGH' where PlayerNameOriginal = 'BHATIA(AM), ARJUN SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, SANDEEP' where PlayerNameOriginal = 'SINGH, SANDEEP'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, RANJIT' where PlayerNameOriginal = 'SINGH, RANJIT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, KARAN PRATAP' where PlayerNameOriginal = 'SINGH, KARAN PRATAP'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHADHA, ABHIJIT SINGH' where PlayerNameOriginal = 'CHADHA, ABHIJIT SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHAUDHRI, ARJUN SINGH' where PlayerNameOriginal = 'CHAUDHRI, ARJUN SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GILL, DIGRAJ SINGH' where PlayerNameOriginal = 'GILL, DIGRAJ SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GILL, PUKHRAJ SINGH' where PlayerNameOriginal = 'GILL, PUKHRAJ SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GILL, VISHAV PRATAP SINGH' where PlayerNameOriginal = 'GILL, VISHAV PRATAP SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KULLAR, DEEPINDER SINGH' where PlayerNameOriginal = 'KULLAR, DEEPINDER SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'RAI, HIMMAT SINGH' where PlayerNameOriginal = 'RAI, HIMMAT SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SANDHU, JAIRAJ SINGH' where PlayerNameOriginal = 'SANDHU, JAIRAJ SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SANDHU, YUVRAJ SINGH' where PlayerNameOriginal = 'SANDHU, YUVRAJ SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SISODIA, SHIVENDRA SINGH' where PlayerNameOriginal = 'SISODIA, SHIVENDRA SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SEERHA, BISHMADPAL SINGH' where PlayerNameOriginal = 'SEERHA, BISHMADPAL SINGH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, KARTIK DIGVIJAY' where PlayerNameOriginal = 'SINGH(MAR1999), KARTIK DIGVIJAY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, GAURAV PRATAP' where PlayerNameOriginal = 'SINGH, GAURAV PRATAP'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, VISHAL' where PlayerNameOriginal = 'SINGH, VISHAL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, BRASHWARPAL' where PlayerNameOriginal = 'SINGH, BRASHWARPAL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PRATAP SINGH, KARAN' where PlayerNameOriginal = 'PRATAP SINGH, KARAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SANDHU, YUVRAJ SINGH' where PlayerNameOriginal = 'SINGH SANDHU, YUVRAJ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH CHADHA, ABHIJIT' where PlayerNameOriginal = 'SINGH CHADHA, ABHIJIT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SINGH, YUVRAJ' where PlayerNameOriginal = 'SINGH(AM), YUVRAJ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SENEKAL, JJ' where PlayerNameOriginal = 'SENEKAL, JJ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MAEAWAKURA, SHUNTA' where PlayerNameOriginal = 'MAEAWAKURA, SHUNTA'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'OTANI, SHUNSUKE' where PlayerNameOriginal = 'OHTANI, SHUNSUKE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'NIIMURA, SHUN' where PlayerNameOriginal = 'NIIMURA(AM), SHUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HAK, SHUN YAT' where PlayerNameOriginal = 'SHUN, YAT HAK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SIMONSEN, MARTIN LETH' where PlayerNameOriginal = 'SIMONSEN, MARTIN LETH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SIMONSEN, MARTIN LETH' where PlayerNameOriginal = 'LETH SIMONSEN, MARTIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'STARK, OSCAR' where PlayerNameOriginal = 'STARK, OSCAR'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'STARK, HUGO' where PlayerNameOriginal = 'STARK(AM), HUGO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SVENSSON, MARCUS' where PlayerNameOriginal = 'SVENSSON, MARCUS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'SVENSSON, JESPER' where PlayerNameOriginal = 'SVENSSON(MAR1996), JESPER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LEE, RICHARD T.' where PlayerNameOriginal = 'TAEHOON, RICHARD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'TINNING, NICOLAI' where PlayerNameOriginal = 'TINNING, NICOLAI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VAN DER VOORT, BOB' where PlayerNameOriginal = 'VAN DER VOORT(AM), BOB'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'VENTER, ALBERT' where PlayerNameOriginal = 'VENTER, ALBERT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'WIKSTROM, JOAKIM' where PlayerNameOriginal = 'WIKSTROM, JOAKIM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'YE, WO-CHENG' where PlayerNameOriginal = 'WOCHENG, YE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CHEN, PEICHENG' where PlayerNameOriginal = 'PEICHENG(AM), CHEN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BAI, BOBBY ZHENGKAI' where PlayerNameOriginal = 'ZHENGKAI, BAI BOBBY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BAI, BOBBY ZHENGKAI' where PlayerNameOriginal = 'BOBBY ZHENGKAI, BAI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, BAEL JUN' where PlayerNameOriginal = 'BAEL JUN, KIM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, HYUN UK' where PlayerNameOriginal = 'HYUN UK (AM), KIM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, DONG MIN' where PlayerNameOriginal = 'KIM(AM), DONGMIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, DONG MIN' where PlayerNameOriginal = 'KIM(AM), DONGMIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, NAM-HYUN' where PlayerNameOriginal = 'KIM(AM), NAMHUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, NAM-HYUN' where PlayerNameOriginal = 'KIM, NAMHUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, DO-HOON' where PlayerNameOriginal = 'KIM(APR1989), DOHOON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, MIN SU' where PlayerNameOriginal = 'KIM(APR1990), MINSU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, TAE-WOO' where PlayerNameOriginal = 'KIM(FEB1993), TAEWOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, DONGKWAN' where PlayerNameOriginal = 'KIM, DONGKWAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, DONGWON' where PlayerNameOriginal = 'KIM, DONGWON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, DOHOON' where PlayerNameOriginal = 'KIM(MAR1989), DOHOON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, BOHYUN' where PlayerNameOriginal = 'KIM, BOHYUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, CHANWOO' where PlayerNameOriginal = 'KIM, CHANWOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, CHANWOO' where PlayerNameOriginal = 'KIM(NOV-1999), CHANWOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, DANIEL JAE YONG' where PlayerNameOriginal = 'KIM, DANIEL JAE YONG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, GOOKMIN' where PlayerNameOriginal = 'KIM, GOOKMIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, JI-WOO' where PlayerNameOriginal = 'KIM, JIWOO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, JONGHARK' where PlayerNameOriginal = 'KIM, JONGHARK'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, JOON' where PlayerNameOriginal = 'KIM, JOON'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, JOONHO' where PlayerNameOriginal = 'KIM, JOONHO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, LEUNKWANG' where PlayerNameOriginal = 'KIM, LEUNKWANG'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, MIN JUN' where PlayerNameOriginal = 'KIM, MINJUN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, SEUNGMIN' where PlayerNameOriginal = 'KIM, SEUNGMIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, SHI ALEX' where PlayerNameOriginal = 'KIM, SHI ALEX'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KIM, YEUNSUB' where PlayerNameOriginal = 'KIM, YEUNSUB'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'PERSSON, JOAKIM' where PlayerNameOriginal = 'PERSSON, JOAKIM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'ARNOY, JARAND EKELAND' where PlayerNameOriginal = 'ARNOY, JARAND EKELAND'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CUARTERO BLANCO, EMILIO' where PlayerNameOriginal = 'CUARTERO BLANCO, EMILIO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CUARTERO BLANCO, EMILIO' where PlayerNameOriginal = 'BLANCO, EMILIO CUARTERO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'XIAO, BOWEN' where PlayerNameOriginal = 'BOWEN, XIAO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BOWEN, JAMES' where PlayerNameOriginal = 'BOWEN, JAMES'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BROWN, DANIEL A' where PlayerNameOriginal = 'BROWN, DANIEL A'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'BROWN, DANIEL A' where PlayerNameOriginal = 'BROWN(OCT1994), DANIEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CALDERON, MATIAS' where PlayerNameOriginal = 'CALDERON, MATIAS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DAVIDSE, KEENAN' where PlayerNameOriginal = 'DAVIDSE, KEENAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DE LEO, GREGORIO' where PlayerNameOriginal = 'DE LEO, GREGORIO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DE SMIDT, RUAN' where PlayerNameOriginal = 'DE SMIDT, RUAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LUMBANTORUAN, MATTHEW' where PlayerNameOriginal = 'LUMBANTORUAN(AM), MATTHEW'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KORB, RUAN' where PlayerNameOriginal = 'KORB, RUAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'CONRADIE, RUAN' where PlayerNameOriginal = 'CONRADIE, RUAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DELPODIO, MATTEO' where PlayerNameOriginal = 'DELPODIO, MATTEO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DOMINGO, AGUSTIN' where PlayerNameOriginal = 'DOMINGO, AGUSTIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DU PLESSIS, CJ' where PlayerNameOriginal = 'DU PLESSIS, CJ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HART DU PREEZ, JAMES' where PlayerNameOriginal = 'JNR, JAMES DU PREEZ'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DUBOIS, EDOUARD' where PlayerNameOriginal = 'DUBOIS, EDOUARD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'FRIEDRICHSEN, SEBASTIAN' where PlayerNameOriginal = 'FRIEDRICHSEN, SEBASTIAN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GANDAS, MANU' where PlayerNameOriginal = 'GANDAS, MANU'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'GREENE, DANIEL' where PlayerNameOriginal = 'GREENE, DANIEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HOLLICK, MICHAEL' where PlayerNameOriginal = 'HOLLICK, MICHAEL'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LANGFORS, PER' where PlayerNameOriginal = 'LANGFORS, PER'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LIPPARELLI, EDOARDO RAFFAELE' where PlayerNameOriginal = 'LIPPARELLI, EDOARDO RAFFAELE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LIPPARELLI, EDOARDO RAFFAELE' where PlayerNameOriginal = 'RAFFAELE LIPPARELLI, EDOARDO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'LARRANAGA, EDUARDO' where PlayerNameOriginal = 'LARRANAGA, EDUARDO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'DERBEZ TORRES, EDUARDO' where PlayerNameOriginal = 'DERBEZ(AM), EDUARDO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MCELROY, DERMOT' where PlayerNameOriginal = 'MCELROY, DERMOT'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MCGEE, RUAIDHRI' where PlayerNameOriginal = 'MCGEE, RUAIDHRI'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MCGEE, GARTH' where PlayerNameOriginal = 'MCGEE, GARTH'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MICHAEL, ANTHONY' where PlayerNameOriginal = 'MICHAEL, ANTHONY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'MURRAY, TOM' where PlayerNameOriginal = 'MURRAY(JAN1990), TOM'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'NORTJE, RIEKUS' where PlayerNameOriginal = 'NORTJE, RIEKUS'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'O`KENNEDY, HENNIE' where PlayerNameOriginal = 'O''KENNEDY, HENNIE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'O`KENNEDY, HENNIE' where PlayerNameOriginal = 'O`KENNEDY, HENNIE'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'KENNEDY, LLOYD' where PlayerNameOriginal = 'KENNEDY, LLOYD'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'POKE, BENJAMIN HENRY' where PlayerNameOriginal = 'POKE, BENJAMIN HENRY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'POKE, BENJAMIN HENRY' where PlayerNameOriginal = 'HENRY POKE, BENJAMIN'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'QUINTARELLI, NICCOLO' where PlayerNameOriginal = 'QUINTARELLI, NICCOLO'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'COCHA, TOMAS' where PlayerNameOriginal = 'COCHA, TOMMY'
update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = 'HILL, CALUM' where PlayerNameOriginal = 'HILL(NOV1994), CALUM'
--update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = '' where PlayerNameOriginal = ''
--update [DARRELL_MASTER].[Money].[WorldRank] set PlayerName = '' where PlayerNameOriginal = ''


--begin tran
--update [DARRELL_MASTER].[Money].[WorldRank] set CountryCode = 'NLD' where countrycode = 'Net'
commit tran


begin tran
update a
set a.playername = b.playername
from [DARRELL_MASTER].[Money].[WorldRank] a inner join 
(select distinct playernameoriginal, playername from [DARRELL_MASTER].[Money].[WorldRank] where not PlayerName is null) b
on a.PlayerNameOriginal = b.PlayerNameOriginal 
where a.PlayerName is null 
commit tran


Print 'Finished Fill_Prepare_Brand'; 
end
GO
