DROP VIEW IF EXISTS [dbo].[Missing_Players_in_PMF];
GO

CREATE VIEW dbo.Missing_Players_in_PMF
AS
SELECT     TOP (100) PERCENT n.PLAYERNAME, a.PLAYERNAME AS Expr1, n.SID, n.FIRSTDAY, n.INPUTNO
FROM         Player_Master.PLAYERNAMES AS n LEFT OUTER JOIN
                      Player_Master.[All] AS a ON n.PLAYERNAME = a.PLAYERNAME AND n.SID = a.SID AND n.FIRSTDAY = a.[FIRST DAY]
WHERE     (n.INPUTNO > 0) AND (a.PLAYERNAME IS NULL)
ORDER BY n.FIRSTDAY DESC
GO
